labgrid/external/usbstick.py

The USBStick.put_file() call supports a default destination parameter, if no
explicit destination is set, use only the basename of the uploadded file to copy
it to the root of the virtual usbstick.

usbstick: use only basename if the destination is not specified

---

.coveragerc
.travis.yml

Remove labgrid/protocols/* from coverage.

coveralls: exclude lines via .coveragerc and use it for travis

---

labgrid/driver/externalconsoledriver.py
labgrid/driver/sshdriver.py
labgrid/target.py

This removes the cleanup function and uses on_deactivate instead.
Do we deactivate the targets drivers after a successful test?

Remove cleanup function

---

labgrid/remote/client.py

By default only show a list of available places, with -v give
the more verbose variant. This behavior is analog to the
resources command.
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>

remote/client: add -v option for places command

---

labgrid/remote/client.py
labgrid/remote/common.py
labgrid/remote/coordinator.py
labgrid/remote/exporter.py

This is fixed upstream in Python 3.5.3 and 3.6.0.

remote: enable TCP_NODELAY for asyncio sessions

---

.travis.yml
dev-requirements.txt
labgrid/driver/__init__.py
labgrid/driver/onewiredriver.py
labgrid/driver/powerdriver.py
labgrid/protocol/__init__.py
labgrid/protocol/digitaloutputprotocol.py
labgrid/resource/__init__.py
labgrid/resource/onewireport.py
setup.py

Add onewire support to labgrid, needs a running onewire server at the moment.
WIP:
* Convert to managedResource
* Add to exporter
* Test over network

[RDY] Topic/onewire

---

labgrid/remote/client.py

This PR has two client fixes:
- add verbosity to the client export function for tests
- fix inaccessable places if they are fully found within another placename

remote/client: various fixes

---

dev-requirements.txt
setup.py

This includes the fix for the Python 3 releated bug in the RFC2217
support (pyserial/pyserial#180).

setup: require pyserial 3.3

---

labgrid/driver/common.py
labgrid/driver/fastbootdriver.py
labgrid/driver/usbloader.py

labgrid/driver: resolve relative paths in bootstrap and fastboot drivers

---

labgrid/driver/onewiredriver.py

Since onewire is going to be an extra in labgrid, we can't import it into the
global scope of the onewiredriver module, since it gets loaded by the reg_driver
call. Fix it by only importing onewire when we create a OneWirePIODriver.

driver/onewiredriver: import onewire when creating a new instance

---

labgrid/driver/bareboxdriver.py
labgrid/driver/shelldriver.py
labgrid/driver/ubootdriver.py
labgrid/resource/base.py
labgrid/resource/common.py
labgrid/resource/onewireport.py
labgrid/resource/power.py
labgrid/resource/serialport.py

The docstrings from yesterday.

driver,resource: add docstrings to multiple files

---

labgrid/remote/client.py

This allows the cli to set the delay time for cycle events.

remote/client: make delay time during power cycle configurable

---

doc/getting_started.rst

`labgrid-venv/bin/activate` must not be executed but sourced instead.

doc: getting_started: source virtualenv's activate

---

examples/shell/test_rt.py

pattern failed if min was a small number aligned with whitespaces

shell/test_rt: improve re pattern

---

labgrid/driver/powerdriver.py
tests/test_powerdriver.py

Convert the cmd_ str from config to a list for subprocess.check_call

driver/powerdriver: use shlex to split cmd

---

labgrid/driver/shelldriver.py

When a system was configured to not expect a password (maybe for
debugging purpose) but the shelldriver configuration had a password set,
login failed as the shelldriver only expected a "Password: " line.
This is handled now by also matching for a prompt even when a password
is configured. Additionally, an explicit Exception will be raised now
when no password is configured but the system expects one.

shelldriver: expect empty password login despite password is provided

---

doc/configuration.rst
doc/usage.rst

This commit also adds an explicit label to the sshdriver in configuration.rst to
link from another document via the :ref: markup.

doc/usage: fix links for SSHDriver and HawkbitTestClient

---

dev-requirements.txt

A recent autobahn update broke our tests since crossbar has not been updated to
use the new version yet. Pin our autobahn and crossbar version, we'll update
them by hand in the future.
Signed-off-by: Rouven Czerwinski  <r.czerwinski@pengutronix.de>

dev-requirements: pin autobahn and crossbar to a specific version

---

labgrid/remote/client.py

Suppose we have the following places:
```
$ labgrid-client places
1003 (rhi:nitrogen6x)
4009 (nitrogen6x-a)
4011 (nitrogen6x-b)
```
Currently, the pattern "nitrogen6x" would match multiple places, even for user rhi:
```
$ whoami
rhi
$ labgrid-client -p nitrogen6x show
labgrid-client: error: pattern nitrogen6x matches multiple places (4011, 1003, 4009)
```
I prefer having short aliases so I dont have to type (and remember) so many characters. But even if I specify the exact alias for the place, it also matches for other places which are not in my namespace, and which I usually need don't work with.
This patch prefers matching the user namespace if the full pattern matches the alias, so that "nitrogen6x" now matches place 1003 for user rhi.

remote: prefer place aliases in user namespace for full matches

---

doc/configuration.rst

See labgrid/strategy/ubootstrategy.py, line 28

doc: UBootStrategy has state 'uboot', not 'barebox'

---

labgrid/driver/shelldriver.py
setup.py

This implementation starts the respective sender or receiver on the target and then uses tehmaze's [xmodem][] Python implementation to transfer files over the serial console. It can work with busybox's `rx` (only for receiving on the target) or `lrz`/`lsz` from [lrzsz][] on the target, and autodetects which commands are available.
XMODEM is a very simple, but also very historic protocol with some quirks. See the comment in `labgrid.driver.ShellDriver._put()` for some insight and workarounds.
Unfortunately, after the peer on the target has been started, there is no way to stop it if the transfer fails and get back to a shell prompt, since the peer on the target interprets everything on the console as XMODEM messages. lsz's `--min-bps` option does not seem to work very good (but are …

ShellDriver: implement file transfer support via XMODEM

---

doc/configuration.rst
labgrid/driver/qemudriver.py

In case we want to test only a bootloader we need to support use cases where we
don't need a kernel or rootfs. Also add support to load flash images into qemu
to support booting a bootloader.

qemudriver: make kernel, rootfs and boot_args optional, add flash

---

doc/configuration.rst
labgrid/driver/bareboxdriver.py

If 'quiet' is used as linux bootarg, you may adjust the bootstring.

bareboxdriver: add bootstring argument

---

tests/test_crossbar.py
tests/test_onewire.py

pytest.skip() only works in individual test function, use the proper pytestmark
variable to skip unavailable tests at the module level. Also introduce this
mechanism for the onewire tests.

tests: properly skip tests at the module level

---

labgrid/config.py

The Config class retrieves a base path to resolve paths. This allows a relative
specification in the yaml configuration. The caller can pass a non
absolute path, call abspath before retrieving the base path.

config: retrieve absolute path before retrieving base

---

doc/usage.rst
labgrid/config.py
labgrid/pytestplugin/fixtures.py

This commit adds the ability to save environment information in the junit xml
file.
I'm not sure we want to do this in the env fixture, but the configuration gets not parsed beforehand and all the necessary information is available here.
TODO:

fixtures: save env information as xml properties

---

.crossbar/config.yaml

The coordinator does not correctly detect a disconnected exporter as long as no
data is send over the connection. Enable auto_pings to detect a disconnected
exporter.
References: https://github.com/crossbario/crossbar/issues/980

crossbar: enable pings to detect tcp timeouts

---

.travis.yml

The python3.6 archive from travis contains setuptools 36.2.0 which breaks if
additional packages are installed when setuptools is upgraded. Work around the
issue by explicitly upgrading setuptools before installing our packages.
More details in pypa/setuptools#1086

travis.yml: work around pypa/setuptools#1086

---

labgrid/driver/serialdriver.py
labgrid/remote/client.py
labgrid/target.py
man/labgrid-client.1
man/labgrid-client.rst

This adds support for strategy states to the labgrid client.
TODO:

Add remote client state support

---

labgrid/driver/shelldriver.py

This was a typo in the original pull-request.
Fixes #94, again.
Signed-off-by: Roland Hieber <r.hieber@pengutronix.de>

driver/shelldriver: fix object has no attribute _put_file

---

labgrid/remote/client.py
labgrid/remote/common.py
labgrid/remote/coordinator.py

Matches can now have an optional name. When a resource matches a named
ResourceMatch, it will be made available on the client under that name.
This is useful when using multiple resources of the same class in one
target.
Note that clients and coordinator must be updated together, as the
older clients do not understand the 'rename' field.

remote: support named matches

---

labgrid/driver/sshdriver.py

On every ssh-connection we get a "Warning: Permanently added '...' (RSA) to the list of known hosts."
This will add a option to the ssh client to suppress the output of warning messages.

add ssh commandline to supress warning

---

doc/usage.rst

After reading PR #134, I realized that the step reporter and debug logging for
pytest are undocumented. Add the documentation in the pytest plugin section.

doc/usage: document step reporter and debug logging.

---

CHANGES.rst
doc/development.rst
doc/overview.rst
doc/usage.rst
labgrid/binding.py
labgrid/driver/powerdriver.py
labgrid/exceptions.py
labgrid/factory.py
labgrid/remote/client.py
labgrid/resource/remote.py
labgrid/target.py
tests/conftest.py
tests/test_bareboxdriver.py
tests/test_environment.py
tests/test_externalconsoledriver.py
tests/test_factory.py
tests/test_onewire.py
tests/test_powerdriver.py
tests/test_qemudriver.py
tests/test_resource.py
tests/test_serialdriver.py
tests/test_serialport.py
tests/test_shelldriver.py
tests/test_sshdriver.py
tests/test_strategy.py
tests/test_target.py
tests/test_usbemulator.py

This adds names to Resources and Drivers, which allows us to have multiple instances of the same class in one Target.
PR #123 needs to be merged first.

multi-instance named resources and drivers

---

CHANGES.rst
doc/development.rst
labgrid/autoinstall/main.py
labgrid/binding.py
setup.py
tests/test_autoinstall.py

This implements a new stand-alone tool for labgrind, which uses an environment config file with embedded python code to automatically install software to multiple targets.
PR #124 needs to be merge before this.

implement autoinstaller tool

---

doc/configuration.rst
labgrid/driver/ubootdriver.py

The UBootDriver did not correctly interrupt the autoboot, resulting in it
swallowing one character for the next command. Interrupt the autoboot and while
at it also make it configurable like the BareboxDriver
Fixes #117

ubootdriver: configurable interrupt and correct autoboot

---

setup.py

This is a workaround for Issue #141. We'll introduce a proper fix later on.
Fixes #141 

setup: workaround for the coordinator extra install

---

doc/getting_started.rst

This describes how to install the requirements and gives an
overview how to build the documentation.
Signed-off-by: Chris Fiege <c.fiege@pengutronix.de>

doc: added info how to build documentation to getting_started

---

dev-requirements.txt
setup.py

Attrs 17.3.0 changes the attribute order for classes using multiple
inheritance, causing problems with default/non-default attributes.

setup, requirements: avoid attrs 17.3.0

---

doc/configuration.rst
labgrid/driver/sshdriver.py
labgrid/resource/networkservice.py

* the networkservice resource has a new password property - if it is set
the sshdriver will login with sshpass (needs to be installed) instead
of the key file
Signed-off-by: Tobi Gschwendtner <tg@bloks.de>

support for ssh password

---

labgrid/driver/fastbootdriver.py

added the "continue" command for fastboot.
This particulary useful to run a "special fastboot" uboot version
which always starts in fastboot mode, enableling flashing without
any external trigger. After exiting the fastboot mode with the
"continue" command uboot will continue to boot normally.
Signed-off-by: Tobi Gschwendtner <tg@bloks.de>

add fastboot continue command

---

labgrid/driver/qemudriver.py
labgrid/driver/sshdriver.py
labgrid/remote/exporter.py

These are probably copy and paste errors from https://docs.python.org/3.5/library/subprocess.html#subprocess.Popen.communicate

TimeoutExpired is a subprocess Error

---

labgrid/driver/power/gude24.py

This driver adds support for Gude Expert Power Control 8080 an devices
alike.
This driver is based on the gude.py-driver but is adapted to
* the new number of ports,
* the new URL for setting values and
* the new format and URL for getting values.
Signed-off-by: Chris Fiege <c.fiege@pengutronix.de>

driver/power: add support for Gude Expert Power Control 8080

---

labgrid/driver/sshdriver.py

Signed-off-by: Tobi Gschwendtner <tg@bloks.de>
this fixes some "strange" ssh behavior for me where the ssh master seems to got to background too early (im missing 2 debug messages in those cases) sometimes (about every 20 tries) on some machines and i then get connection refused errors when trying to connect via the control socket.

changed "-f" option for SSH master to "-n"

---

labgrid/resource/udev.py

replaced the static USB ids in the fastboot resource with configurable properties
Signed-off-by: Tobi Gschwendtner <tg@bloks.de>
This is necessary for us since we use different USB IDs.
Once we agreed on this i will update the documentation.
Might be interesting for other USB resources as well...

configurable USB ids for fastboot

---

labgrid/remote/exporter.py

The ApplicationRunner sets up its own logging infrastructure, instead of setting
it up again in our application, pass the level to the ApplicationRunner.

remote/exporter: pass debug level to ApplicationRunner

---

labgrid/resource/udev.py

Before this change every action which is not in one of the previous cases would
remove the device and set availability to false. This includes the 'bind'
action. Remove the device only if the device unbinds.

resource/udev: remove devices only on unbind

---

CHANGES.rst
doc/conf.py
labgrid/config.py
labgrid/target.py
setup.cfg

This PR fixes the errors during documentation compilation. The last commit is a very dirty hack, but works for now. I'll dig into apidoc some more if we want to drop that commit.

Fix documentation compilation

---

labgrid/remote/client.py

microcom console was missing capability to adjust speed even though
resource.speed exist.

remote/client: Added missing speed configuration for microcom console

---

doc/overview.rst

The overview section also has an Installation section. Remove it since it's outdated and the installation procedure fits into getting started better anyway.

Remove leftover installation section from overview

---

labgrid/config.py

Reads all shell environment variables named LG_* and adds these to the substitution list used by !template in the YAML config file.
Ex. a place can thus be specified via the environment
`export LG_PLACE=kjeldsboard
`
And in local.yaml write
```
targets:
main:
resources:
RemotePlace:
name: !template $LG_PLACE
```
In this way, the same config can be used on several targets without editing before running pytest.

map LG_* variables from OS environment into YAML config file 

---

doc/configuration.rst
examples/strategy/quartusstrategy.py
labgrid/driver/__init__.py
labgrid/driver/quartushpsdriver.py

Adds the driver itself, an example strategy and documentation.
The example strategy can be used like this:
``` yaml
targets
my-target:
resources:
RemotePlace:
name: 'my-target'
drivers:
- QuartusHPSDriver: {}
- SerialDriver:
txdelay: 0.01
- NetworkPowerDriver:
delay: 5.0
- BareboxDriver:
prompt: 'barebox@[^:]+:[^ ]+ '
autoboot: "abort autoboot"
interrupt: "\x03"
- ShellDriver:
prompt: 'root@[^:]+:[^ ]+'
login_prompt: ' login: '
username: 'root'
- QuartusHPSStrategy:
image_xload: /path/to/barebox-xload.img
image: /path/to/barebox.img
imports:
- examples/strategy/quartusstrategy.py
```

driver/quartushpsdriver: add support for Quartus HPS

---

labgrid/remote/client.py
labgrid/remote/exporter.py
labgrid/resource/remote.py
man/Makefile
man/labgrid-client.1
man/labgrid-client.rst
man/labgrid-exporter.1
man/labgrid-exporter.rst

Uses the environment variable LG_CROSSBAR and LG_CROSSBAR_REALM as defaults for crossbar URL, if they are set.

Search environment for crossbar

---

labgrid/driver/bareboxdriver.py

Commands like ubiformat can take longer than the default 30 seconds. Allow this.

bareboxdriver: add timeout to run()/run_check()

---

doc/configuration.rst
labgrid/driver/__init__.py
labgrid/driver/smallubootdriver.py

This patch adds a driver for really small (and thus stripped down)
UBoot drivers.
This UBoots do not have:
* A real password prompt
* An echo command
* The possibility to print the return code of a command
This driver copes with these limitations.
Tested against the stock-uboot on a TP-Link WR841N v11.
Signed-off-by: Chris Fiege <chris@tinyhost.de>

driver/smallubootdriver: add driver for small UBoots

---

labgrid/remote/exporter.py
man/labgrid-exporter.1
man/labgrid-exporter.rst

When exporting USBSerialPort the exporter exports the host as the hostname. This may however not always resolve. 
setting LG_HOSTNAME to ex an IP address will override gethostname() in the exporter
This variable can be used with ex. USBSerialPort, USBGenericExport, USBSigrokExport
Tested with USBSerialPort only.

Use --hostname to override export host name

---

labgrid/driver/shelldriver.py
labgrid/driver/sshdriver.py

Problem is described in this issue https://github.com/labgrid-project/labgrid/issues/203 
This PR solves this by allowing the .run method for the SSHDriver and the ShellDriver to take extra arguments. All tests that have conflicting characters must be rewritten.
```
stdout, stderr, returncode = command.run("/tmp/pcm52test/test-registration", codec = "iso-8859-1" )
stdout, stderr, returncode = command.run("/tmp/pcm52test/test-registration", codecerrors = "ignore" )
stdout, stderr, returncode = command.run("/tmp/pcm52test/test-registration", codec = "iso-8859-1", codecerrors = "ignore" )
```
The parameters are passed to str.decode(), for more information on possible parameters see https://docs.python.org/3/howto/unicode.html
The defaults is "utf-8" and strict, which is also the defaults for …

Add codec and decodeerrors parameters to .run methods on SSHDriver and ShellDriver

---

doc/configuration.rst
examples/usbsdmux/local.yaml
examples/usbsdmux/test_sdmux.py
labgrid/driver/__init__.py
labgrid/driver/networkusbstoragedriver.py
labgrid/driver/usbsdmuxdriver.py
labgrid/driver/usbstorage.py
labgrid/remote/exporter.py
labgrid/resource/__init__.py
labgrid/resource/remote.py
labgrid/resource/udev.py

This adds support for the quite useful SD card juggler from Pengutronix (https://www.pengutronix.de/de/2017-10-23-usb-sd-mux-automated-sd-card-juggler.html) finally allowing to use it for automated testing with labgrid.
I also added a lg-command `sd-mux` to switch the USB-SD-Mux via `labgrid-client` but kept it out of this series because not being sure about how generic this is.
Despite the actual `/dev/sgX` device the Muxer uses is a `scsi_generic` one, I added the muxer as an USB device because it actually has a USB cable.
For now I realize this by matching the actual SCSI-Device and scanning if the parent matches the USB-SD-Mux USB vender and model ID's. To make this work with recent labgrid UBS resource implementation I had to adapt the DEVNUM and BUSNAME lookup a little.
Another …

Add Support for the Pengutronix USB-SD-Mux Hardware

---

doc/development.rst
doc/overview.rst
labgrid/driver/__init__.py
labgrid/driver/common.py
labgrid/driver/powerdriver.py
labgrid/driver/resetdriver.py
labgrid/protocol/__init__.py
labgrid/protocol/resetprotocol.py
labgrid/target.py
tests/test_target.py

Initial starting point for the driver priorities. I wrote three tests and tweaked the `get_driver` function so far, so the tests pass. I have not looked a other parts of the chain yet.
TODO:

implement driver priorities and the ResetProtocol

---

doc/configuration.rst
labgrid/driver/__init__.py
labgrid/driver/powerdriver.py
labgrid/driver/serialdigitaloutput.py

Adding a powerdriver that controls an external relais board connected to
the control signals of a USB-UART-dongle.
This is a poor-mans solution for a power switch that can be used for
desktops with only a single place.

 driver/powerdriver: Add SerialPortPowerdriver 

---

labgrid/driver/power/simplerest.py

Adds a generic powercontroller for NetworkPowerPort  using http get rest calls.
It uses a "Tweak" in NetworkPowerPort declaration where anything can be written in the "host" field.

Add simplerest model for NetworkPowerPort

---

doc/configuration.rst
labgrid/driver/shelldriver.py

This feature can be used for embedded devices that do not - by default -
start a console on the serial terminal.  The 'console_ready'-regex is
used to identify when the kernel is ready to start a console. Afterwards
<enter> is send to the device. The shelldriver now waits for a prompt or login.
Tested with a 4.4-kernel on a LEDE-based device.
If 'console_ready' is not set _await_login() should behave like before.
Depends on #192.

 driver/shelldriver: Add 'enable console' feature

---

labgrid/driver/bareboxdriver.py
labgrid/driver/commandmixin.py
labgrid/driver/exception.py
labgrid/driver/shelldriver.py
labgrid/driver/sshdriver.py
labgrid/driver/ubootdriver.py
tests/conftest.py
tests/test_bareboxdriver.py
tests/test_shelldriver.py
tests/test_sshdriver.py

If you use the run_check function and get an ExecutionError, it will only contain the command that was run, but not the stdout or stderr. Add those and refactor run_check into the mixin.

Make the ExecutionError readable for the run_check case

---

tests/conftest.py
tox.ini

I ran into some Python3.4-3.6 version issues again and updated the tox config.
I also fixed the crossbar fixture to work with tox.

Tox update and a fix for tox in the crossbar fixture

---

doc/configuration.rst
labgrid/driver/bareboxdriver.py

The same functionality is already supported in the UBootDriver.

bareboxdriver: make startup string configurable

---

labgrid/resource/udev.py

These devices show up as "USB HID v1.10 Device [Freescale,Inc. ROM
Recovery]". imx-usb-loader cannot handle (some of?) these devices, but
they work with mxs-usb-loader.

resource: add i.MX28 USB IDs for MXSUSBLoader

---

labgrid/resource/udev.py

The board shows up in imx-usb-loader as "i.MX25", and in lsusb as "Freescale Semiconductor, Inc. SE Blank SENNA".
cc @olerem

resource: IMXUSBLoader: add i.MX25 product ID

---

labgrid/remote/exporter.py

When many udev events happen very quickly (such as when a whole USB bus is reconnected), the intermediate disconnected state may be missed. This patch makes sure to restart ser2net when needed by comparing the current parameters to the ones used to start running ser2net process.

ser2net fix

---

doc/configuration.rst
labgrid/driver/ubootdriver.py

Signed-off-by: Vincent Prince <vincent.prince.fr@gmail.com>

ubootdriver.py: Add login_timeout when board takes long time to boot

---

.pylintrc

> no-member
Pretty useless, because attr is used pretty much everywhere and pylint does not recognize it. Ignore this.
> arguments-differ
Not sure if we should check this, e.g. almost every driver implements a run method with different arguments.
> useless-super-delegation
The [docs](https://labgrid.readthedocs.io/en/latest/development.html#writing-a-driver) state that this is needed:
"The minimum requirement is a call to `super().__attrs_post_init__()`." Why do we override it to call the method on super?
> no-self-use
I think wrapping functionality in methods that could be functions is still a good thing for the sake of logic. Ignore this.
> protected-access
Not sure if we should check this, there are quite some occurrences across labgrid. Maybe this is by design or we need to define …

pylintrc: adjust configuration to labgrid needs

---

labgrid/driver/usbloader.py
labgrid/remote/client.py

Since [recently](https://git.pengutronix.de/cgit/barebox/commit/?id=ca929ac265), imx-usb-loader can also load code into i.MX23/28 (MXS) devices.
Make it possible to override the use of mxs-usb-loader when bootstrapping a device by instantiating a IMXUSBDriver in a YAML file, like this:
``` yaml
targets:
main:
resources:
RemotePlace:
name: my-remote-place
drivers:
IMXUSBDriver: {}
```

Using imx-usb-loader for MXS devices

---

labgrid/resource/udev.py

The board reported by imx-usb-loader as "i.MX6 SoloX".
Signed-off-by: Oleksij Rempel <o.rempel@pengutronix.de>

resource: IMXUSBLoader: add i.MX6SoloX product ID

---

labgrid/driver/networkusbstoragedriver.py

The dd command was moved to its own variable during linting, but
accidentally to a tuple and not a list. This leads to an error while
concatinating with self.storage.command_prefix:
TypeError: can only concatenate list (not "tuple") to list
Fix that.
Fixes: 533cec4c ("linting: do miscellaneous linting")

driver/networkusbstoragedriver: fix concatinating tuple to list

---

labgrid/driver/networkusbstoragedriver.py

The cat command was moved to its own variable during linting, but
accidentally to a tuple and not a list. This leads to an error while
concatinating with self.storage.command_prefix:
TypeError: can only concatenate list (not "tuple") to list
Fix that.
Another occurrence of the same error was fixed by 2544d1d1
("driver/networkusbstoragedriver: fix concatinating tuple to list")
Fixes: 533cec4 ("linting: do miscellaneous linting")

driver/networkusbstoragedriver: fix concatinating tuple to list in get_size()

---

labgrid/driver/quartushpsdriver.py

The Quartus Tools work on JTAG cable numbers only. The numbers are not
stable, see this scenario:
- two devices are connected and detected
- we resolve the usb path (with jtagconfig) to JTAG cable number '2'
- the device with cable number '1' disappears
- the device originally identified by cable number '2' is now cable
number '1'
- we (accidentally) run quartus_hps on non-existent cable number '2'
It is also possible that the wrong device is flashed, this is racy by
design. We cannot solve the raciness, but can mitigate it by not caching
the cable number.

drivers/quartushpsdriver: do not cache cable number

---

doc/usage.rst
labgrid/pytestplugin/fixtures.py
tests/test_fixtures.py

Depending on the exact workflow, it can be convenient to be able to set
an environment variabel once, and just run pytest without '--lg-env'
argument while testing.
Both --lg-env and --env-config overrules $LG_ENV, making this change
backwards compatible.

Allow use of $LG_ENV environment variable instead of --lg-env arg

---

labgrid/driver/power/gude8316.py

This driver adds support for the Gude Expert Power Control 8316,
using the same implementation as gude24.py, except for the port
limit of 8 and a workaround for a bug in version 1.2.0 of the
firmware.
Signed-off-by: Felix Lampe <flampe@arri.de>

driver/power: add support for Gude Expert Power Control 8316

---

labgrid/resource/udev.py
tests/test_environment.py

The USBSerialPort overwrites its own port attribute via udev. Emit a warning and
redirect the user to the udev matching documentation if the port attribute is
set by the user. Also add a test for the warning.
Fixes #268

resource/udev: add warning if port attribute is set on USBSerialPort

---

labgrid/driver/fastbootdriver.py

The fastboot protocol defines a "oem" command, that allows vendor specific
subcommands. barebox supports "exec", which executes arbitrary shell commands.
Add support for this to the fastbootdriver.
Signed-off-by: Steffen Trumtrar <s.trumtrar@pengutronix.de>

driver/fastbootdriver: add run argument

---

labgrid/factory.py
labgrid/remote/exporter.py
labgrid/resource/ethernetport.py
labgrid/resource/udev.py
labgrid/stepreporter.py
labgrid/util/agent.py

Fixes this linting warning:
> no-self-use (R0201):
> Method could be a function. Used when a method doesn’t use its bound instance, and so could be written as a function.

linting: declare methods without self-use static and annotate legitimate methods

---

labgrid/driver/bareboxdriver.py
labgrid/driver/commandmixin.py
labgrid/driver/shelldriver.py
labgrid/driver/smallubootdriver.py
labgrid/driver/sshdriver.py
labgrid/driver/ubootdriver.py
tests/test_bareboxdriver.py
tests/test_shelldriver.py
tests/test_sshdriver.py

Commit 1deea1c71728f50644ffd7b7e709577f43e1d4c2 introduced a bug where the
internal _run_check function used the run function guarded by a check_active
decorator. Use _run for the run_check function, refactor _run functions for
drivers who did not have it and adjust the tests to mock the correct funtion.
Fixes #230

multiple: add _run function, use _run in _run_check for the mixin

---

labgrid/strategy/graphstrategy.py

invalidate() exists to reset the Graph Strategy. Make sure all drivers
are deactivated so they can be activated when starting over.

strategy/graphstrategy: deactivate drivers on invalidate()

---

labgrid/driver/bareboxdriver.py
labgrid/driver/shelldriver.py

_run() methods are not called with step and step is not used anyway, so
remove it.
This fixes errors like:
TypeError: _run() missing 1 required keyword-only argument: 'step'
Issue introduced by PR #237.

multiple: remove step kwarg from _run()/run()

---

labgrid/remote/exporter.py

Identify ports which are exported over ser2net as local ports, ignoring the
modem control lines.
We had a device which uses a full rs232 connection instead of the usual serial
to ttl usb converter. Somewhere in the boot process the device side closed the
port and signaled this via the modem control lines, reulting in an EOF in
ser2net.
Configure the ser2net subprocesses to assume that all serial ports are local
ports, telling the kernel to ignore the control lines.

remote/exporter: set LOCAL option for ser2net exported serial ports

---

labgrid/factory.py
tests/test_factory.py

Caused by copying/pasting the config yaml contains this:
```
targets:
main:
drivers:
- SerialDriver:
- ShellDriver: {}
..
```
This leads to:
`TypeError: 'NoneType' object is not iterable`
To help debugging the config error from above now ends with:
`labgrid.exceptions.InvalidConfigError: invalid list item, add empty dict for no arguments`

factory: recognize invalid config yaml item in _convert_to_named_list()

---

doc/configuration.rst
man/labgrid-device-config.rst

Specifying an image path directly leads to:
KeyError: "no path configured for image '/path/to/bootloader.img'"
Clarify that in the documentation.

doc: IMXUSBDriver/MXSUSBDriver expects images key instead of image path

---

labgrid/pytestplugin/fixtures.py

Before the change, labgrid would always create console logfiles. Change the
option so that logfiles are only produced if --lg-log ist set.

pytest/fixtures: change --lg-log default to const

---

doc/getting_started.rst
labgrid/driver/serialdriver.py
requirements.txt

Add our local pyserial fork in requirements and mention the fork in the installation chapter.

Add Labgrid-project pyserial fork

---

labgrid/driver/serialdriver.py

Our versioned release is 3.4.0.1, so we should only warn if the pyserial version
is lower than this , not equal and lower.
Fixes: 9d26bb2d86 ("serialdriver: add a warning about the RFC2217 fixes")
Reported-by: Jonathan Götzinger <J.Goetzinger@eckelmann.de>

serialdriver: fix version detection for RFC2217

---

doc/configuration.rst
doc/development.rst
doc/usage.rst
labgrid/strategy/bareboxstrategy.py
labgrid/strategy/ubootstrategy.py

This adds the off state which allows to switch the DUT off.

strategy: add off state to BareboxStrategy and UBootStrategy

---

doc/configuration.rst
labgrid/driver/sshdriver.py

TCP timeouts can take a long time to detect a failed connection, so we
enable keep-alives at the SSH level. With the default value of
ServerAliveCountMax of 3, this will detect a failed connection after
about 45 seconds.

driver/sshdriver: configure ServerAliveInterval to detect failed connections

---

labgrid/strategy/graphstrategy.py
tests/test_graphstrategy.py

GraphStrategies have an additional 'via' keyword argument for
transitions. This change allows specifying this by using `labgrid-client
-s shell:off,barebox` which translates to `transition('shell',
via=['off', 'barebox'])`.

graphstrategy: support a compatibility format for transitions with via

---

labgrid/strategy/__init__.py

This will allow to use StrategyError by just importing Strategy
as done in examples/usbpower/examplestrategy which is currently
failing on raise StrategyError
Signed-off-by: Kasper Revsbech <krev@triax.com>

strategy/init: Also import StrategyError from common

---

doc/configuration.rst
labgrid/config.py
labgrid/environment.py

This extends the imports: mechanism in the config.yaml file with support for using Python
modules without having to care about their filesystem paths.
Say you have installed a Python module which includes a labgrid strategy driver as my.labgrid.strategy module, you can add
```yaml
imports:
- my.labgrid.strategy
```
to your config.yaml.
This makes it easier to manage drivers when managed as an infrastructure part, and not directly in the test repositories.

Allow import of python modules using imports: in config.yaml

---

labgrid/remote/common.py
labgrid/resource/power.py
labgrid/resource/remote.py
labgrid/resource/ykushpowerport.py

The `convert()` method was deprecated with attrs 17.4.0.
See http://www.attrs.org/en/stable/changelog.html#id44

Fix use of deprecated attrs convert() method

---

labgrid/driver/serialdriver.py

Fix a bug in the serialdriver. It says python instead of pyserial.
Fix for a copy-and-paste error I did with the pyserial version warning.

serialdriver: fix warning string

---

labgrid/remote/client.py
man/labgrid-client.1
man/labgrid-client.rst

When using the pytestplugin, $LG_ENV can be used for specifying the
configuration file.  Adding support for same behavior when using
labgrid-client allows setting up $LG_ENV and then using simple CLI commands
without having to bother with --lg-env and --config options.

remote/client: Allow use of $LG_ENV to specify config file

---

doc/configuration.rst
labgrid/driver/sshdriver.py

This adds a stderr_merge flag to SSHDriver, which when se makes SSHDriver
instances return values from run() compatible with what is returned by
ShellDriver, ie. with stdout and stderr merged together in first value,
and [] in second.
With this, it is much easier to write test cases that can be used with
both SSHDriver and ShellDriver.
Example fixture for use:
@pytest.fixture(scope='function')
def shell(target):
ssh = target.get_driver('SSHDriver')
if ssh:
target.activate(ssh)
stderr_merge = ssh.stderr_merge
ssh.stderr_merge = True
yield ssh
ssh.stderr_merge = stderr_merge
else:
return target.get_active_driver('CommandProtocol')

driver/sshdriver: Add option to merge stderr with stdout

---

labgrid/driver/shelldriver.py

When waiting for the initial login prompt, the `before` value is `b''`
on timeout, so with `last_before = None` the timeout had to fire two times
before the `self.console.sendline("")` was executed.

driver/shelldriver: Fix initial login prompt timeout

---

.travis.yml
docker/README.rst
docker/build.sh
docker/client/Dockerfile
docker/coordinator/Dockerfile
docker/exporter/Dockerfile
docker/exporter/entrypoint.sh

This add Dockerfile for building Docker images including the Labgrid distributed infrastructure components, and integrates build testing of them in Travis CI.
Replaces #284
Closes #260

Build Docker images

---

labgrid/driver/sshdriver.py

For tests where both ShellDriver and SSHDriver are activated, the SSHDriver
should be preferred, as it much faster.  Without this, calling
`target.get_driver('CommandProtocol')` with both drivers active will fail.
For other use cases (ie. where only one CommandProtocol driver is active at a
time), things will work as before.

driver/sshdriver: Make SSHDriver a preferred CommandProtocol

---

labgrid/driver/serialdriver.py

This got refactored and is also not necessary here, since we rely on the proxy
setting of the exporter.

driver/serialdriver: remove wrong keyword argument

---

labgrid/resource/udev.py

Fixes: 88ab4edb ("resource/udev: fix DeprecationWarnings")

resource/udev: properties is not a method in filter_match()

---

labgrid/remote/exporter.py

Classes which are not a subclass of the ResourceExport don't have these keyword
arguments, remove them.
This causes an error for newly restarted exporters.

exporter: fix proxy arguments for non Exported classes

---

labgrid/util/proxy.py

The keyword argument is actually called "force_proxy", not "proxy".

util/proxy: fix docstring for proxy kwarg

---

doc/configuration.rst

While at it replace the "double quoted command" around it with a ``inline code snippet``.

doc: fix typo (s/udevadmin/udevadm/)

---

labgrid/remote/exporter.py

This works the same way as ResourceExport.stop() does.
It fixes:
`TypeError: _stop() missing 1 required positional argument: 'start_params'`

remote/exporter: fix _stop() call in USBSerialPortExport

---

labgrid/strategy/ubootstrategy.py

Barebox does not exist in ubootstrategy.
Signed-off-by: Laurentiu Palcu <laurentiu.palcu@nxp.com>

strategy/ubootstrategy: fix OFF transition

---

labgrid/util/ssh.py

In case an image file is given as a symlink pointing to the actual image
the rsync command skips the file:
skipping non-regular file "myimage.img"
Fix this by actually copying the symlink referent to the remote.
This is important for Yocto builds. The resulting images contain a
timestamp in the file name. For each image a symlink with a predictable
name is created. So using this symlink is the easiest way of
referencing a Yocto image in an automated build and test chain.
See: https://www.yoctoproject.org/docs/1.8/ref-manual/ref-manual.html#images-dev-environment
Note: this was originally part of #336.

util/ssh: copy also symlink referents to remote

---

labgrid/driver/shelldriver.py

This ends up being the normal situation, so let's please demote it to debug level.

Avoid "Key already on target" spamming

---

labgrid/resource/udev.py

USBSDMuxDevice's path property has no setter method. So use disk_path
directly on update().
Fixes: 9ef77464 ("resource/udev: use update function for USBSDMuxDevice")

resource/udev: access USBSDMuxDevice's disk_path directly

---

labgrid/util/ssh.py

Fix error and warnings introduced by #351.

util/ssh: TimeoutExpired stems from subprocess, fix linting errors

---

labgrid/resource/udev.py

The function would try to iterate on the NoneType object of no device was
available. Add the else path to only iterate on the device children if the
device is available
Fixes: 9ef7746 ("resource/udev: use update function for USBSDMuxDevice")

resource/udev: fix missing else in USBSDMuxDevice update function

---

labgrid/driver/serialdriver.py

When using non compliant servers we may get a "ValueError: remote
rejected value for option 'control'" exception.
However, since Labgrid is not using HW flow control at all, we can
safely ignore the SET_CONTROL responses.
According to pyserial documentation, this can be achieved by adding the
'ign_set_control' option in the rfc2217 URL.
Signed-off-by: Laurentiu Palcu <laurentiu.palcu@nxp.com>

serialdriver: ignore SET_CONTROL answers when using rfc2217

---

debian/control

Building on stretch (minimal container - using dck-buildpackage) threw out lots of strange errors,
Problems were:
* python3-venv was missing 
* some deps need to C-compile, therefore python headers are needed
* python-setuptools need to be installed, otherwise some commands fail w/o any easily visible explaination (can we increase the debug level / verbosity here ?)
* some of the automatically pulled python modules lack (autogenerated) metadata, so git is needed to create them

debian: fixed dependencies for stretch

---

labgrid/remote/client.py

labgrid does not limit the number of places that can match a given resource. This very flexible perception of places results in places being created but not used (anymore). Also resources might get matchen by different places. At the end you might have server racks full of embedded boards blocking space and resources without being used (anymore). So I came up with two options:
`labgrid-client places --sort-last-changed` lists all places by their last changed date. Combined with `-v` the actual changed date is shown per place.
`labgrid-client resources --sort-by-matched-place-change` lists all resources by "their" last changed date and shows places matching the respective resource and their last changed date.
The first one should come quite self-explanatory. It can be used to delete places …

remote/client: add --sort-last-changed for places/resources subcommands

---

CHANGES.rst
labgrid/remote/client.py

IP, username and password might be already available in NetworkService, currently used for SSHDriver. Try to use these also for labgrid-client's ssh subcommand.

remote/client: try to use IP/username/password for ssh subcommand from NetworkService

---

setup.py

Raise the minimal pytest version to 3.6.0 which introduced get_closest_marker.
**Checklist**

Raise minimum pytest version to 3.6 (which introduced get_closest_marker)

---

labgrid/pytestplugin/hooks.py

This fixes
AttributeError: 'NoneType' object has no attribute 'config'
in case --lg-coordinator is given but --lg-env (or LG_ENV) is missing.
**Checklist**

pytestplugin/hooks: only set coordinator if env exists

---

doc/development.rst
labgrid/util/managedfile.py
labgrid/util/ssh.py
tests/test_util.py

This PR aims at improving user experience with ManagedFile:
* use `rsync --compress=1 --sparse` to speed up sparse file upload
* heuristic for determining file is on NFS and foregoing the preceding transfer if it is
**What I intend to use this feature for:**
Save time when using labgrid-client.
**How does labgrid benefit as a testing library from the feature?**
The added `run`/`run_check` command can be used in tests where running commands on the exporter system is required. 
**How did you verify the feature works?**
I included some tests.
**Checklist**

Conserve bandwidth when using ManagedFile

---

labgrid/remote/client.py

Fix the fastboot client command to use the driver functions which use the ManagedFile.
**Checklist**

remote/client: let fastboot use driver functions

---

docker/README.rst

Indenting code-blocks will give quoted code blocks which is not what's
intended here.
Also change inline commands to be handled as ``inline literal`` instead of
`interpreted text`.

docker: README.rst: some markup fixes

---

labgrid/driver/commandmixin.py
labgrid/protocol/commandprotocol.py

Signed-off-by: Vincent Prince <vincent.prince.fr@gmail.com>

driver/commandmixin: Add poll_until_success helper function

---

CHANGES.rst
labgrid/driver/networkusbstoragedriver.py
labgrid/remote/client.py
labgrid/resource/udev.py
man/labgrid-client.1
man/labgrid-client.rst

Add the write-image command to the client. This allows the writing of images to USB mass storage devices.
Also fix the disk_path property of the usbsdmux.
The `NetworkUSBStorageDriver` has been enhanced with a check for the `path` property of the resource, since the USBSDMux can be available, but in `DUT` mode does not expose a usb storage device.

Add write-image subcommand to the client, fix udev detection and check device path

---

docker/client/Dockerfile
docker/coordinator/Dockerfile
docker/exporter/Dockerfile
tox.ini

Signed-off-by: Anders Gammelgaard <anga@triax.com>
Python 3.7 has new asyncio-based features. To use these together with labgrid from within a docker container, it helps to base the container on Python 3.7. This is easy to accomplish if labgrid can use Python 3.7 directly. This seems to be the case already for the tip of master and only needs to be stated explicitly. Besides, the 3.7 version should be used in relevant places - in particular docker. There may be more places, however, than I am aware of.
**Checklist**
Added new tox.ini environment py37 and ``tox -r`` seems to run flawlessly.
Summary for CHANGES.rst file:
- docker images for client, exporter and coordinator will now use Python3.7.

Allow use of Python3.7 features

---

docker/README.rst
docker/coordinator/Dockerfile

The default port for coordinator, defined in crossbar configuration
file, is 20408.
Signed-off-by: Andreas Schmidt <mail@schmidt-andreas.de>

docker: coordinator: fix port number

---

labgrid/resource/udev.py

Following warnings appears when using labgrid with new pyudev:
/usr/lib/python3.7/site-packages/labgrid-0.2.1.dev35+g6c8ab66.d20190215-py3.7.egg/labgrid/resource/udev.py:178: DeprecationWarning: Will be removed in 1.0. Access properties with Device.properties.
if self.device:
-- Docs: https://docs.pytest.org/en/latest/warnings.html
Check explicitly for None value, so we can get rid of them.

udev: suppress udev warnings by explicitly comparing with None

---

CHANGES.rst
labgrid/remote/client.py

Since PR #342 NetworkService's IP/username/password are considered for
'labgrid-client ssh'. This also adds the SSH port.
Thanks to @maximilianriemensberger for [pointing this out](https://github.com/labgrid-project/labgrid/pull/342#pullrequestreview-191191011).
**Checklist**

remote/client: use port from NetworkService for ssh call

---

.travis.yml
CHANGES.rst
contrib/systemd/tmpfiles.d/labgrid.conf
doc/getting_started.rst
labgrid/util/managedfile.py
tests/test_util.py

Move the cache directory for managedfile uploads to `/var/cache/labgrid` and also provide a configuration example in contrib.
**Checklist**

managedfile: change upload directory to /var/cache/labgrid

---

contrib/systemd/tmpfiles.d/labgrid.conf

Merge the two lines in the configuration into one.
The tmpfiles configuration had two lines which could be merged, merge those.

contrib: tmpfiles: fix tmpfiles directives

---

.travis.yml

Fixes the docker build. It still shows a python version, probably from the main configuration.

travis: remove python directive for docker

---

labgrid/driver/sshdriver.py
labgrid/util/ssh.py

Python3.8 reports a SyntaxWarning for "is not" usage with literals.
Replace the "is not" with "!=".
**Checklist**

treewide: fix is not with literal

---

setup.py

PR #397 introduced new Python module `labgrid.util.agents`. The module wasn't entered into `setup.py`, however.
When I use `tox -r` to test tip of master (currently commit 897b3a5), two tests in `tests/test_agent.py` fail. But with the proposed change all tests pass.
I have no idea why Travis didn't catch this error.

setup.py: add labgrid.util.agents

---

tests/conftest.py

The pytest setup function still uses the deprecated get_marker function.
Replace it with the new get_closest_marker function.

tests: get_closest_marker for localsshmanager

---

CHANGES.rst
crossbar-requirements.txt
labgrid/remote/client.py
labgrid/remote/exporter.py
requirements.txt

Update Crossbar and autobahn to the latest released versions. We are currently seeing a bug in out setup which results in the following log output:
```
Apr 01 09:23:16 labgrid crossbar[27698]: [Router      27705] INTERNAL WARNING: event for publication 1671249291329997 not in event store
Apr 01 09:23:16 labgrid crossbar[27698]: [Router      27705] INTERNAL WARNING: subscription 3503552087680833 for publication 1671249291329997 not in event store
```
A similar bugreport upstream (crossbario/crossbar#1459) has been closed as not reproducible on an updated version, so this bump should fix the bug.
**Checklist**
Fixes #406

Update crossbar and fix authid

---

labgrid/driver/usbvideodriver.py

The default device of v4l2src is /dev/video0. If the device is not specified and more than
one camera is connected, the default camera video0 will always be used.
The fix uses the devices video path to get the correct video device.
Tested with 2 cameras:
Without the fix:
labgrid-client -p board-1 video -> returns the stream of board-1
labgrid-client -p board-2 video -> returns the stream of board-1
With the fix:
labgrid-client -p board-1 video -> returns the stream of board-1
labgrid-client -p board-2 video -> returns the stream of board-2
**Checklist**

driver/usbvideodriver: fix: select correct camera for stream

---

doc/configuration.rst
labgrid/driver/fastbootdriver.py

Always set fastboot's '-S' option with given value. fastboot ignores the
option for non-image commands and in case the image size is smaller than
the given sparse size. Default is to disable sparse support altogether
(as before).
**Checklist**

driver: fastbootdriver: allow setting sparse option

---

doc/configuration.rst
labgrid/driver/ubootdriver.py

In UBootDriver, make the hardwired string "stop autoboot" that is supposed to match the message about stopping U-Boot's autoboot configurable as a new attribute "autoboot".
Use the old value as a default.
This is implemented in the same way by the BareboxDriver.
**Checklist**
Fixes #402.

Make UBootDriver's autoboot string configurable

---

labgrid/remote/client.py
man/labgrid-client.1
man/labgrid-client.rst

Previously both STATE and PLACE were not namespaced with the LG prefix.
Add support for both and prefer them over the old variables.
The old variables are still supported.

remote/client: support env variables in namespace

---

doc/configuration.rst
labgrid/driver/fastbootdriver.py

By default, the sparse threshold is computed by querying the
target's `max-download-size` variable.
With #416, labgrid adopted the behavior of passing `-S 0` as
default value to fastboot. This is problematic as different
fastboot versions interpret `-S 0` differently:
- Fastboot releases containing [542370dead ("Move fastboot over
to ParseByteCount."](https://github.com/aosp-mirror/platform_system_core/commit/542370dead58e854c477549bf0b3333aaf23b299)) treat `-S 0` and its absence the same:
The target's `max-download-size` variable is queried.
- Older fastboot releases, e.g. 1:7.0.0+r33-1 shipped by Debian
Stretch, instead completely disables sparse when `-S 0`, while not
supplying it queries the target.
To have the fastbootdriver interoperate with both versions,
supply …

driver: fastbootdriver: don't disable sparsing by default

---

labgrid/driver/sshdriver.py

-n to put the ssh program to background doesn't work with password.
Use -f instead.

sshdriver: use -f if ssh is used with password

---

labgrid/remote/client.py

Currently, the fastboot command on the exporter will try to parse parameters from the command which we want to run on the target:
```
$ labgrid-client fastboot oem exec state -s
fastboot: option requires an argument -- 's'
[.. traceback ..]
subprocess.CalledProcessError: Command '['ssh', '-x', '-o', 'ConnectTimeout=5', '-o', 'PasswordAuthentication=no', 'labgrid-exporter-hostname', '--', 'fastboot', '-i', '0x1337', '-s', 'usb:2-2.3.2', 'oem', 'exec', 'state', '-s']' returned non-zero exit status 1.
```
AndroidFastbootDriver.run() already adds a '--' after the `fastboot oem exec` part, so use that method for `labgrid-client fastboot` to fix this behaviour.

labgrid-client: fastboot: use AndroidFastbootDriver.run() for 'oem exec'

---

CHANGES.rst
labgrid/driver/shelldriver.py
labgrid/driver/sshdriver.py

The keyfile path is given relative to the current working directory,
whereas the images are given relative to the config.
Handle the keyfile path just like the image paths to gain consistency.
**Checklist**

SSHDriver/ShellDriver: make keyfile paths consistent with image paths

---

CHANGES.rst
doc/usage.rst
labgrid/driver/modbusdriver.py
labgrid/driver/onewiredriver.py
labgrid/driver/power/apc.py
labgrid/driver/power/digipower.py
labgrid/driver/power/gude.py
labgrid/driver/power/gude24.py
labgrid/driver/power/gude8316.py
labgrid/driver/power/netio.py
labgrid/driver/power/netio_kshell.py
labgrid/driver/power/simplerest.py
labgrid/driver/powerdriver.py
labgrid/remote/client.py
labgrid/resource/common.py
labgrid/util/proxy.py
labgrid/util/ssh.py
man/labgrid-client.1
man/labgrid-client.rst
tests/test_onewire.py

This PR implements support for using a SSH proxy host for connections to the coordinator and network resources. Note that so far only SerialDriver, NetworkPowerDriver (most backends), ModbusCoilDriver and OneWirePIODriver have been modified to use the ProxyManager.
This should also solve the use-case described in #186.
**Checklist**

Extended SSH Proxy Support

---

examples/deditec-relais8/deditec.py
examples/deditec-relais8/deditec_remote.py
examples/deditec-relais8/export-didicontrol.yaml
examples/deditec-relais8/import-dedicontrol.yaml
labgrid/driver/deditecrelaisdriver.py
labgrid/remote/client.py
labgrid/remote/exporter.py
labgrid/resource/remote.py
labgrid/resource/udev.py
labgrid/util/agent.py
labgrid/util/agents/deditec_relais8.py
labgrid/util/agentwrapper.py
requirements.txt
tests/test_agent.py

This PR first adds an agent module to control the device remotely. Then it adds a resource and driver to allow local and remote control via the agent. An example for both variants is also included
**Checklist**

Add agent module, resource and driver for Dedidec Relais 8 device

---

README.rst

We've migrated to .com from .org, so update the badge URL.

README: update travis-ci badge

---

labgrid/resource/udev.py

The i.MX8MQ in serial download mode identifies as:
```
Bus 001 Device 057: ID 1fc9:012b NXP Semiconductors i.MX 8M Dual/8M QuadLite/8M Quad Serial Downloader
```
add the VID and PID to the IMXUSBLoader resource.

resource/udev: add VID and PID for i.MX8MQ

---

doc/configuration.rst
labgrid/driver/openocddriver.py

Until now the USB Blaster device had to be configured via OpenOCD
configs. Since OpenOCD's a1b308ab ("jtag: drivers: provide initial
support for usb path filtering") it is now possible to identify the
device via USB path.
Set the USB path via "adapter usb location" via OpenOCD's --command
argument to the path of the AlteraUSBBlaster resource.
**Checklist**

driver: openocddriver: use AlteraUSBBlaster's USB path

---

labgrid/remote/client.py
labgrid/remote/common.py

Currently, a `labgrid-client console` connection is left open even if the place is released (either normally or with `--kick`). With this change, we monitor the place's state and terminate microcom when we detect that the place is no longer acquired.
**Checklist**
Fixes #449

close labgrid-client console connection on place release

---

labgrid/resource/udev.py

Use the labgrid internal Timeout class instead of open coding the
timeout implementation.
Small correction I just realized talking to @jluebbe.

resource/udev: use timeout helper

---

.crossbar/config.yaml

We currently don't make use of the event store, removed it since we see
errors in the coordinator log otherwise.

crossbar: remove event store enabled by default

---

labgrid/remote/client.py
tests/test_crossbar.py

The del_place function used the pure argument instead of going through
the idle place helper, allowing the user to delete acquired places. Use
the idle place helper to ensure that only idle places are deleted

remote/client: use idle place helper for delete

---

labgrid/pytestplugin/hooks.py
requirements.txt

Update pytest to 4.6.3, so the subtests plugin can be used. We've tested this internally for two weeks.

update pytest to 4.6.3

---

CHANGES.rst
labgrid/driver/fastbootdriver.py

These commands allow reading variables. The value is returned in a
pretty obfuscated way, so clean up is performed and only the value of
the (environment) variable is then returned.
Note: there is no way to distinguish non-existent variables and
variables with an empty value. This is a fastboot limitation.
**Checklist**

driver: fastbootdriver: implement 'getvar' and 'oem getenv' commands

---

doc/configuration.rst
labgrid/driver/bareboxdriver.py

Since 016f605c ("bareboxdriver: refactor login expect loop and add password support")
startstring is not used anymore.
**Checklist**

driver: bareboxdriver: remove unused startstring attribute

---

labgrid/resource/common.py

With the new labgrid-client -P option using:
labgrid-client -P labgrid01 -p board-1 video
labgrid-client -P labgrid01 -p board-1 bootstrap
labgrid-client -P labgrid01 -p board-1 fastboot
results in a timeout or ssh connect error.
When the the self.video.command_prefix is evaluated, labgrid tries to
create a second connection to the exporter with the hostname from 
self.extra.proxy instead of the one specified with the -P option. Since
self.extra.proxy is a default variable, it should only be evaluated when
"proxy_required" is True.
Signed-off-by: Jonathan Goetzinger <j.goetzinger@eckelmann.de>
**Checklist**

resource: common.py only use proxy when 'proxy_required' is true

---

labgrid/driver/onewiredriver.py
tests/test_onewire.py

Previously, the OneWireDriver only read back the configure output value instead of the real physical line value.
**Checklist**

fix onewire PIO input

---

labgrid/pytestplugin/hooks.py

Instead of accessing the private member of the capturemanager, use the
supported public function.

pytestplugin/hooks: fix capture check

---

labgrid/pytestplugin/hooks.py

Otherwise pytest will complain about the unregistered marker.

pytestplugin/hooks: register lg_feature marker

---

labgrid/pytestplugin/fixtures.py

The global pytest.config has been deprecated, use the suggested
request.config instead.
Fixes #466

pytestplugin/fixtures: use request.config

---

labgrid/strategy/graphstrategy.py
tests/test_graphstrategy.py

This prevents debugging sessions where a string is passed accidentally
to via and handled like a list.
**Checklist**

graphstrategy: raise if via is not list or None

---

labgrid/driver/onewiredriver.py

Add step decorators to the get and set methods of the onewiredriver.
This logs the appropriate steps in the console output.

driver/onewiredriver: add steps to get and set

---

labgrid/driver/ubootdriver.py

Other than what's stated in the commit, I've tested this on a local development board which uses NOR flash, so erasing it is slow, and it timed out every time before making the change.
**Checklist**

ubootdriver: use the given timeout for run()

---

CHANGES.rst
doc/configuration.rst
examples/sysfsgpio/export-gpio.yaml
examples/sysfsgpio/import-gpio.yaml
examples/sysfsgpio/sysfsgpio.py
examples/sysfsgpio/sysfsgpio_remote.py
labgrid/driver/__init__.py
labgrid/driver/gpiodriver.py
labgrid/remote/client.py
labgrid/remote/exporter.py
labgrid/resource/base.py
labgrid/resource/remote.py
labgrid/util/agents/sysfsgpio.py
tests/test_agent.py
tests/test_sysfsgpioagent.py

This is only complementary work for https://github.com/labgrid-project/labgrid/pull/407
**Checklist**
Complements https://github.com/labgrid-project/labgrid/pull/407

Implement GPIO support via sysfs with agent interface

---

labgrid/driver/ubootdriver.py
tests/test_ubootdriver.py

PR #476 passed the timeout argument by position, which causes an error as it's a keyword only argument.
**Checklist**

Fix uboot timeout

---

CHANGES.rst
doc/configuration.rst
labgrid/driver/__init__.py
labgrid/driver/filedigitaloutput.py
tests/test_filedigitaloutput.py

This PR adds a FileDigitalOutputDriver. It writes arbitrary string representations of booleans to a file and reads string representations from it.
I tested it with a led available in sysfs.
**Checklist**

Add a FileDigitalOutputDriver

---

tests/test_onewire.py
tests/test_serialdriver.py

With pytest-cov, the monkeypatch fixture is not needed and mocker.patch()
should be used instead. Refactor the tests accordingly.

tests: refactor to remove monkeypatch usage

---

CHANGES.rst
labgrid/remote/client.py
labgrid/remote/common.py
labgrid/remote/coordinator.py
labgrid/remote/exporter.py
tests/test_crossbar.py

Currently, the coordinator doesn't track which resources are used by which places. Accordingly, it can't detect if two places configured for the same resource are acquired at the same time.
To solve this, we need to refactor the coordinator to track the acquired state of resources and let it detect conflicts.
Additionally, as the exporter now knows which resources are acquired, we can start any helper processes only when needed.
**Checklist**

Acquire resources on exporter

---

labgrid/driver/fastbootdriver.py
labgrid/driver/flashromdriver.py
labgrid/driver/networkusbstoragedriver.py
labgrid/driver/openocddriver.py
labgrid/driver/power/apc.py
labgrid/driver/powerdriver.py
labgrid/driver/quartushpsdriver.py
labgrid/driver/usbloader.py
labgrid/driver/usbsdmuxdriver.py
labgrid/pytestplugin/hooks.py
labgrid/remote/client.py
labgrid/util/helper.py
tests/test_powerdriver.py

This PR adds a subprocess wrapper which acts like `subprocess.check_output`, but takes callbacks to send the output of the command to.
`processmanager.register` adds a callback, `processmanager.unregister` removes the callback. Callbacks receive the process output line based.
**Checklist**
**TODO List**

Subprocess Wrapper

---

doc/development.rst
doc/getting_started.rst
doc/overview.rst
doc/usage.rst
labgrid/remote/client.py
labgrid/remote/common.py
labgrid/remote/coordinator.py
labgrid/remote/scheduler.py
man/labgrid-client.1
man/labgrid-client.rst
tests/test_crossbar.py
tests/test_sched.py

When using labgrid with Jenkins, it can happen that a place is already used by someone/something else. In that case, it would be useful to let the test job wait until a compatible place is available.
This PR implements an initial version of place reservation using tags and filters, and a scheduler which allocates places. Documentation is still missing and more tests are needed.
This builds on PR #481.
**Checklist**

place reservation

---

labgrid/driver/shelldriver.py

Instead of hard coding a 5 sec timeout, we can use whatever is left of the global timeout for getting shell, when waiting for the shell after inputting password.
This solves issues when the shell is delayed after inputting a password, which can happen with slow devices or slow authentication systems. The cause for this was discovered by Christoforos Markou (chma@hms.se)

shelldriver: use remaining timeout after password

---

labgrid/remote/common.py

UTF-8 is nice, but we shouldn't rely on the user having a UTF-8 locale.
$ grep -R --color='auto' -P -n "[^\x00-\x7F]" labgrid/*
was used to search for all None UTF-8 characters, the only other matches
are in a docstring.
Fixes https://github.com/labgrid-project/labgrid/issues/486

remote/common: replace → to support C locale

---

labgrid/util/proxy.py

This caused problems when using evaluating labgrid output in the shell.
Fixes #500

util/proxy: remove leftover debug print

---

labgrid/remote/client.py

This fixes a grammatical error I noticed while using labgrid. Not tested in any way :-)

remote/client: Add a verb to an printed message

---

labgrid/util/agent.py

This avoids stopping the agent when using it from an interactive python
session and pressing Ctrl-C.

util/agent: ignore SIGINT

---

CHANGES.rst
labgrid/target.py

We already allow class name strings in get_driver and similar, so we
should also allow it in the binding dict for consistency. In the longer
term, this should help to reduce the amount of required imports just for
binding to the correct types.
**Checklist**

target: allow driver bindings by class name

---

labgrid/driver/deditecrelaisdriver.py
labgrid/resource/remote.py
labgrid/resource/udev.py

This add support for the invert attribute on deditec relais8 resources, similar to modbus and onewire.
**Checklist**

deditecrelaisdriver: add support for inverted signals

---

setup.py

This was lost in commit 7021d8db4308f6a75283ba6a2b267b50f700496f, and
significantly increased the startup time. Get some performance back by reenabling fastentrypoints.
Also add the linter hints to avoid losing it again.

setup: reenable fastentrypoints

---

doc/configuration.rst
doc/development.rst
labgrid/driver/powerdriver.py
labgrid/resource/power.py

This addresses the long-standing request to add support for PDUDaemon
ports via the PowerProtocol.
**Checklist**

driver/power: add PDUDaemon support

---

labgrid/driver/qemudriver.py
labgrid/resource/suggest.py
labgrid/resource/udev.py
setup.py

This helps with finding the correct match attributes for USB devices.
The output looks like this:
```
=== existing device ===
USBSerialPort for /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.2/1-3.2:1.0/ttyUSB1/tty/ttyUSB1
=== device properies ===
device node: /dev/ttyUSB1
udev tags: seat, systemd, uaccess
vendor: FTDI
vendor (DB): Future Technology Devices International, Ltd
model: USB_Serial_Converter
model (DB): FT232 Serial (UART) IC
revision: 0600
=== suggested matches ===
USBSerialPort:
match:
'@ID_PATH': pci-0000:00:14.0-usb-0:3.2
---
USBSerialPort:
match:
'@ID_SERIAL_SHORT': FT8WJPE3
---
=== added device ===
USBSDMuxDevice for /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.4/1-3.4.1
=== device properies ===
device node: /dev/bus/usb/001/047
vendor: Pengutronix
vendor …
```

add udev match suggestion utility

---

doc/configuration.rst
labgrid/driver/sigrokdriver.py
labgrid/remote/exporter.py
labgrid/resource/remote.py
labgrid/resource/sigrok.py
labgrid/resource/udev.py
tests/test_sigrok.py

This splits the capture support from common code in driver/sigrokdriver and then adds a new SigrokPowerDriver implementing PowerProtocol and get/set methods for voltage and current.
**Checklist**

add support for USB power supplies via sigrok

---

labgrid/driver/networkusbstoragedriver.py

- fix string formatting in get_size()
- use sysfs polling to wait for medium
This is a workaround. The resource should only be "available" once the medium is there.
**Checklist**

driver: networkusbstorage: fix get_size(), wait for medium

---

labgrid/driver/shelldriver.py

Use only a single expect call. This allows using a combined timeout for the marker and the prompt.
Due to heavy load on the target echoing the marker and displaying the prompt might take a while. This is no error, so increase the timeout (3 seconds -> 5 seconds).
**Checklist**

driver: shelldriver: combine marker/prompt expects and increase timeout in _check_prompt()

---

labgrid/remote/client.py

When 'microcom' is not installed on the host running labgrid exporter,
client calling 'labgrid-client console' will receive FileNotFoundError.
This patch adds graceful exit in this situation.
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>

client: exit gracefully when microcom is missing

---

labgrid/resource/remote.py

Without this optional the exporter might return None for the
control_path if no device is connected, which results in the following
error message when the client wants to create the target:
```
File "/home/phoenix/work/ptx/labgrid/labgrid/factory.py", line 111, in make_resource
r = cls(target, name, **args)
File "<attrs generated init labgrid.resource.remote.NetworkUSBSDMuxDevice>", line 24, in __init__
__attr_validator_control_path(self, __attr_control_path, self.control_path)
File "/home/phoenix/.virtualenvs/labgrid/lib/python3.7/site-packages/attr/validators.py", line 45, in __call__
value,
TypeError: ("'control_path' must be <class 'str'> (got None that is a <class 'NoneType'>).", Attribute(name='control_path', default=None, …
```

remote: missing optional for NetworkUSBSDMuxDevice

---

.travis.yml

We should test against all supported Python versions by default. We can also update the base image to Ubuntu bionic.
**Checklist**

travis: switch to bionic and test python 3.7 and 3.8 by default

---

labgrid/strategy/graphstrategy.py

`root_states` already contains all states without dependencies as strings. Joining only the first element of each string results in the first character of each state being printed. Fix this by joining `root_states` directly without a list comprehension.
**Checklist**

graphstrategy: fix error message about multiple root states

---

docker/base/Dockerfile
docker/build.sh
docker/client/Dockerfile
docker/coordinator/Dockerfile
docker/exporter/Dockerfile
docker/exporter/entrypoint.sh

* Base image switched to debian:buster-slim to reduce the size of the
images (python:3 base images is fat). Each image is now ~500M instead of
~1G.
* Introduce a labgrid-base image since the build-dependencies are common
to all images.
* Use buildkit backend to slightly speed up the docker build time.
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>

docker: refactor Dockerfiles to reduce their size

---

.travis.yml

With the newly introduced base image (see #525), it looks like we can't use the docker hub builder anymore. Push the finished images from travis-ci instead.
**Checklist**

travis: push docker images

---

doc/development.rst

Fixup: Add python3-dev to dependencies for development-environment

doc: Add python-dev to required development dependency

---

labgrid/pytestplugin/fixtures.py
labgrid/resource/common.py
labgrid/target.py
tests/test_sigrok.py

Implement `poll` for all resources.
This should fix the bug in #530 and now poll all resources either directly or using their respective manager. Needs more testing before being merged.
**Checklist**
Fixes #530

Implement poll for all resources

---

labgrid/remote/client.py

Add PDUDaemon driver support to the client.
Tested with [PDUDaemon in revision 941f14c](https://github.com/pdudaemon/pdudaemon/commit/941f14cdb0a5a36777c1bfc6fed87cd9c1ca8362). Older versions of PDUDaemon will still work, but since the HTTP listener falsely always responds with an error (see commit message in above link), the Labgrid client will raise an exception as well.

remote/client: add PDUDaemon driver support

---

crossbar-requirements.txt
dev-requirements.txt
labgrid/remote/client.py
labgrid/remote/coordinator.py
labgrid/remote/exporter.py
requirements.txt
tests/conftest.py
tests/test_crossbar.py

This fixes a locking issue in the coordinator, which was triggered when exporters stopped responding without closing their TCP connection to crossbar.
It also adds some more robustness fixes to the client and improves testing in these areas.
**Checklist**

coordinator and client robustness fixes

---

doc/getting_started.rst
doc/overview.rst

Adds some links from the "Getting Started" chapter to the "Overview" chapter to ease finding informtaion about the general concept of things in labgrid.
**Checklist**

doc: Link 'Overview' Chapters From 'Getting Started' Chapter

---

labgrid/driver/powerdriver.py

The pykush module needs an import like this:
from pykush import pykush
Fix the YKUSH driver to reflect this change.
Signed-off-by: Matthias Brugger <matthias.bgg@kernel.org>
**Checklist**

driver/power: Fix YKUSH power driver

---

labgrid/pytestplugin/reporter.py

Due to an increasing number of drivers implementing protocols the method names logged in the step reporter become more and more ambiguous. Therefore prepend the event source (the name of the driver) to the report.
**Checklist**

pytestplugin: reporter: report event source

---

labgrid/driver/qemudriver.py
labgrid/util/qmp.py

Raise meaningful exceptions in case of invalid QMP messages and check if the QEMU process is still alive when this happens.
**Checklist**

qmp/QEMUDriver: improve error handling

---

labgrid/step.py

It is possible to call the step function not via the `@step` decorator but directly. In case `getattr()` is used to retrieve an object's method it will be a bound method object (instead of a function object when used via the decorator). The signature of a bound method does not contain self as a parameter, so the event source will always be None.
Currently only the _GraphStrategy_ calls the step function directly. Fix the event source in these cases by using `func.__self__` for bound methods.
Note: This allows #555 to print steps for GraphStrategy states with the correct event source (the class name of the individual strategy).
**Checklist**

step: set event source for bound methods

---

labgrid/remote/exporter.py
tests/conftest.py
tests/test_crossbar.py

When the exporter is unable to start or stop subprocesses for resources, it's better to handle that explicitly rather than wait for errors when using them.
**Checklist**

exporter broken tracking

---

labgrid/driver/deditecrelaisdriver.py
labgrid/driver/dockerdriver.py
labgrid/driver/fastbootdriver.py
labgrid/driver/flashromdriver.py
labgrid/driver/gpiodriver.py
labgrid/driver/modbusdriver.py
labgrid/driver/networkusbstoragedriver.py
labgrid/driver/onewiredriver.py
labgrid/driver/openocddriver.py
labgrid/driver/powerdriver.py
labgrid/driver/quartushpsdriver.py
labgrid/driver/serialdriver.py
labgrid/driver/sshdriver.py
labgrid/driver/usbloader.py
labgrid/driver/usbsdmuxdriver.py
labgrid/driver/usbstorage.py
labgrid/driver/usbtmcdriver.py
labgrid/driver/usbvideodriver.py
labgrid/driver/xenadriver.py
labgrid/factory.py
labgrid/target.py

This PR fixes the lookup by string during the driver binding by introducing a new dictionary in the TargetFactory and using this to look at all registered resources and drivers.
It then converts the imports used for the bindings to strings.
**Checklist**
Tested by running tox, which also revealed the lookup problem.

Convert drivers from imports to strings

---

labgrid/remote/coordinator.py
labgrid/remote/exporter.py

We found two cases where the exporter and coordinator could block for some time, leading to ping timeouts and forced restarts. This PR allows scheduling other async tasks more often.
**Checklist**

improve async scheduling

---

crossbar-requirements.txt

The most resent update of zlmdb (20.1.1) is not compatible with crossbar 19.11.1. Hence this explicit version pin to zlmdb 19.11.1 in the crossbar requirements file

crossbar-requirements: Add explicit zlmdb version

---

.crossbar/config.yaml
CHANGES.rst
docker/staging/docker-compose.yml

Change the crossbar workdir configuration, for labgrid, from being
the parent dir to the actual workdir of crossbar. This implies
that all files related to crossbar are in the same dir.

crossbar: move labgrid specific files to general workdir

---

labgrid/target.py
tests/test_target.py

When getting named resources and drivers fails because the requested name is unavailable the error messages do not say which name was not found. Add the name in these cases. While at it use named args for extensive format strings and remove redundancies in exception messages.
**Checklist**

target: improve exception messages

---

labgrid/config.py
labgrid/driver/openocddriver.py

I am not sure if moving the reusable part of `resolve_path_str_or_list()` from the OpenOCDDriver to Config is beneficial . Either way, it was [requested back in summer 2018](https://github.com/labgrid-project/labgrid/pull/270#pullrequestreview-133655151), so here we go.
Feedback (as always) welcome.
**Checklist**

config: move resolve_path_str_or_list() from OpenOCDDriver to Config

---

labgrid/driver/networkusbstoragedriver.py
labgrid/resource/udev.py

Instead of explicitly checking if self.storage.path is set use the `@Driver.check_active` decorator. In order to make this work for USBMassStorage resources overwrite its avail attribute.
**Checklist**
Fixes #363
Replaces #556

driver: networkusbstorage: make decorator check that resources are bound

---

CHANGES.rst
labgrid/driver/networkusbstoragedriver.py
labgrid/remote/client.py

This PR enables writing to USB storage partitions and enables skip and seek for `Mode.DD`. Corresponding options were added to the client's `write-image` action.
**Checklist**

Add write-image features

---

labgrid/binding.py

Currently the error message does not tell a user (without detailed knowledge of driver binding states) why the method called cannot be called at this time:
```
Driver.method can not be called (Driver(target=Target(name='name', env=Environment(config_file='conf.yaml')), name=None, state=<BindingState.bound: 1>) is in state bound)
```
The exception is raised only if the state is not active, so make the error message say this:
```
Driver(target=Target(name='name', env=Environment(config_file='x86-esr.yaml')), name=None, state=<BindingState.bound: 1>) has not been activated, Driver.method cannot be called in state "bound"
```
**Checklist**

binding: improve StateError message

---

labgrid/remote/client.py
man/labgrid-client.1
man/labgrid-client.rst

This also helps setting the correct URL form for a coordinator URL.
**Checklist**

man/remote: client: document 'labgrid-client -x' default

---

.travis.yml
labgrid/driver/sshdriver.py
tests/conftest.py
tests/test_sshdriver.py

Convert ssh_prefix to a list and adjust all users. This was a string
previously, which led to get() and put() being broken on master, since
the string contained spaces. Convert it to a list, adjust the callers
and add new tests to test the SSHDriver against localhost. We also add a
new pytest option to supply the username, to make this work on travis.
Fixes: 1d7b97b838f7 (driver/sshdriver: Allow whitespaces in filenames Prevent filenames with whitespaces from beeing split.)
**Checklist**
Thanks @krevsbech for the report on IRC.

sshdriver: ssh_prefix to list and adjust users

---

doc/getting_started.rst

The instructions outlined here are not only valid for stretch, but also for buster.

doc/getting_started: instructions are also valid for buster

---

labgrid/remote/exporter.py

Up to now we only support 115200 baud for the serial console.
Add a new option to allow a different baud rate to be used.
Signed-off-by: Matthias Brugger <matthias.bgg@gmail.com>
Documentation for the feature already exists but it wasn't actually implemented.
I tested this with a MediaTek board that has a baudrate of 921600 on it's serial console.
**Checklist**

USBSerialPorts: Add baudrate

---

labgrid/remote/exporter.py

Remove the explicit path from ser2net. Setting PATH correctly is for the
user to decide, and this allows overriding it externally with a locally
compiled version by modifying PATH.
Reasonably sure this breaks debian packages which run labgrid as a non-root user. We could modify the service units for this.
On the other hand this will be useful to have to test newer ser2net versions locally without updating the system.
@jluebbe what do you think?
**Checklist**

labgrid/remote: remove explicit path from ser2net

---

labgrid/util/yaml.py
tests/test_yaml.py

This could otherwise cause problems with other users of the yaml module
in the same python process.
**Checklist**

util/yaml: avoid customization on the default Loader/Dumper classes

---

CHANGES.rst
doc/configuration.rst
labgrid/driver/ubootdriver.py

Currently it's not possible to boot into shell on Linksys WRT3200ACM
device as the U-Boot there doesn't have standard bootcmd:
```
Marvell>> run bootcmd
Unknown command 'run nandboot' - try 'help'
```
So lets introduce new `boot_command` argument which defaults to current
`run bootcmd`, but can be overriden on such exotic targets.
**Checklist**

ubootdriver: allow overriding of boot command

---

doc/getting_started.rst
labgrid/driver/smallubootdriver.py

* smallubootdriver: fix missing init_commands argument support
* doc/getting_started: fix missing python3-setuptools package

smallubootdriver and getting_started fixes

---

labgrid/pytestplugin/__init__.py
labgrid/pytestplugin/fixtures.py
labgrid/strategy/common.py
labgrid/strategy/shellstrategy.py
labgrid/target.py

This adds support for the Stategy state forcing approach we've been using internally in some test suites to labgrid itself. It's exposed as a `--lg-initial-state=` on the pytest plugin.
Also, it makes it possible to use `target.get_driver("Strategy")` to get the registered Strategy without knowing the actual class.
**Checklist**

strategy improvements

---

debian/control
debian/labgrid.install
doc/configuration.rst
helpers/labgrid-bound-connect
labgrid/driver/sshdriver.py
labgrid/remote/client.py
labgrid/remote/exporter.py
labgrid/util/proxy.py
labgrid/util/ssh.py
man/labgrid-client.1
man/labgrid-client.rst

When the target is only reachable via link-local addresses or overlapping network ranges, we need to make sure to connect from a specific interface on the exporter. This is possible using the SO_BINDTODEVICE socket option (which requires root privileges, so we need a sudo helper script) and some additional SSH tunneling.
As SSH is now more widely usable, also implement the low-hanging fruits in labgrid-client and SSHDriver (scp, rsync and sshfs).
**Checklist**

support binding outbound SSH connections to specific interfaces, add support for scp, rsync and sshfs to labgrid-client

---

labgrid/resource/udev.py

This is compatible with the other i.MX8M*.

resource/udev: add VID and PID for i.MX8MM

---

labgrid/pytestplugin/reporter.py
tests/test_fixtures.py

Currently pytestplugin reporter uses pytest internal API, which was
broken with 6.0.0 release by removing safe_text_dupfile()
function. Workaround that by using EncodedFile() and porting part of old
safe_text_dupfile() implementation.
Internal implementation of TerminalWriter has also been modified and
with 6.0.0+ pytest version there is no reline() method. Workaround that
by setting self.rewrite=False for all StepReporter instances.
Fixes: #629

pytestplugin: workaround pytest>=6.0.0 compatibility

---

labgrid/remote/exporter.py

See:
https://github.com/labgrid-project/labgrid/issues/565
Verified to work when using ser2net version 2.10.0 and version 4.1.8.
Test performed: 
- Start exporter
- Check which port is chosen
- Connect using telnet to the ip / port
Verify that commands be send, and output seen.

remote/exporter: Use YAML syntax for ser2net if version > 4.0.0

---

labgrid/driver/sshdriver.py
tests/test_sshdriver.py

Adding a "-r" in front of filename helps with folders, and it still works
with regular files.
Prior to commit 1d7b97b838f7, something like this was working:
ssh.put('-r <folder_name>', '<remote_location>')
but afterwards, scp fails with "unknown option --".
Add a similar change for ssh.put
Fixes: 1d7b97b838f7 (driver/sshdriver: Allow whitespaces in filenames Prevent filenames with whitespaces from beeing split.)
Signed-off-by: Mirela Rabulea <mirela.rabulea@nxp.com>
**Checklist**

driver/sshdriver: Allow filename to be a folder

---

requirements.txt

collections.abc was removed in Python 3.9. pyudev 0.22.0 deals with this change.
**Checklist**

Update pyudev to py39 compatible version

---

labgrid/driver/serialdriver.py
requirements.txt
setup.py

The version might contain 'b' in a component, e.g., with the newest beta
version 3.5b0. This makes the int() conversion fail. Switch to packaging.version comparison.
**Checklist**

serialdriver: Prevent pyserial version check fails

---

doc/configuration.rst
labgrid/driver/__init__.py
labgrid/driver/usbloader.py

add driver for NXP mfgtools uuu
https://github.com/NXPmicro/mfgtools.git
**Checklist**

labgrid: add uuuloader and uuudriver

---

doc/overview.rst
labgrid/util/proxy.py

If we want to connect to an isolated exporter, prefer a connection to
the exporter over the LG_PROXY variable. We expect the user to have a
properly setup SSH config to access the exporter, document this as a
note in the proxy documentation.
**Checklist**
Fixes https://github.com/labgrid-project/labgrid/issues/620

util/proxy: prefer isolated over LG_PROXY

---

labgrid/driver/power/gude24.py

When the Gude Expert Power Control 8080 receives a request it blocks requests from other IP addresses for 120 seconds. Therefor when user A creates a request to the web interface user B with a different IP can not make a request for two minutes. The return message user B will get is:
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta http-equiv="cache-control" content="no-cache">
<link rel="stylesheet" type="text/css" href="style.css">
<title>Device blocked</title>
</head><body><h2 align="center"><font color="red">Device is blocked by another user with IP xyz</font></h2>
<hr size=1 noshade><p align="center">[<a href="/">back</A>]
</body></html> 
```
The previous …

driver/power/gude24.py: Raise execution error if device is blocked

---

labgrid/driver/power/gude8031.py

Added Power Driver for Gude Expert Power Control 8031 due to a different web interface. Was tested with local setup.
**Checklist**

Power Driver for Gude8031

---

doc/configuration.rst

For USB hubs controlled by the USBPowerPort, the interface needs to be
included in the Paths, since the wrong driver will be detected
otherwise.
**Checklist**
Closes https://github.com/labgrid-project/labgrid/pull/291

doc/configuration: document USB hub interfaces

---

doc/configuration.rst
labgrid/driver/__init__.py
labgrid/driver/lxaiobusdriver.py
labgrid/remote/client.py
labgrid/remote/exporter.py
labgrid/resource/__init__.py
labgrid/resource/lxaiobus.py
labgrid/resource/remote.py
tests/test_lxaiobus.py

Add support and documentation for the LXA IO Bus, through the
lxa-iobus-server. Currently only digital output pins are supported. Also
extend the documentation and add support for switching the outputs
through the remote client.
**Checklist**
Supercedes https://github.com/labgrid-project/labgrid/pull/578

lxaiobus: support for LXA IO Bus nodes

---

.travis.yml
setup.py

Add CI for python 3.9 and adjust the classifiers in setup.py

CI Support for python 3.9

---

labgrid/driver/sshdriver.py

The scp/rsync/sshfs methods use the SSH control master. In these cases no valid hostname is required. Certain SSH config option combinations break this behavior, e.g.:
```
Host *
CanonicalDomains          example.com
CanonicalizePermittedCNAMEs *.example:*.example.com
```
This leads to:
`Could not resolve hostname _: Name or service not known`
or
`Could not resolve hostname : Name or service not known`
Fix this by forcing no config file for these commands.
**Checklist**

driver/sshdriver: force no config when no hostname given

---

labgrid/driver/powerdriver.py
tests/test_powerdriver.py
tests/test_stepreporter.py

The user expects the name of the target instead of the name of the driver.
**Checklist**

driver/power: use target's name in ManualPowerDriver user prompts

---

labgrid/driver/quartushpsdriver.py

Beside flashing, erasing a region at a specific offset with a specific
size is a common operation with quartus_hps.
If 'size' is omited, everything starting from address will be erased.
If 'address' is omitted, a bulk erase of the entire device will be
performed.

driver/quartushpsdriver: support erase operation

---

labgrid/driver/usbstoragedriver.py

Fixes: 1a5c787a ("driver/usbstoragedriver: log what actually gets written")
**Checklist**

driver/usbstoragedriver: fix bmaptool call format string

---

CHANGES.rst
doc/configuration.rst
labgrid/config.py
tests/test_config.py

In environments with multiple targets, having only the global options available requires using using prefix/suffix if those options differ between targets. Per-target options solve this issue and relate to the global options the same way per-target feature flags relate to the global feature flags.
**Checklist**

Add support for per-target options

---

labgrid/driver/qemudriver.py

Various configuration parameters of the QEmuDriver lead to QEMU getting called with `-append`. This might not be obvious to the user. If the user specifies `-append` in `extra_args` instead of using `boot_args`, the `-append` argument in `extra_args` is ignored by QEMU. This happens because the last occurrence of `-append` is used, all other occurrences are silently ignored [1].
Add an explicit check to make sure no `-append` is given in `extra_args`, and suggest the usage of `boot_args` which leads to only a single `-append` being passed to QEMU.
[1] https://lists.gnu.org/archive/html/qemu-devel/2017-05/msg03214.html
**Checklist**

driver: qemudriver: prevent multiple -append QEMU arguments

---

labgrid/driver/sshdriver.py
tests/test_sshdriver.py

Only remove the final line from the output if it is empty. This prevents
swallowing of output if the SSHDriver stdout does not contain a final
new line.
Related to https://github.com/labgrid-project/labgrid/issues/613
**Checklist**

sshdriver: only remove final line if empty

---

.github/workflows/docker.yml
.github/workflows/unit-tests.yml

The Travis CI credits in our free plan were only enough for a few days. As I've not received a response to my request for OSS credits, migrate the CI to GitHub Actions.

github: add workflows for unit tests and docker images

---

doc/configuration.rst
labgrid/driver/__init__.py
labgrid/driver/usbsdwiredriver.py
labgrid/driver/usbstoragedriver.py
labgrid/remote/client.py
labgrid/remote/exporter.py
labgrid/resource/__init__.py
labgrid/resource/remote.py
labgrid/resource/suggest.py
labgrid/resource/udev.py

Adds a driver for the Tizen SDWire based device SD Card multiplexer.
This device is very similar to the already existing SDMux device (which
is distinct from the Tizen SDMux device on which SDWire is based).
The primary differences are:
1) SDWire is controlled with the `sd-mux-ctrl` tool
2) The serial number for SDWire devices is tied to the control chip
(an FTDI-based GPIO solution).
See: https://wiki.tizen.org/SDWire
**Checklist**

Add sdwire driver

---

labgrid/remote/client.py

These are leftovers from the method prior to 77ee439
("driver/sshdriver: move interactive SSH access to the SSHDriver").
The instanciation of NetworkService is still needed to bind a
NetworkService with an IP of an EthernetPort resource to the target.
**Checklist**

remote/client: remove unused variables from _get_ssh()

---

labgrid/driver/fastbootdriver.py
labgrid/driver/flashromdriver.py
labgrid/driver/usbstoragedriver.py
labgrid/remote/client.py
labgrid/util/helper.py

#469 introduced ProcessWrapper, acting "like `subprocess.check_output`, but takes callbacks to send the output of the command to". This PR aims to improve the user experience of process output:
Output is now split on "\r" instead of "\r\n". This allows processing output of commands rewriting lines. It is currently used for "labgrid-client write-image" which again uses "dd status=progress".
Command output is in many cases not recognizable by the user without knowing the actual command. This gets even worse when multiple processes emit output. This is addressed by printing the command as well as its PID when started and prepend the PID to every log line of output.
To make use of this ProcessWrapper's logging callback is enabled for labgrid-client. Command output that is …

Improve process output logging, adjust client log levels

---

labgrid/exceptions.py
labgrid/factory.py
labgrid/remote/client.py
labgrid/target.py
tests/test_factory.py
tests/test_target.py

For the power and digital_io command, try to get a bound driver via
protocol first. This way already instanced drivers from a passed in
environment file can be chosen, even if they are not part of upstream
labgrid, or require a driver as a supplier.

remote/client: try protocols before driver

---

doc/development.rst
doc/getting_started.rst

The development environment installs crossbar as well, and subsequently
requires python-snappy which will only install if the headers can be
found.
**Checklist**

doc/development: add libsnappy-dev as requirement

---

labgrid/pytestplugin/fixtures.py

Commit 1773cf8a3edd ("pytestplugin/fixtures: exit with error if target
init failed") tried to catch the UserError in case the target is not
locked, however the UserError already occurs in the env fixture, when
trying to record the target properties:
```
request = <SubRequest 'env' for <Function test_barebox_log_level>>, record_testsuite_property = <function record_testsuite_property.<locals>.record_func at 0x7f7dad25f8b0>
@pytest.fixture(scope="session")
def env(request, record_testsuite_property):
"""Return the environment configured in the supplied configuration file.
It contains the targets contained in the configuration file.
"""
env = request.config._labgrid_env
if not env:
pytest.skip("missing environment config (use --lg-env)")
record_testsuite_property('ENV_CONFIG', …
```

pytestplugin/fixture: exit early if not acquired

---

labgrid/util/helper.py

The pytester pytest plugin will setup multiple pytest sessions and calls
the pytest_configure multiple times. This leads to multiple registration
of the logging callback, which triggers the assert that the callback can
only be registered once. Remove the assert and replace it with a check
to register the callback only once.
**Checklist**
Fixes https://github.com/labgrid-project/labgrid/issues/684

util/helper: multiple registration of callbacks

---

CHANGES.rst
doc/configuration.rst
labgrid/driver/__init__.py
labgrid/driver/powerdriver.py
labgrid/remote/client.py
labgrid/remote/exporter.py
labgrid/resource/__init__.py
labgrid/resource/remote.py
labgrid/resource/suggest.py
labgrid/resource/udev.py
tests/test_sispm.py

This patch adds support for SiS-PM (Silver Shield PM) Control
for Linux, aka sismpctl.
Signed-off-by: Matthias Brugger <matthias.bgg@kernel.org>
**Checklist**

driver/power: Add power driver to support GEMBIRD SiS-PM Control

---

labgrid/remote/exporter.py
labgrid/util/agents/sysfsgpio.py

Fix accessing sysfs GPIOs over a network
**Checklist**

Fix Network sysfs GPIO

---

doc/development.rst

- fix missing `StrategyError` import
- register custom strategy with `@target_factory.reg_driver`
- fix use of `@step` decorator (otherwise we get `TypeError: step() takes 0 positional arguments but 1 was given`)

doc: development: fix custom strategy skeleton

---

debian/copyright
doc/conf.py

labgrid is in active development, so extend the copyright period to reflect that.

debian/doc: extend copyright period to 2021

---

labgrid/resource/udev.py

Newer (?) Deditec 8 way relais board have a device individual and unique
serial number. In order to make those work with labgrid, the
ID_SERIAL_SHORT must be user definable.
To not break existing setups, the fallback value will be the already
existing default.

resource: DeditecRelais8: add ID_MODEL

---

helpers/labgrid-bound-connect

Delete the ARP or NDP cache before attempting to connect to a service.
For devices that are assigned an ephemeral MAC address on boot instead
of using a fixed one, these caches may be out of date which results in
the connection failing.
**Checklist**

labgrid-bound-connect: Delete IP cache

---

CHANGES.rst
labgrid/remote/client.py
man/labgrid-client.rst

Adds environment variables LG_CLAIM_HOSTNAME/LG_CLAIM_USER to control
the hostname and user that used to make a claim on a place. This is
useful in container based build pipelines where multiple pipeline stages
may need to use a claim, but the hostname and user name running in each
container differs (e.g. Tekton in Kubernetes).
Signed-off-by: Joshua Watt <JPEWhacker@gmail.com>
**Checklist**

client: Add LG_CLAIM_HOSTNAME/LG_CLAIM_USER

---

doc/configuration.rst
labgrid/driver/serialdigitaloutput.py

This allows the inversion of serial lines lines which are used as
digital outputs. This is done on the driver level to not clutter the
SerialPort resource, which is usually used for communication and not as
a digital output.
**Checklist**

driver: add invert to SerialDigitalOutputDriver

---

CHANGES.rst
dev-requirements.txt
doc/configuration.rst
examples/pyvisa/env.yaml
examples/pyvisa/pyvisa_example.py
labgrid/driver/__init__.py
labgrid/driver/pyvisadriver.py
labgrid/resource/__init__.py
labgrid/resource/pyvisa.py
pyvisa-requirements.txt
tests/test_pyvisa.py

Add driver and resource to support controlling test instruments using the
PyVISA package.
The [PyVISA](https://pypi.org/project/PyVISA/) project provide a python package  to control measurement devices and test equipment via GPIB, RS232, Ethernet or USB.
A transparent wrapper is implemented in Labgrid to allow representing PyVISA devices as resources.
PR has been tested locally using a RSDG 2024 signal generator connected over TCP/IP. The test has been added in examples
to also serve as an example for future use.
**Checklist**

driver/pyvisadriver: add driver to support PyVISA

---

crossbar-requirements.txt
requirements.txt

Two version bumps to fix our python 3.9 builds. Autobahn is not strictly necessary, but it's nice to keep things in sync.
**Checklist**
Due to autobahn and crossbar dropping Python 3.5, this PR break Python 3.5 as well, at least for the CI.

Update Crossbar & Autobahn to 20.12.x

---

helpers/labgrid-bound-connect

Fixes a typo in the IP cache invalidation that prevents the helper from
running.
Signed-off-by: Joshua Watt <JPEWhacker@gmail.com>
**Checklist**

labgrid-bound-connect: Fix typo

---

labgrid/strategy/bareboxstrategy.py
labgrid/strategy/shellstrategy.py

This updates the default strategies to what we've been using internally for some time.
The console enable change makes sure that we don't miss bootloader output when enabling power to the board.

strategy: use name-based bindings and enable console early

---

labgrid/target.py
tests/test_target.py

Allow optional bindings to the same protocol if both are not available. We simply ignore this case since we don't care about a duplicate binding than.
**Checklist**

Fix DuplicateBinding Error for optional bindings of the same protcol

---

labgrid/remote/exporter.py

The exporter was ignoring the device baud rate when invoking ser2net and
always connected at 115200 baud. Change the exporter to correctly
respect the device baud rate.
Signed-off-by: Joshua Watt <JPEWhacker@gmail.com>
**Checklist**

exporter: Correctly handle serial baud rates other than 115200

---

labgrid/remote/client.py
labgrid/remote/common.py
tests/test_crossbar.py

Labgrid client now requires that all matches are fulfilled when locking
a place:
```
$ lgc -p cc add-match this/isatest/match
$ labgrid-client -p cc lock
labgrid-client: error: Match this/isatest/match has no matching resource
```
Use the -l argument to loosen this requirement.
```
$ lgc -p cc add-match this/isatest/match
$ labgrid-client -p cc lock -l
$
```
**Checklist**

remote: require that all matches are fulfilled when places are locked

---

doc/configuration.rst
labgrid/driver/powerdriver.py
labgrid/remote/client.py

Each power driver defines its own default delay value. Respect that by dropping the default from the client's delay cli argument and only passing the delay value when it is actually specified via the cli.
In order to make that simpler, make the PDUDaemonDriver expect its delay as a float value (not an int) as all other power drivers do.
**Checklist**

Pass delay to power drivers only if specified explicitly

---

labgrid/remote/exporter.py

The start params do not contain the speed for the serial port, but the
local SerialPort resource does, so fetch it from there.
Fixes: 162e903d1b68 ("exporter: Correctly handle serial baud rates other than 115200")
**Checklist**

exporter: fix SerialPortExport start params

---

doc/configuration.rst
labgrid/driver/__init__.py
labgrid/driver/usbhidrelay.py
labgrid/protocol/digitaloutputprotocol.py
labgrid/remote/exporter.py
labgrid/resource/remote.py
labgrid/resource/udev.py
labgrid/util/agents/usb_hid_relay.py
tests/test_agent.py

This adds local and remote support for simple USB HID relays. Support for more protocols can be added easily to the agent.
**Checklist**

add support for USB HID relays

---

dockerfiles/base/Dockerfile

It seems like recent Python cryptography package versions need Rust
compiler present for OpenSSL wrapper, which leads to following error:
```
generating cffi module 'build/temp.linux-x86_64-3.7/_openssl.c'
running build_rust
...
error: Can not find Rust compiler
```
There is following note regarding this issue in the documentation:
> If you are on RHEL/CentOS/Fedora/Debian/Ubuntu or another distribution
derived from the preceding list, then you should upgrade pip (in a
virtual environment!) and attempt to install cryptography again before
trying to install the Rust toolchain. These platforms will receive a
binary wheel and require no compiler if you have an updated pip!
So fix this by recommended pip update.
References: https://cryptography.io/en/latest/installation.html#rust

docker: base: fix Python cryptography build failure

---

dockerfiles/client/Dockerfile

rsync is required on the client side to transfer files to a remote host
**Checklist**

docker: Add rsync to client

---

README.rst

Drop the Travis CI badge in favor of GitHub actions unit tests/docker build workflow badges.

README: update badges

---

CHANGES.rst
labgrid/driver/ubootdriver.py

Current 30 second timeout used by default in `await_boot()` might not be
enough in some corner cases where we for example boot large initramfs
images over network, which take some time to load, decompress and boot:
```
await_boot state='start'
expect state='start', args={'pattern': 'Linux version \\d'}
expect state='stop', result=(0, b"bootm 0x83000000 ... b'Linux version 4'), duration=42.025
```
So make it possible to override the default timeout via new `boot_timeout` variable.
**Checklist**

ubootdriver: allow overriding of await boot timeout

---

.github/workflows/unit-tests.yml
CHANGES.rst
doc/usage.rst
labgrid/pytestplugin/reporter.py
tests/conftest.py
tests/test_stepreporter.py

The default color schemes use 256-color escape sequences, which are not fully supported by all terminals (e.g. the Linux virtual console).
First refactor the exiting code a bit.
Then add two more dark and light color schemes that only use the original 8 colors. Then try to detect if the terminal in use understands the enhanced escape codes, and in that case use the 256-color dark scheme by default.
As a side effect, the two new color schemes also work well in terminals with "solarized" color schemes.
**Checklist**

ColoredStepReporter: be compatible with 8-color terminals

---

labgrid/driver/quartushpsdriver.py

It might take a while until an intact JTAG chain is available, so keep retrying for a while. There is no point in using a JTAG cable with a broken chain, so bail out in case no intact chain is found.
**Checklist**

driver: quartushpsdriver: retry on broken JTAG chain

---

labgrid/remote/client.py

Adds support for the client to control relays attached to a USB HID
Relay using the "io" subcommand
**Checklist**

client: Add support for HIDRelay GPIOs

---

.codecov.yaml

As significant parts of labgrid are not practical to test, these annotations
are only distracting during code review.

.codecov.yaml: disable github check annotations

---

CHANGES.rst
doc/configuration.rst
labgrid/driver/power/rest.py
tests/test_powerdriver.py

Add a new driver to support relay based power control where relay is controlled with a REST API with a simple GET/PUT request to the same URL.
This is different from simplerest driver, as it relies on REST interface using
GET to query status, and PUT to change status, where as simplerest driver uses
GET for both purposes.
These two models are therefore inherently incompatible, and supplements each
other.
**Checklist**

driver/power: add support for REST based relays controlling power

---

CHANGES.rst
labgrid/consoleloggingreporter.py

I was confused why `pytest --lg-log foobar` would silently refuse to log anything, but I found out why:
* the directory `foobar` did not exist before, and it was not created anywhere
* the error handling in `ConsoleLoggingReporter.get_logfile()` only caught PermissionErrors when opening the log file, but `open()` raised a FileNotFoundError when opening the log file because the directory did not exist (but I did not figure out why pytest didn't report this uncaught exception…)
Solve both of those issues by creating the log path in `ConsoleLoggingReporter.__init__()`, and improving the error handling.
**Checklist**

ConsoleLoggingReporter: create log path and improve error handling

---

labgrid/driver/sshdriver.py
labgrid/remote/client.py
tests/test_sshdriver.py

Adds a context manager function that will forward a port on the local
host to a port on the target
**Checklist**

sshdriver: Add port forwarding

---

doc/configuration.rst
dockerfiles/Dockerfile
labgrid/driver/sshdriver.py
tests/test_docker.py

Fixes bug #697 when connecting to a place via ssh proxy. I have tried to use both, subprocess/Popen/write and pexpect/spawn/expect/sendline to write the password to stdin, but as sshpass, it only works when connecting without proxy and fails when connecting via ssh proxycommand. Then I found the builtin ssh option SSH_ASKPASS, which is the only left way to pass the password from a script, or a graphical user interface to the agent. It may not be the most elegant solution, but it works for us and it is robust.
**Checklist**

driver/sshdriver: use SSH_ASKPASS instead of sshpass

---

labgrid/target.py

We do not support python3.5 anymore, so we can use an f-string here.
**Checklist**
Fixes #669

target: fix broken format string in print statement

---

labgrid/resource/serialport.py

Instantiating an exception, but not raising it, has no effect.
**Checklist**
Fixes: e21a5eba ("resource: rename SerialPort to RawSerialPort")

resource: serialport: raise exception rather than only instantiating it

---

labgrid/driver/externalconsoledriver.py

The docstring states that this method does nothing if it is already closed. This is not the case, multiple calls lead to "child has
vanished" ExecutionErrors. Fix that by resetting the driver state, so the next close() call returns early.
**Checklist**
Fixes 69d5c69c

driver: externalconsoledriver: allow multiple close() calls

---

doc/configuration.rst
labgrid/driver/lxausbmuxdriver.py
labgrid/remote/client.py
labgrid/remote/exporter.py
labgrid/resource/remote.py
labgrid/resource/suggest.py
labgrid/resource/udev.py

This devices allows switching a USB device between the host and the DUT.
**Checklist**

add support for Linux Automation USB-Mux

---

labgrid/driver/usbsdmuxdriver.py
labgrid/remote/client.py

The usbsdmux tool dropped the service/client split with https://github.com/linux-automation/usbsdmux/commit/656e3d5ca46f6e7a707925707dc9504dcd18fb33, so stop passing `-c` (client mode). 
https://github.com/linux-automation/usbsdmux/commit/628303606c4fdb15a65f85a804900d05de8994dd added support to query the currently selected mode. Add support for that to the `USBSDMuxDriver` as well as to the client (allowing `labgrid-client sd-mux get`).
**Checklist**

client/usbsdmuxdriver: drop deprecated command line switch, add mode query

---

doc/conf.py
doc/configuration.rst
examples/networkmanager/nm.env
examples/networkmanager/nm.py
labgrid/driver/__init__.py
labgrid/driver/networkinterfacedriver.py
labgrid/remote/exporter.py
labgrid/resource/__init__.py
labgrid/resource/base.py
labgrid/resource/remote.py
labgrid/resource/suggest.py
labgrid/resource/udev.py
labgrid/util/agents/network_interface.py

This adds support for controlling an exported NetworkInterface remotely using NetworkManager over an agent connection.
Via NetworkManager, we can configure and inspect Ethernet and WiFi (client&AP) interfaces. This is especially useful for testing WiFi interfaces on the DUT.
**Checklist**

add NetworkManager remote control via agent

---

labgrid/driver/__init__.py

This leads to
```
labgrid.exceptions.InvalidConfigError: unknown driver class LXAUSBMuxDriver
```
when used with an environment config. So fix it.
**Checklist**
Fixes #766

driver: add missing LXAUSBMuxDriver in __init__.py

---

CHANGES.rst
doc/overview.rst
doc/usage.rst

NetworkServices specify their own proxies, which take precedence over
LG_PROXY. This isn't clear when specifying LG_PROXY, and I didn't know
both had to be configured in .ssh/config. I've added some documentation
showing how to debug this.
Signed-off-by: Thomas Preston <thomas.preston@codethink.co.uk>
**Checklist**
- N/A Tests for the feature 
- N/A The arguments and description in doc/configuration.rst have been updated
- N/A Add a section on how to use the feature to doc/usage.rst
- N/A Add a section on how to use the feature to doc/development.rst
- N/A PR has been tested
- N/A Man pages have been regenerated

doc/usage: LG_PROXY: Add NetworkServices proxy note

---

labgrid/remote/common.py

`labgrid.remote.client` and `labgrid.remote.coordinator` import `*` from `labgrid.remote.common`. This leads to various modules being imported implicitly. Polluting the namespace like this could overwrite previous local imports or variables.
Better specify explicitly what should be imported on `*`.
**Checklist**

remote: common: list public objects explicitly

---

CHANGES.rst
labgrid/remote/exporter.py

On Debian, the ser2net binary is installed at /usr/sbin/ser2net and it
can be run by any user. Since this isn't on the users PATH, we should
attempt to use it when failing to find a ser2net binary, before falling
back to /usr/bin/ser2net.
Signed-off-by: Thomas Preston <thomas.preston@codethink.co.uk>
You can quickly see this like so:
```
$ podman run -it debian:bullseye
-rwxr-xr-x. 1 root root 136696 Aug 24  2018 /usr/sbin/ser2net
```
**Checklist**
- N/A Documentation for the feature (not necessary, just searches in an additional place)
- N/A Tests for the feature (not necessary)
- N/A The arguments and description in doc/configuration.rst have been updated (not relevant)
- N/A Add a section on how to use the feature to doc/usage.rst (not relevant)
- N/A Add a section on how to use the …

exporter: Check /usr/sbin for ser2net

---

contrib/systemd/labgrid-coordinator.service
contrib/systemd/labgrid-exporter.service
contrib/systemd/sysusers.d/labgrid.conf
contrib/systemd/tmpfiles.d/labgrid.conf
doc/getting_started.rst

Adds systemd services for coordinator and exporter.
While the coordinator can be run under a dynamic user, the exporter needs a dedicated system group: Users, that are a member of the `labgrid` group are then able to store `ManagedFile`s in `/var/cache/labgrid`. Therefore also adds a sysusers.d file that creates the `labgrid` user and group. Further hardening (e.g. dropping privileges) of the services has been omitted; however, it is questionable whether this is needed in a lab environment anyway.
One can set the coordinator URL the exporter should connect to by overriding the exporter service file; i.e. one would execute `systemctl edit labgrid-exporter.service` and add the following snippet:
[Service]
Environment="LG_CROSSBAR=ws://<your-host>:<your-port>/ws"
Tested on …

contrib/systemd: add systemd services

---

doc/configuration.rst
doc/usage.rst
labgrid/driver/bareboxdriver.py
labgrid/driver/shelldriver.py

The concept of "activation" is mentioned a few times in the docs, but it is explained nowhere. Try to change that by distilling the code from `labgrid.target.Target.activate()` into an explanation with an example. Also document how to create multiple resources of the same type and bind them to drivers through the API. While at it, add a few more links to the API doc, and throw in some smaller drive-by improvements to the docs.

docs: improve library usage docs

---

labgrid/driver/power/digipower.py

This changes basically make this driver work. I am not sure if it ever worked at all:
* Indexing of the `portstring` and `ports` -dicts has probably never worked
the way it was done: `index` is explicitly casted to `int` but indices
have been `str`.
* `response.content` is the bytes-response from the server.
The way it was used before probably never worked the way it was done:
A byte-array can not be splitted using a string.
When using `response.text` decoding is done by `requests` what is
probably the best idea here.
This problems showed up when I wanted to bring up a new lab in our infrastructure that is equipped with a Digipower power-switch.
I successfully tested the `get` and `set` methods against our device.
**Checklist**

driver/power/digipower: Make driver work

---

setup.py

Include the README.rst as the long_description, so we get a properly
rendered README.rst on Pypi.
See https://packaging.python.org/guides/making-a-pypi-friendly-readme/
Preview available at: https://test.pypi.org/project/labgrid-EMANTOR/
**Checklist**

setup.py: add README.rst

---

tests/test_stepreporter.py
tests/test_util.py

When running the test suite, various warnings and exceptions happen. Some occur because cleanup actions are called explicitly during tests leading to errors once the atexit registered cleanup methods run. Unregister the atexit cleanup methods for these tests explicitly. Another warning happens because not all of pytest's TerminalWriter features that we use are mocked. Extend `MockTW` accordingly.
**Checklist**
Fixes #730
Fixes #687

tests: fix warnings and atexit exceptions

---

doc/configuration.rst
labgrid/driver/openocddriver.py
labgrid/remote/exporter.py
labgrid/resource/remote.py
labgrid/resource/suggest.py
labgrid/resource/udev.py

This cleans up the OpenOCD driver and adds support for using FTDI-based JTAG interfaces. I've used this to load bitstreams on a [ECPIX-5 FPGA devboard](http://docs.lambdaconcept.com/ecpix-5/features/debug.html).
**Checklist**

add support for USB JTAG debuggers

---

contrib/sync-places.py

The code was only adding matches and tags for places that were seen
while processing adding/removing places. This meant that brand-new
places did not get the matches and tags set. Fix this to set tags and
matches for all places specified in the config file, but only query the
existing places and tags for places that were seen (which prevents
dry-run from breaking)
**Checklist**

contrib/sync-places: Fix missing matches on tag on new places

---

labgrid/remote/common.py

Up to now aliases were printed in a random order and resources in the
order they were added. To make it easier to find given resources or
aliases in long lists, alphabetical ordering is more sensible. Also
reproducible output helps when watching configuration over time or
comparing two settings.
**Checklist**
Run `labgrid-client -v places` and verified it is sorted and stable on repetition.

place/show: Sort aliases and resources for reproducibility

---

labgrid/driver/fastbootdriver.py

Remove passing of -i option to fastboot, since it has been removed
upstream by commit f3192bd05 ("Remove -i vendor id matching.").
Signed-off-by: Thorsten Scherer <t.scherer@eckelmann.de>
Debians (bullseye) fastboot 1:10.0.0+r36-7 removes the option for vendor id matching. Which breaks our labgrid fastboot setup. This commit aims at fixing this issue.
**Checklist**

driver/fastbootdriver: remove vendor_id matching

---

doc/configuration.rst
labgrid/driver/consoleexpectmixin.py
labgrid/driver/shelldriver.py

Some devices may have chatty consoles during login;
specifically, if a user logs into the root serial console of a target
using systemd that has not finished booting, boot messages will begin to
appear after login. These messages can interrupt prompt detection and
cause test timeouts. To allow proper detection of the prompt:
1. Add an API to wait for the device to "settle", e.g.
no output is seen on the console for a specified number of seconds and
add an option for the shelldriver to utilize it
2. Move the password and post-login prompt detection into the same main
main loop as the other prompt detection. This allows the same login and retry
logic to be used which make it more robust against noise.
**Checklist**

shelldriver: Handle intermingled output on login

---

labgrid/remote/client.py

We must abort the for loop as soon as we find any matching driver. Otherwise
we'd possibly overwrite it in a later iteration. This also avoids some
redundant lines.

remote/client: fix automatic driver selection

---

labgrid/remote/exporter.py

This is useful for debugging if ser2net is not starting correctly.

remote/exporter: info print ser2net command

---

doc/configuration.rst
labgrid/driver/__init__.py
labgrid/driver/manualswitchdriver.py
tests/test_manualswitchdriver.py

Adds a Manual Switch Driver which can be used to prompt the user to set
a jumper or switch when testing locally
**Checklist**

drivers/manualswitchoutput: Add Driver

---

labgrid/driver/flashscriptdriver.py
labgrid/driver/openocddriver.py

If the config/search/attrs attributes are changed in one object instance, they appear changed in all the others since they are in fact shared. This could happen when multiple OpenOCDDrivers/FlashScriptDrivers are instanciated on different resources.
Fix that by using a factory instead.
**Checklist**
Fixes #746 
Fixes #781
Fixes #270

driver: flashscriptdriver/openocddriver: avoid using mutable objects as defaults

---

doc/configuration.rst
doc/usage.rst
labgrid/driver/bareboxdriver.py
labgrid/driver/shelldriver.py
labgrid/driver/ubootdriver.py

This is an effort to allow creating labgrid environment configurations without looking at the code.
Some arguments of Resources/Drivers were outdated, incomplete or simply documented incorrectly. This should be fixed now.
It should be clear, which Driver/Resource arguments are optional and which default values are used when they are omitted. I made the default/optional notation used to for the BareboxDriver/UBootDriver consistent over all Drivers now.
Some Resources/Drivers were not documented at all, so I've added documentation for:
- DeditecRelaisDriver
- DeditecRelais8
- SysfsGPIO
- DigitalOutputResetDriver
While scrolling through the Driver code, I've updated some outdated/incomplete doc strings. I did not go through all of them, though.
While at it, I've also …

Improve docs, update Driver doc strings

---

labgrid/resource/udev.py

Imagine multiple USBResources match the same device, e.g.:
```
{% for idx, sysfs in [
(1,   'pci-0000:00:14.0-usb-0:2.3'),
(2,   'pci-0000:00:14.0-usb-0:2.4'),
(3,   'pci-0000:00:14.0-usb-0:2.1'),
(4,   'pci-0000:00:14.0-usb-0:2.2')] %}
usbhub-b-{{idx}}:
location: 'on my desk'
USBSerialPort:
match:
'@ID_PATH': '{{sysfs}}'
{% for port in range(1, 5) %}
usbhub-b-{{idx}}-outlet{{port}}:
SiSPMPowerPort:
match:
'ID_PATH': '{{sysfs}}'
index: {{port}}
{% endfor %}
{% endfor %}
```
This describes a 4 port USB hub. On each port USBSerialPort as well as SiSPMPowerPort resources should be exported. Note that the 4 power sockets of the _SiS-PM_ power outlet are exported separately.
This works if the SiS-PM is plugged before the exporter is started. In case it is then unplugged, not …

resource/udev: handle multiple resources on single device correctly

---

labgrid/remote/config.py

This allows using `{% include 'other.yaml' %}` to include further
configuration fragments.
**Checklist**

remote/config: support jinja2 includes

---

doc/configuration.rst

The "paths" key was missing in the config skeleton. It is referenced in the documentation of the QEMUDriver. See also Config's `get_path()` and `get_paths()` methods.
The "features" key is documented in its own section in `doc/usage.rst`, but it was missing in the config skeleton.
**Checklist**

doc: configuration: add missing keys "paths"/"features" to env config skeleton

---

labgrid/pytestplugin/fixtures.py

labgrid's `env` fixture calls `git rev-parse HEAD` in each path configured in the environments "paths" and "images" keys to record their corresponding commit-ishes.
Because of that, errors like these are quite common:
```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
This happens if the paths do not contain a git repository. Redirect these errors to `/dev/null` instead of printing them without context, confusing the users of the pytest plugin.
**Checklist**

pytestplugin: fixtures: redirect stderr of git commands to /dev/null

---

tests/test_util.py

Those tests require access to the ssh binary, skip them if ssh is not
available in the test environment.
**Checklist**

tests/util: skip tests if ssh is not available

---

CHANGES.rst
doc/configuration.rst
labgrid/driver/fastbootdriver.py

This fixes and improves ways to use preconfigured images in the yaml config for the AndroidFastbootDriver.
**Checklist**

drivers: fastbootdriver: fix flashing and allow booting of preconfigured images

---

tests/test_docker.py

Recent pytest versions print out a collection error if the module is not
skipped:
```
____________________ ERROR collecting tests/test_docker.py _____________________
ImportError while importing test module '/build/source/tests/test_docker.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/1g54cwl6m78rgrqsnn1pp29dbvldpvsd-python3-3.9.6/lib/python3.9/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
tests/test_docker.py:89: in <module>
???
tests/test_docker.py:17: in check_external_progs_present
import docker
E   ModuleNotFoundError: No module named 'docker'
=========================== short test summary info ============================
ERROR tests/test_docker.py …
```

tests/test_docker: skip unavailable docker module

---

tests/test_flashscript.py

The true and false binaries may not be available within the execution
environment of the tests (i.e. on Nixos), skip the tests if the binaries
are not available.
**Checklist**

test/flashscript: skip tests if binaries missing

---

labgrid/util/ssh.py

The first part of the condition always evaluates to True, so the output of the SSH check command is never considered.
Fortunately, this only results in wrong messages being logged in the worst case.
Fix that by actually checking if `stdout` contains `b"No such file or directory"`.
**Checklist**
Fixes: #687

util/ssh: fix control master check

---

CHANGES.rst
examples/power/env.yaml
examples/power/power_example.py
labgrid/driver/power/eaton.py
tests/test_powerdriver.py

The NetworkPowerDriver for the pdu uses PySNMP.
Signed-off-by: Nikolaj Rahbek <nikolaj@b2vn.org>
Added support for Eaton ePDU via SMNP. The resource is implements the NetworkPowerPort, and therefore works like other power drivers, e.g. the apc power driver.
An usage example has been added under `examples/power/`, and includes both an environment yaml and a pytest example.
The driver has been tested on Eaton eMMA10.
**Checklist**

driver: add eaton epdu network power driver

---

labgrid/strategy/bareboxstrategy.py
labgrid/strategy/shellstrategy.py
labgrid/strategy/ubootstrategy.py

The system might not be in operational state once the login prompt is shown. Try to wait until the system is up and running for systemd-based systems. Use run() instead of run_check() for non-systemd based systems or if degraded/maintenance/stopping system states are reached.
This covers wider use-cases for the shipped strategies.
**Checklist**
- [.] PR has been tested

strategy: wait for systemd operational state in shell states

---

CHANGES.rst
labgrid/pytestplugin/hooks.py
tests/test_flags.py

pytest allows setting markers via function decorators [1], class decorators [2] and "pytestmark" global to mark whole modules [2]. Additionally, each of these variants can specify multiple markers.
labgrid's pytest plugin considered only the closest marker. Change that to allow combinations of multiple markers.
This allows use cases like:
```
import pytest
pytestmark = pytest.mark.lg_feature("watchdog")
@pytest.mark.lg_feature("barebox")
def test_watchdog_barebox(barebox):
..
```
Tests in this module are only run if the feature flag "watchdog" is available. The specific test "test_watchdog_barebox" is only run if the feature flag "barebox" is available additionally.
[1] https://docs.pytest.org/en/latest/example/markers.html#adding-a-custom-marker-from-a-plugin
[2] …

combine multiple lg_feature markers instead of considering only closest one

---

CHANGES.rst
labgrid/remote/client.py

Sometimes a remote place might have multiple NetworkService resources,
for example a single device running multiple operating systems.  In this
case, we must specify which NetworkService resource to use for the local
SSHDriver instance.
Signed-off-by: Thomas Preston <thomas.preston@codethink.co.uk>
Testing:
```
(labgrid-venv) $ labgrid-client ssh --help
usage: labgrid-client ssh [-h] [name]
positional arguments:
name        optional resource name
optional arguments:
-h, --help  show this help message and exit
(labgrid-venv) $ labgrid-client -p codethink-office-guest-gw ssh guest-os-network
guest-os#
(labgrid-venv) $ labgrid-client -p codethink-office-guest-gw ssh host-os-network
host-os# 
```
**Checklist**
- N/A Tests for the feature (I don't think there are labgrid-client tests, and also …

client: Add named resource arg to SSH subparser

---

labgrid/__init__.py

When using labgrid as a library, instanciating the `ConsoleLoggingReporter` to retrieve console log is a common case.
Allow `from labgrid import ConsoleLoggingReporter`, similar to the `StepReporter`.
**Checklist**

__init__: add ConsoleLoggingReporter

---

doc/configuration.rst
labgrid/driver/usbvideodriver.py

Adds support for another USB camera model and updates documentation a bit.
**Checklist**

Add Support for "HD 2MP WEBCAM" to USBVideoDriver

---

labgrid/target.py

Having this message at info() level means it shows up on stdout when a
resource disappears during a test. This is unnecessary as any driver
using the resource will fail when an attempt is made to use it.
**Checklist**

target: Quieten message when resource is unavailable

---

CHANGES.rst
dev-requirements.txt
kasa-requirements.txt
labgrid/driver/power/tplink.py
tests/test_powerdriver.py

Implemented using the python-kasa library. This driver functions in the same way as other network power drivers, e.g.  eaton
Tested on a KP303 power strip.
Signed-off-by: kiran ostrolenk <kiran.ostrolenk@codethink.co.uk>
**Checklist**

driver/power: add network power driver for TP-Link power strips

---

labgrid/util/expect.py

Fix a typo, improve the sentence and remove unneeded newlines. The
newlines seem to be leftover from a previous state.
Fixes: 5204c4a0 update sphinx to 1.8.1
Fixes: 56d5947a configure and run yapf
Signed-off-by: Sebastian Fricke <sebastian.fricke@posteo.net>

util/expect: Improve __init__ method for wrapper

---

pyproject.toml

Using pyproject.toml to specify build system requirements is now the
preferred way. From the setuptools documentation[1]:
"This used to be accomplished with the setup_requires keyword but is now
considered deprecated in favor of the PEP 517 style described above."
I didn't remove the 'setup_requires' from setup.py because some users
who are using older versions of setuptools might still rely on it if
their version of setuptools has no support for pyproject.toml.
Without this pyproject.toml, the following command fails on a local
network without internet access:
[edit: correct command as explained below in the comments]
`pip install --index-url <local index> -e .`
because setuptools does not take the index into account when fetching
the 'setup_requires' dependencies defined in setup.py. …

pyproject.toml: specify build-system requirements

---

CHANGES.rst
dev-requirements.txt
doc/configuration.rst
doc/getting_started.rst
examples/modbusrtu/conftest.py
examples/modbusrtu/env.yaml
examples/modbusrtu/test_modbusrtu_example.py
labgrid/driver/__init__.py
labgrid/driver/modbusrtudriver.py
labgrid/resource/__init__.py
labgrid/resource/modbusrtu.py
modbusrtu-requirements.txt
tests/test_modbusrtudriver.py

Added a Modbus RTU driver to allow for labgrid tests to control modbus devices.
**Checklist**

driver: add modbus rtu driver

---

CHANGES.rst
README.rst
doc/configuration.rst
doc/development.rst
doc/getting_started.rst
doc/overview.rst
doc/usage.rst
examples/usbpower/examplestrategy.py
labgrid/driver/bareboxdriver.py
labgrid/driver/ubootdriver.py
labgrid/protocol/commandprotocol.py
labgrid/protocol/infoprotocol.py
labgrid/resource/serialport.py
labgrid/resource/sigrok.py
labgrid/resource/udev.py
labgrid/resource/xenamanager.py
labgrid/strategy/bareboxstrategy.py
labgrid/strategy/graphstrategy.py
labgrid/strategy/ubootstrategy.py
labgrid/target.py
man/labgrid-device-config.5
man/labgrid-device-config.rst

- fixed typos in comments, doc strings, CHANGES.rst and docs
- fixed docs of Sigrok resources, AndroidFastbootDriver, FlashromDriver, ModbusRTU, DeditecRelais8, HIDRelay, SerialPortDigitalOutputDriver, FlashScriptDriver
- fix example code in docs, add missing imports (all non-pseudo-code examples should actually work now)
- fix example configurations (all non-pseudo-code configurations should actually work now)
- add "Arguments:" sections to resources, indent resource arguments
- add documentation of missing power backends
- add documentation of SysfsGPIO arguments
- example code simplifications
- document pytest plugin's `--lg-initial-state`
No functional changes intended.
**Checklist**

Documentation fixes and improvements

---

labgrid/driver/__init__.py

It should be possible to specify the DeditecRelaisDriver and USBTMCDriver in a labgrid environment config. Allow that.
**Checklist**

driver: import missing drivers in __init__.py

---

doc/development.rst
labgrid/util/managedfile.py

Since coreutils 8.31, the file creation time is supported:
> stat now prints file creation time when supported by the file system, on GNU Linux systems with glibc >= 2.28 and kernel >= 4.11. [1]
labgrid checks the file creation (birth) time locally and remotely. Prior to this change in coreutils' stat, this timestamp was always "0". Since this change, the actual creation timestamp is displayed on the local filesystem. Via NFS, however, the creation timestamp is not transferred.
This means that on recent kernels and coreutils versions, stat's output locally and remotely differ, although the file is actually the same. This results in an unneeded transfer of the file.
In order to fix this, drop the creation (birth) time from the stat call in labgrid altogether.
[1] …

util/managedfile: do not check file creation time in NFS check

---

tests/test_docker.py

This exception is raised when the docker socket is not available.
**Checklist**

tests/test_docker: handle docker.errors.DockerException

---

labgrid/driver/lxaiobusdriver.py
labgrid/resource/lxaiobus.py
labgrid/resource/udev.py

Although the parts of labgrid which need `requests` and `pyudev` are not used by `labgrid-client`, they are still loaded every time and cause a significant startup overhead. This is especially noticeable on smaller ARM systems.
**Checklist**

use deferred imports for requests and pyudev

---

debian/copyright
doc/conf.py
man/labgrid-suggest.1
man/labgrid-suggest.rst

labgrid is in active development, so extend the copyright period to reflect that.
**Checklist**

debian/doc/man: extend copyright period to 2022

---

.github/workflows/unit-tests.yml
doc/conf.py
doc/configuration.rst
doc/development.rst
doc/getting_started.rst
doc/overview.rst
doc/usage.rst

In the past, a lot of code snippets in the documentation did not work (see #877). Use [sphinx' doctest extension](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html) to test code snippets and configurations where feasible.
While at it, fix the documentation of the docker strategy.
**Checklist**
Fixes #301

doc: test code/config snippets in docs

---

CHANGES.rst
doc/configuration.rst
labgrid/driver/power/eg_pms2_network.py
tests/test_powerdriver.py

This driver adds support for the Energenie PMS2 LAN & WLAN programmable
power sockets. They are accessed over a web interface and require a
login before accessing the status of the socket or switching them on or off.
A password is required for the login in POST request and this driver
deliberately uses the default password, as the current state of labgrid
doesn't support password encryption, meaning the password would be
stored in plain text.
Signed-off-by: Sebastian Fricke <sebastian.fricke@posteo.net>
Small note about passwords:
From my discussion in this [issue](https://github.com/labgrid-project/labgrid/issues/794) I have gotten the notion, that security in labgrid is performed on the network level, therefore I have decided to keep this module as simple as possible by demanding the …

driver/power: Add backend driver for EG PMS2 LAN/WLAN

---

doc/index.rst

The introduction in the docs is similar to the README. The README has been updated in a previous commit (#884), but the docs were not updated accordingly. Do that now.

doc: index: apply README changes

---

labgrid/driver/shelldriver.py

lrzsz also provides the `rx` command, and it will output the same banner
to stderr as the `lrz` command. Suppress stderr to handle this case
**Checklist**

shelldriver: Redirect rx stderr to /dev/null

---

labgrid/remote/client.py

Since 361a7f7 ("client: Add named resource arg to SSH subparser"), a
"name" argument is required for all SSH operations, but it was omitted
from the `scp`, `rsync`, `sshfs`, and `forward` subcommands.
**Checklist**

client: Add missing name argument

---

examples/strategy/test_barebox_strategy.py
examples/strategy/test_uboot_strategy.py
examples/usbpower/test_example.py

Since 5d9e76ad888c (pytestplugin: add a --lg-initial-state= option to use
during development), labgrid provides a strategy fixture which matches on the
abstract Strategy class. Accordingly, these custom fixtures are no longer
needed and currently break use of --lg-initial-state=.
**Checklist**

examples: remove custom strategy fixtures

---

labgrid/strategy/bareboxstrategy.py

This adds support for `--lg-initial-state=barebox/shell` when using the pytest
plugin.
**Checklist**

strategy/bareboxstrategy: add force function

---

doc/configuration.rst
labgrid/resource/modbusrtu.py

Collection of fixes for the configuration section of the documentation fixing/improving the resource/driver arguments (drop inexistent argument, fix wrong types, use generic default notation). Stumbled upon those while looking up arguments for a resource.

Minor Configuration Documentation Fixes/Improvements

---

CHANGES.rst
labgrid/remote/client.py
labgrid/remote/coordinator.py
man/labgrid-client.1
man/labgrid-client.rst
tests/test_crossbar.py

Adds coordinator and client API to release a place, but *only* if it is
acquired by a specific user in an atomic manner.
The intention is that this can be used by cleanup procedures to ensure
that there is not a race condition between figuring out which user has a
resource locked, and actually kicking that user. For example, some CI
systems may leave a place locked if they don't get a chance to cleanup
properly. A cleanup procedure might cross reference the user that has a
place locked with a list of active CI jobs, and if a user is found
that doesn't match any running CI job, the place it has acquired is
released. This presents a race however if this procedure is occuring in
multiple places simultaneously, as it's possible one of them releases
the place, then it gets acquired by an …

Add release-from

---

dockerfiles/Dockerfile

GitHub disabled support for the git protocol [1]. Use https instead.
Fixes:
> Cloning into 'opt/wait-for-it'...
> fatal: remote error:
>   The unauthenticated git protocol on port 9418 is no longer supported.
[1] https://github.blog/2021-09-01-improving-git-protocol-security-github/

dockerfiles: use https instead of git protocol

---

crossbar-requirements.txt

crossbar <= v22.3.1 and werkzeug v2.1.0 are not compatible. werkzeug deprecated `werkzeug.utils.escape` in v2.0.0 [1] and removed it in v2.1.0 [2]. crossbar still uses it, though:
```
File "/opt/hostedtoolcache/Python/3.10.2/x64/bin/crossbar", line 8, in <module>
sys.exit(run())
File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/crossbar/__init__.py", line 175, in run
_personalities = personalities()
File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/crossbar/__init__.py", line 213, in personalities
from crossbar import personality as standalone
File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/crossbar/personality.py", line 47, in <module>
from crossbar.webservice …
```

crossbar-requirements: do not install werkzeug>=2.1

---

CHANGES.rst
doc/configuration.rst
labgrid/driver/modbusdriver.py
labgrid/resource/modbus.py

[Quido ETH](https://en.papouch.com/io-modules/quido/ethernet/) is a family of I/O modules with up to 32 digital outputs (relays) and ethernet interface which makes them quite nice devices for DUT power control.
In order to control the state of the relay outputs, firmware needs to be instructed using Modbus function code 15, multiple coils write method as single coil write method is not supported, only single coil state reading is. Write using single method ends with `Could not write coil (code=7/exception=1)` error.
So in order to support those modules, new `write_multiple` boolean config option has been added to `ModbusTCPCoil` resource. When enabled, the Modbus driver is going to use `write_multiple_coils()` method instead of defaul `write_single_coil()`.
Example usage …

modbus: add support for Papouch Quido ETH I/O modules

---

tests/conftest.py

Lets you run the test suite without havin the labgrid-exporter installed in $PATH.

tests: Enable labgrid-exporter without the executable

---

labgrid/remote/client.py

If twisted is installed, txaio must be configured before importing autobahn.
Otherwise we get an error:
RuntimeError: To use txaio, you must first select a framework with
.use_twisted() or .use_asyncio()

remote/client: configure txaio earlier

---

labgrid/resource/mqtt.py

The mqtt availability payload is really device-specific; Tasmota uses `Online` and `Offline`, whereas ESPHome uses `online` and `offline`. Let's make MQTTManager a little bit more device-agnostic and allow both cases to satisfy the criteria.
Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>
---
This is the minimum change required to support ESPhome firmware as a `TasmotaPowerPort`. I think it makes sense to change the availability payload detection where I have done it.
PS: Let me know if also like to have a separate driver called `ESPHomePowerPort` or similar, I can do a separate commit on top

mqtt: Make availability payload more generic

---

labgrid/remote/exporter.py

ser2net allows multiple, multiplexed connections.  Enable by default
with a max of 10.
RFC: this should probably be an optional feature, with the number a parameter, but this is just to show how it can be done.
Signed-off-by: Kevin Hilman <khilman@baylibre.com>

remote/exporter: enable multiple ser2net connections

---

CHANGES.rst
labgrid/resource/udev.py

Udev matching by ATTR(S){} does currently not work on my machine.
I found the issue because I have a 4-port usb-to-serial device where I can only determine the ports by looking at the attributes. 
This is also the device I used for testing locally.
After some search I found that pyudev internally stores attributes as bytes, not strings.
To compare them with the expectation when doing udev matching, they need to be encoded.
Luckily, pyudev already has a function for that, just without a default value. 
**Checklist**

Fix Udev Attribute matching

---

doc/configuration.rst

Add the AndroidFastboot arguments `usb_vendor_id` and `usb_product_id` to the docs.
**Checklist**
Fixes #923

doc: configuration: add missing AndroidFastboot arguments

---

CHANGES.rst
labgrid/driver/smallubootdriver.py

By default SmallUBootDriver sends `boot_secret` terminated with new
line, which works fine on multitude of devices, but fails for example on
quite popular ralink/mt7621 based Ubiquiti ER-X devices, where
bootloader offers following boot menu:
Please choose the operation:
1: Load system code to SDRAM via TFTP.
2: Load system code then write to Flash via TFTP.
3: Boot system code via Flash (default).
4: Entr boot command line interface.
7: Load Boot Loader code then write to Flash via Serial.
9: Load Boot Loader code then write to Flash via TFTP.
r: Start TFTP recovery.
and expects only single character choice, otherwise uses default choice
3, but in order to control such DUTs we need to enter boot prompt by
selecting choice 4. and thus sending `4` verbatim, without new …

smallubootdriver: allow sending of boot_secret without new line

---

CHANGES.rst
labgrid/remote/client.py
labgrid/remote/common.py
tests/test_crossbar.py

Do not add matches without a name in their resource path that already exist with a name (and vice versa).
**Checklist**
Fixes #888

Check for duplicate matches on add-match/add-named-match

---

labgrid/driver/usbvideodriver.py
labgrid/resource/udev.py

This
- adds support for two additional webcam models
- fixes up the USBVideoDevice resource to export the correct video device for webcams that have multiple device nodes
- adds a generic fallback pipeline so many webcams are usable without having to adapt labgrid. The parameters are what I found in common in the `gst-device-monitor-1.0` output for both added webcams and my laptops internal webcam.
- a commit that i deem optional. It produces a verbose warning when using the fallback pipeline. I dislike the string indentation mess it leaves in the source code, but the error message looks as intended:
```
WARNING: Unkown USB video device 1224:2825, using fallback pipeline. This might not
work as expected.
Consider adding support for your camera model to labgrid as described here: …
```

Add support for more webcams and a generic fallback pipeline

---

README.rst
doc/RELEASE.rst
doc/development.rst
doc/getting_started.rst

Extend Documentation to update pip when creating a new virtualenv. The dependency resolver of older pip versions (at least until 2.0.2, as shipped with Ubuntu 20.04) is not able to install the current set of required versions. 
Fixes #919

Add instructions to update pip when setting up a virtualenv for labgrid

---

CHANGES.rst
doc/configuration.rst
labgrid/remote/config.py
labgrid/remote/exporter.py

Previously you could only use os.environ in your resource config templates. Add exporter name, hostname and isolation status to the mix. This allows you to e.g. export network resources on the host this exporter is running on:
dut_power:
NetworkPowerPort:
model: rest
host: 'http://{{ hostname }}/dut/enable'
index: '0'
**Checklist**
I did not find a suitable existing test to extend and don't really have the appropriate project knowledge to add a completely new one.
I've used it to construct an URL containing the hostname, as show above.

remote/config: Add more templating variables, like the hostname and exporter name

---

labgrid/driver/consoleexpectmixin.py
labgrid/driver/externalconsoledriver.py
labgrid/driver/serialdriver.py
tests/test_externalconsoledriver.py
tests/test_serialdriver.py

Extend read function of serialdriver and externalconsoledriver with 'max_size' argument that limits the number of read bytes to 'max_size'. Set 'size' = 'max_size' to read exactly 'size' bytes. The values 'None' and '0' result in an unlimited read.
Extend 'test_read' in test_serialdriver.py and test_externalconsoledriver.py  to check 'max_size' argument.
Implement 'max_size' explicitely in consoleexpectmixin.
- We use the feature to read a fixed number of bytes on the serial port during testing the serial communication. The current read function returns the full buffer of the serial port (maximum of size and in_waiting). We use labgrid to test embedded software on hardware devices.
- We think that for certain tests it can be useful to read a well defined and fixed size from the serial …

Add max_size option to ConsoleExpectMixin read

---

labgrid/remote/client.py
labgrid/util/timeout.py

`labgrid-client console --loop` should keep trying to connect to the console even if the serial port is currently unvailable.
The console method is declared async because it needs to handle crossbar communication with the coordinator concurrently, see [1] (e.g. place kicks, resouces becoming available).
Until now it only tries again if microcom comes back with a return code != 0. But in case the resource is unavailable, labgrid bails out early because `target.get_resource()` raises a `NoResourceFoundError`.
Calling `target.get_resource()` waits until the resources are available by default. This is done in a blocking `poll()`/`time.sleep()` loop until a timeout is reached allowing no crossbar communication in the meantime. This again means changes in resource availability …

remote/client: no block in async console, loop even on unavailable resource

---

man/labgrid-client.1
man/labgrid-client.rst
man/labgrid-exporter.1
man/labgrid-exporter.rst

- fix long crossbar option for `labgrid-client`/`labgrid-exporter`
- add missing `labgrid-client` subcommands
**Checklist**
Fixes: #28

man: fix crossbar option, add missing subcommands

---

labgrid/remote/coordinator.py
labgrid/util/yaml.py

Using `yaml.load()` without specifying a loader has been deprecated since 5.1. As such this series changes `remote/coordinator` to make use of the custom yaml loader/dumper within `util/yaml`, which ultimately results in use of the SafeLoader and the SafeDumper. Previously however the coordinator will have `yaml.dump`ed tuples with the `python/tuple` tag, which the SafeLoader will not load, in order to not break any existing deployments on upgrade this series also adds the tuple constructor to the custom loader.
Additionally does a little miscellaneous tidying within `util/yaml`, including changing `dump()` to take kwargs.
I've tested this series against a local deployment of a labgrid coordinator and exporter.
**Checklist**

remote/coordinator: switch to using the custom yaml loader/dumper

---

CHANGES.rst
doc/configuration.rst
labgrid/driver/__init__.py
labgrid/driver/dfudriver.py
labgrid/remote/client.py
labgrid/remote/exporter.py
labgrid/resource/remote.py
labgrid/resource/suggest.py
labgrid/resource/udev.py
man/labgrid-client.1
man/labgrid-client.rst

Add a resource, driver and client sub command to communicate with devices in DFU (Device Firmware Upgrade) mode. labgrid uses the [dfu-util tool](http://dfu-util.sourceforge.net/).
**Checklist**

Introduce DFUDevice, DFUDriver

---

labgrid/driver/qemudriver.py
tests/test_qemudriver.py

#912 introduced the new kwarg `max_size` in `ConsoleExpectMixin` which is passed through to the driver's internal `_read()` method. The `QEMUDriver` was not adjusted accordingly, so do that now.
While at it, add tests for the `QEMUDriver` to prevent such issues in the future.
**Checklist**
Fixes #912

driver/qemudriver: let _read() handle max_size kwarg

---

labgrid/remote/client.py

PR #935 added async waiting for the NetworkSerialPort. This makes `labgrid-client console --loop` work as long as the resource changes from being unavailable to being available. It does not work vice versa, however: the resources are not being updated before being checked for availability. The code inside the while loop does not run in this case.
This makes the subsequent `target.await_resources()` raise a NoResourceFoundError which is not handled anywhere causing an error message and exit of labgrid-client despite being called with ``--loop``.
Fix that by updating the resources before checking the resource's availability. `labgrid-client console --loop` will now loop even if the NetworkSerialPort changes from being available to unavailable.
**Checklist**
Fixes #935
Fixes …

remote/client: update resources before checking NetworkSerialPort availability

---

labgrid/driver/sshdriver.py

The run() function was not passing its timeout parameter on to the
internal _run() function; therefore, any timeout set by a caller was
ignored.
Signed-off-by: Nick Potenski <nick.potenski@garmin.com>
**Checklist**

sshdriver: Fix timeout for run()

---

labgrid/driver/usbvideodriver.py

Add support for the AUKEY PC-LM1E camera
**Checklist**

driver/usbvideodriver: add support for AUKEY PC-LM1E

---

labgrid/driver/qemudriver.py

Make the `q35` machine behave similar to `pc` if a kernel is started directly. Furthermore, the default drive interface has been added. This commit is an addition to `086ba3b3fe1e04bcc8cba0e6dfe558b7747d372d`.
**Checklist**

driver/qemudriver: add drive interface and kernel boot parameters

---

.crossbar/config.yaml
tests/conftest.py

Recording the coordinator's coverage is useful to determine, which parts of the component are executed during tests.
crossbar runs labgrid's coordinator component as a guest worker. Guest workers are spawned as subprocesses by crossbar. Therefore recording coverage of the coordinator component does not work out of the box.
To allow recording coordinator coverage, set the coverage command line tool as the `excutable` in the crossbar configuration, whose 'run' subcommand works as a drop-in replacement for 'python'. This way the coverage of the guest worker is recorded separately. The `--parallel-mode` switch makes coverage add a unique suffix to the coverage data file. Set the location of the coverage data via `--data-file` to the root directory. pytest-cov automatically …

tests: record coordinator's coverage

---

labgrid/driver/qemudriver.py

Since the q35 machine was added, using the vexpress-a9 machine with a disk attribute ends up with a `NotImplementedError`. Fix that.
**Checklist**
Fixes #961

driver/qemudriver: fix disk attribute for vexpress-a9 machine

---

labgrid/resource/suggest.py

We can't really detect if the ports are actually controllable, so we have to
show all hubs. This also means that we can't suggest a specific port index, so
show a placeholder.

resouce/suggest: add basic support for USBPowerPorts

---

labgrid/driver/power/siglent.py

When using the siglent power backend with the NetworkPowerDriver, this error occurs:
```
self = NetworkPowerDriver(target=Target(name='Test', env=None), name='power', state=<BindingState.active: 2>, delay=2.0)
@Driver.check_active
@step()
def off(self):
>       self.backend.power_set(self._host, self._port, self.port.index, False)
E       TypeError: power_set() takes 3 positional arguments but 4 were given
labgrid/driver/powerdriver.py:219: TypeError
```
The siglent backend does not follow the function signatures expected by the NetworkPowerDriver, because it's missing the port parameter. Fix that by adding the port parameter and making sure that it's `None`, just like other backends do (apc, rest, sentry, simplerest, tplink).
Note: I have no Siglent device here to …

driver/power/siglent: use backend function signatures expected by NetworkPowerDriver

---

doc/configuration.rst
doc/overview.rst
labgrid/driver/fastbootdriver.py
labgrid/remote/exporter.py
labgrid/resource/fastboot.py
labgrid/resource/remote.py
labgrid/resource/suggest.py
labgrid/resource/udev.py
tests/test_environment.py

Signed-off-by: Oleg Karfich <oleg.karfich@wago.com>
Extend the currently fastboot implementation in labgrid by supporting fastboot over ethernet.
The extension is tested with an WAGO PFC200 (750-8212) with running Barebox v2021.10.0. We also tested the currently implemented USB functionality in case of some breaking changes. 
**Checklist**

driver: fastbootdriver: support fastboot over network

---

.github/workflows/unit-tests.yml
labgrid/driver/openocddriver.py
tests/test_openocd.py

It seems that OpenOCD no longer accepts (or requires) extra quoting around the
`--command` arguments, so remove it. Also add some simple tests to detect
regressions in this area earlier.
**Checklist**

driver/openocddriver: fix command quoting and add tests

---

labgrid/remote/coordinator.py

Signed-off-by: Larry Shen <larry.shen@nxp.com>
This PR to log `place acquire`/`place release` info in coordinator log, so that admin possible to check who have once used that board when issue happen.

coordinator: record place acquire/release info.

---

labgrid/driver/ubootdriver.py

Update the U-Boot reset method to be equal with the Barebox method.
Signed-off-by: Daniel Schultz <d.schultz@phytec.de>
**Checklist**
Fixes #105

driver/ubootdriver: Fix reset method

---

labgrid/driver/sshdriver.py

This avoids shell interpretation in case the password contains special
characters.

sshdriver: escape password when writing to pass_file

---

labgrid/util/qmp.py

Lines end with '\r\n', so an extra empty line is logged after each QMP line received. Log the representation of the line to get rid of extra lines.
**Checklist**

util/qmp: log representation of line instead of line

---

.github/pull_request_template.md
doc/RELEASE.rst

Experience shows that these tend to introduce merge conflicts. Since we have to dig through the PRs anyway to make sure the release notes are complete when doing a release, we can drop the checkbox altogether.

github/pull_request_template: drop CHANGES.rst update checkbox

---

dev-requirements.txt
setup.cfg

We do not use yapf in our current workflow. To improve code style consistency and reduce discussions about style, we want to switch to [black](https://github.com/psf/black) in a future PR and enforce it via CI step by step.
For now, only drop yapf.

requirements/setup.cfg: drop yapf

---

labgrid/resource/udev.py

Signed-off-by: Marvin Sacher <marvin.sacher@protonmail.com>
Added support for Olimex devices when using resourse USBDebugger.
IDs of following devices are now included:
- ARM-USB-OCD
- ARM-USB-OCD-H
- ARM-USB-TINY
- ARM-USB-TINY-H
IDs are specified in https://www.olimex.com/Products/ARM/JTAG/_resources/ARM-USB-OCD_and_OCD_H_manual.pdf
(page 7 table 2)
**Checklist**
- functionality has been tested on a remote machine with the same exact changes, using Olimex ARM-USB-OCD-H

Added Olimex USBDebugger IDs

---

dockerfiles/Dockerfile

Timeout will occur in some configurations, for example, when the
ConsoleProtocol is used to match on events during a boostrap proccess
and those events are used to determine the when the ShellDriver is
deactivated/activated. This issue is fixed by including `qemu-utils` in
the image.
Signed-off-by: Emil Kronborg Andersen <emil.kronborg@protonmail.com>
I tested this locally using an image that reboots by design. Without `qemu-utils`, the reboot event is not caught by the ConsoleProtocol and the test timeouts. When `qemu-utils` is included, it runs as expected in the container, that is, like it runs when not containerized. 
**Checklist**

dockerfiles: add qemu-utils to labgrid-client

---

labgrid/exceptions.py
labgrid/remote/client.py
labgrid/target.py

When matching multiple resources but not having a name, we raise an unintuitive error about not finding a resource, but don't indicate the available names. Bubble up the found resources and provide a neat list to the user to select from the available names.
**Checklist**

client: show names for multiple matching resources

---

CHANGES.rst
labgrid/util/helper.py
tests/test_powerdriver.py
tests/test_processwrapper.py

Adds an input argument that allows a string to be passed as input to the process, matching subprocess.run().
**Checklist**

processwrapper: Add input argument

---

labgrid/driver/openocddriver.py
labgrid/resource/common.py

Until now drivers simply prepend the command_prefix for commands that should work on local and network resources. For local resources, it is empty, for network resources, it contains `["ssh", .., "<exporter>", "--"]`.
In some cases this is not enough, because the argument separation is lost when the command is run via SSH. This means we need shell escaping, but only for network resources.
So add a `wrap_command()` method to Resource and NetworkResource. For Resources, it simply returns the passed command. For NetworkResources, the `command_prefix` property is prepended and each command component is shell-escaped.
The OpenOCDDriver is affected by this issue: It runs openocd with `--command` passing an argument containing spaces: `adapter usb location ..`. When run with the …

Allow Command Wraping in NetworkResources, Use it in OpenOCDDriver

---

labgrid/util/agentwrapper.py

Allow users to place agent scripts in locations external to the labgrid repository.   The provided `path` should contain the desired script to load named as `{name}.py`.
Signed-off-by: Nick Potenski <nick.potenski@garmin.com>
**Checklist**

agentwrapper: Add path argument to load()

---

labgrid/util/expect.py

Sometimes it's useful to send Ctrl-C to interrupt a process or Ctrl-Z to send a hung process to the background and kill it then (e.g. gst-validate-1.0). This is often faster than transitioning to the off/root state and back to the shell.
Although pexpect.spawn has a sendcontrol() method, it relies on ptyprocess which is not useful for labgrid's usecase. So implement it here.
Note: was originally part of #552.
**Checklist**

util: expect: implement sendcontrol()

---

doc/configuration.rst

Add a note to the ShellDriver docs on how to handle backeted-paste mode.
Closes #969
Closes #975

doc/configuration: add note about bracketed-paste mode

---

doc/configuration.rst
labgrid/driver/sshdriver.py

Allows to configure a connection timeout connection to a target on ssh. 
This is relevant when having a slow booting target.
**Checklist**
Did you test the change locally? If yes, best to mention how you did it in the description section.

driver/sshdriver: add connection timeout option

---

labgrid/driver/sshdriver.py
labgrid/util/ssh.py

Fixes #948
changes the names for the temporary file_paths from 
`labgrid-ssh-tmp-` to `lg-ssh-` 
and
`labgrid-connection-` to `lg-con-`
in order to be compatible with MacOS and its longer tempdir-path

path too long error fix

---

.github/workflows/docker.yml
.github/workflows/unit-tests.yml

Bump GitHub actions used to their latest versions. Fixes various deprecation warnings [1]:
> docker:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
> 
> unit tests:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-python, actions/cache, codecov/codecov-action, actions/cache, actions/setup-python, actions/checkout
See also [2].
Since we do …

github/workflows: bump actions versions

---

doc/configuration.rst
labgrid/driver/networkinterfacedriver.py
labgrid/remote/exporter.py
labgrid/resource/base.py

Until now only USB network interfaces are supported. The NetworkInterface class already exists, but there is no corresponding
resource export.
Change that by adding such a resource export and document the new NetworkInterface resource. Also mention that a RemoteNetworkInterface can either be a remote USBNetworkInterface or a NetworkInterface.
Now allow binding of the NetworkInterfaceDriver against it.
Note: Only tested on REPL by instantiating a NetworkInterface resource and binding a NetworkInterfaceDriver against it
**Checklist**

Add NetworkInterface resource

---

dockerfiles/README.rst
dockerfiles/build.sh

Allow to force usage of podman/docker by environment variable DOCKER. Example
export DOCKER=podman
./dockerfiles/build.sh
. Try to autodetect podman/docker.
Signed-off-by: Alexander Merkle <alexander.merkle@lauterbach.com>

dockerfiles: support podman/docker for build.sh

---

.github/workflows/unit-tests.yml
setup.py

Python 3.11 was released on October 24th [1]. Let's add a test job for it and announce support in the setup.py.
[1] https://blog.python.org/2022/10/python-3110-is-now-available.html
Note: Deprecation warning leading to an error of the Python 3.11 job will be fixed by #1024.

Test/Announce Python 3.11 Support

---

labgrid/driver/externalconsoledriver.py
labgrid/driver/qemudriver.py
labgrid/driver/sshdriver.py
labgrid/driver/usbaudiodriver.py
labgrid/driver/usbvideodriver.py
labgrid/remote/client.py
labgrid/util/agents/network_interface.py
labgrid/util/agentwrapper.py
labgrid/util/ssh.py

Collection of fixes for various ResourceWarnings:
- unclosed files
- unclosed sockets
- unclosed pipes
Found by running labgrid-client and labgrid's pytest plugin in [Python Development Mode](https://docs.python.org/3/library/devmode.html) during day-to-day use as well as the test suite:
```
python3 -X dev -X tracemalloc=50 -m pytest
```
Test suite warnings are down from 90 warnings to 15. Only labgrid module code was touched, warnings in test code were ignored.
**Checklist**
- [.] PR has been tested (not all changes were manually tested)

Fix ResourceWarnings

---

labgrid/driver/powerdriver.py
labgrid/util/proxy.py
tests/test_powerdriver.py

Some power backends (`rest`, `simplerest`) store a full URL in the resource's host parameter. As these backends cannot specify a `PORT` since it can be a flexible part of the URL specified in the exporter, such resources cannot be proxied currently.
As a prerequisite, allow this when requesting a proxy connection for such a resource.
Then add a method to the `NetworkPowerDriver` trying to handle the host parameter as a URL and extract the port from it. Use this port to request the proxy forward for. Finally construct a proxied variant of the host parameter to pass to `on()`, `off()` and `get()`.
This allows to use power backends such as `rest` and `simplerest` to be proxied.
Tested with a remote [LXA Test Automation …

Allow proxying of dynamic port power backends with URL in host parameter

---

labgrid/factory.py
tests/test_factory.py

`normalize_config()` and `make_target()` modify the referenced dicts returned by `_convert_to_named_list()`, meaning they modify the config in case resources or drivers are dictionaries, not lists:
```yaml
resources: # or drivers
FooPort: {}
BarPort:
name: "bar"
```
For the list case, copies of the relevant items are already used.
The modification happens when popping `name`, `cls` and `bindings` from the arguments.
This can be observed with an env.yaml containing a RemotePlace resource having a `name` argument:
```yaml
targets:
main:
resources:
RemotePlace:
name: myplace
```
Now we pass this environment config to labgrid-client:
```
$ labgrid-client --debug --config env.yaml console
Selected role main and place myplace from configuration file
DEBUG: expanded remote …
```

factory: pass copy of driver/resource args to avoid modifying config in place

---

labgrid/driver/sshdriver.py

`stdout` is still a bytestring at this point, so we have to also use a bytestring as delimiter.
Fixes: e874ae62 ("driver: close pipes from processes explicitly")
**Checklist**
Fixes #1018

driver/sshdriver: fix splitting bytestring on SSH master error

---

.github/workflows/unit-tests.yml
dockerfiles/staging/docker-compose.yml

The docker-compose steps in the unit-tests workflow tend to run into errors once in a while, e.g. [here](https://github.com/labgrid-project/labgrid/actions/runs/3336552208/jobs/5521844726).
If something goes wrong during coordinator/exporter startup, no resources are exported. That leads to an infinite loop while waiting for resources with `labgrid-client r`. The job is then killed by GitHub Actions after 6 hours.
Add a timeout to prevent such situations. This also allows gathering logs from the services in a future commit.
In case of an error during 'docker-compose up', fetch logs with timestamps from all services. This allows us to tell at least how the services failed post-mortem.

add timeout to docker-compose client, gather logs on error

---

requirements.txt

twisted 22.10.0 [1] (released on 2022-10-30) uses attrs imports such as..
```
from attrs import something
```
The new import ("attrs", not "attr") is supported since attrs 21.3.0 [2]. labgrid currently pins attrs to 21.2.0. This incompatibility causes issues such as..
```
File "/opt/hostedtoolcache/Python/3.11.0/x64/bin/crossbar", line 8, in <module>
sys.exit(run())
^^^^^
File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/crossbar/__init__.py", line 143, in run
from autobahn.twisted import install_reactor
File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/autobahn/twisted/__init__.py", line 40, in <module>
from autobahn.twisted.websocket import \
File …
```

requirements: bump attrs 21.2.0 -> 21.3.0

---

requirements.txt

attrs 21.3.0 is breaking code coverage [1].
To fix this, bump attrs to 21.4.0.
[1] https://github.com/python-attrs/attrs/issues/895
**Checklist**
See #1029

requirements: bump attrs 21.3.0 -> 21.4.0

---

labgrid/remote/client.py

The command
```
labgrid-client tmc
```
showed the help of last subparser (=export). Now it shows the help of TMC including all subcommands.
Signed-off-by: Alexander Merkle <alexander.merkle@lauterbach.com>
**Checklist**

client: fix help parser of labgrid-client tmc

---

debian/labgrid-client
debian/labgrid-exporter
debian/labgrid-pytest
debian/labgrid-suggest
debian/labgrid.install

These two patches unify option passing for the already existing wrappers of some labgrid commands and add a new wrapper for `labgrid-suggest`.

Labgrid wrappers

---

CHANGES.rst
labgrid/driver/common.py
labgrid/driver/networkinterfacedriver.py
labgrid/driver/sshdriver.py
labgrid/target.py
labgrid/util/agentwrapper.py
labgrid/util/ssh.py
tests/test_util.py

When using a RemoteNetworkInterface, it is useful to open connections from the
exporter to the DUT. We can make that easy by using the sshmanager we already
have for managing access to the exporter.
Also fix some minor issues on the way.
**Checklist**

add port-forwarding helpers on the NetworkInterfaceDriver

---

contrib/coordinator-statsd.py

Adds a script that periodically scrapes place and reservation metrics from the coordinator and reports them to a statsd server
**Checklist**

contrib: Add script to scrape statsd metrics from coordinator

---

doc/configuration.rst
labgrid/driver/power/gude8225.py

This patch adds support for Gude Expert Power Control 8225 using the HTTP-GET API defined at wiki.gude.info/EPC_HTTP_Interface .
Signed-off-by: Alexander Merkle <alexander.merkle@lauterbach.com>
**Checklist**

driver/power: add support for Gude Expert Power Control 8225

---

labgrid/driver/sshdriver.py

The control file needs the "%" escaped when cleaning up like all the other places it is passed to SSH
**Checklist**

sshdriver: Escape control path on cleanup

---

CHANGES.rst
labgrid/driver/sshdriver.py
labgrid/util/agentwrapper.py
labgrid/util/ssh.py
man/labgrid-client.1
man/labgrid-client.rst

Adds an environment variable called LG_SSH_CONNECT_TIMEOUT  which
controls the timeout passed to SSH when attempting a connection.
**Checklist**

Add LG_SSH_CONNECT_TIMEOUT environment variable

---

labgrid/config.py

An empty file is valid yaml, so no exception is raised by the yaml module. labgrid later relies on parsed config data to be either a list or a dict, so check for an empty config early and raise a proper exception instead of cryptic exceptions being raised later.
**Checklist**

config: raise proper exception on empty config

---

debian/copyright
doc/conf.py
man/labgrid-device-config.5
man/labgrid-device-config.rst
man/labgrid-exporter.1
man/labgrid-exporter.rst
man/labgrid-pytest.7
man/labgrid-pytest.rst
man/labgrid-suggest.1
man/labgrid-suggest.rst

labgrid is under active development, so extend the copyright period to reflect that.
**Checklist**

debian/doc/man: extend copyright period to 2023

---

contrib/completion/labgrid-client.bash
debian/control
debian/labgrid.install
labgrid/remote/client.py

Add bash completion for `labgrid-client` including completion for:
- top level longopts
- all sub commands including their longopts and arguments
- files and directories
- places
- available resources
- exporters
- known hosts and users (`allow` and `release-from`)
- place's matches
- place's match names (set via `add-named-match`)
Note: `_labgrid_complete()` and `_labgrid_complete_exporters()` call `labgrid-client complete`. These completions are not as responsive as the rest due to client/coordinator interaction.
**Checklist**

contrib: add labgrid-client bash completion

---

contrib/completion/labgrid-client.bash

When labgrid-client is called via an alias like `alias lgc=labgrid-client` completion can still be enabled via:
```bash
_completion_loader labgrid-client
complete -F _labgrid_client lgc
```
In this case `${base_cmd[0]}` is "lgc". Since `base_cmd` is called for completing places/resources/matches via the complete sub command, this does not work, because "lgc" is undefined in the script's scope.
Allow this case by resolving aliases via `$BASH_ALIASES`.
While at it, use spaces consistently in the completion script.
**Checklist**

contrib/completion: try to resolve bash aliases

---

labgrid/remote/exporter.py

In case an exception is raised during procedure registration, the default exception handler logs it and the event loop carries on. That means when the exporter tries to join and it fails to register, the exporter process simply hangs.
Move the register calls inside the try..except block which already handles printing the exception and stopping the loop. This way the process stops and it can be restarted (e.g. by systemd).
**Checklist**

remote/exporter: stop event loop when register calls fail

---

pyproject.toml

The explicit six dependency with minimum version was introduced back in a540ab7a. Since we do not support Python 3.5 anymore and moved to a newer crossbar version long ago, let's drop this explicit dependency.
labgrid has no direct dependency on werkzeug. The dependency was introduced in 8c171014 to allow successful installation of crossbar 21.3.1. So move it to the crossbar dependencies for now. Once we can loosen the
dependency versions, we can drop this altogether (see #1042 for a first step towards this goal).
**Checklist**

pyproject.toml: drop six, move werkzeug to crossbar extras

---

.github/workflows/push-pr-unit-tests.yml
.github/workflows/reusable-unit-tests-docker.yml
.github/workflows/reusable-unit-tests.yml
.github/workflows/scheduled-unit-tests.yml

Test results may vary due to new dependency versions. Daily CI runs should help us find issues early.
This becomes especially important once all of labgrid's dependencies get unpinned.
**Checklist**

CI: add scheduled tests

---

.github/workflows/build-and-release.yml
.github/workflows/push-pr-unit-tests.yml

Add a build and release workflow which runs after successful tests and if a Tag was pushed.
Depends on #1045

Github Release workflow

---

CHANGES.rst
README.rst

The current major/minor versions don't really follow the semver concept, so sidestep the issue by moving to calendar based versioning.

change to calver versioning

---

.crossbar/config-anonymous.yaml
doc/getting_started.rst
dockerfiles/Dockerfile
dockerfiles/staging/docker-compose.yml
examples/usbpower/README.rst
labgrid/remote/authenticator.py
labgrid/remote/client.py
labgrid/remote/coordinator.py
labgrid/remote/exporter.py
tests/conftest.py

labgrid performs dynamic clear text challenge authentication with unchecked dummy tickets [1]. Add the anonymous static authentication method [2] and deprecate the previous one.
The only change required apart from the crossbar config is the location of the authid. Previously we could set the authid on `ApplicationSession.join()`, but with anonymous static authentication the authid is generated randomly. Since we still need a way to distinguish coordinator, exporter and client, add labgrid's authid to `authextra` [3]:
> All authenticators can return `authextra` auxiliary information that is returned both to the authenticating client, as well as clients which get disclosed the identity of a calling/publishing peer, as well as in the meta API when querying a session.
Dropping …

Introduce anonymous static authentication, deprecate dynamic ticket authentication

---

contrib/completion/labgrid-client.bash
labgrid/remote/client.py

Expose microcom --listenonly feature via labgrid-client console.
This enables a user to monitor a devices serial output without the risk of client modifying it.
Useful for multiple concurrent console invocations of same port.
Future amendments to this listenonly feature could enable the usecase of monitoring a console of a place locked by a different user.
**Checklist**
Since this is a new client CLI option, I believe the argparse library handles documentation / help
I didn't see any existing tests for basic labgrid-client features.  Can add if necessary

client: console support for --listenonly option with microcom

---

.github/workflows/build-and-release.yml
.github/workflows/push-pr-unit-tests.yml
pyproject.toml

Adjust the build and release workflow to work:
- upload to testpypi if it is not a tag, to ensure the release pipeline works
- set an explicit python version
- inherit secrets from the main run so API tokens can be accessed in the build and release job.
- remove local versioning for `setuptools_scm`

Actions: build and release fixes

---

.github/workflows/build-and-release.yml

Set the fetch-depth to 0 for the build and release workflow. This way we should have the complete tag history of the branch, which should allow setuptools_scm to calculate the correct wanted release name for the testpypi upload.

actions: set fetch-depth for build and release

---

.crossbar/config.yaml
dockerfiles/Dockerfile
dockerfiles/staging/docker-compose.yml

Updating the docker containers breaks backwards compatibility with older clients. Revert back to ticket authentication.

dockerfiles: revert to previous authentication

---

dockerfiles/build.sh

This is just a small improvement to make the `build.sh` script for building Docker containers a bit more robust. I was confused by the fact that I couldn't execute it from its directory.

dockerfiles: make execution of build.sh independent of cwd

---

pyproject.toml

xenavalkyrie is EOL and pins its dependencies to versions incompatible with latest setuptools [1], so drop it from the dev extra for now (as suggested in [2]).
In the long run, the xenavalkyrie dependency should be dropped altogether. It is currently unclear if Xena support is still needed. This is issue is tracked in [1].
[1] https://github.com/labgrid-project/labgrid/issues/1084
[2] https://github.com/labgrid-project/labgrid/issues/1084#issuecomment-1409864342
**Checklist**

pyproject.toml: remove xena extra from dev extra

---

labgrid/resource/remote.py
tests/test_crossbar.py

While it is recommended to use an Environment config, it should still be possible to instantiate a Target and a RemotePlace without it, e.g.:
```python
import labgrid
target = labgrid.Target("main")
remote_place = labgrid.resource.RemotePlace(target, name="my-place-name")
power = labgrid.driver.powerdriver.NetworkPowerDriver(target, name=None)
target.activate(power)
power.cycle()
```
We already have a fallback for crossbar URL and realm if it's not present in the Environment, so stick to that when no Environment is present at all.
Also add a test for this.
**Checklist**

resource/remote: allow instantiation of RemotePlaces without Environment

---

labgrid/resource/udev.py

Distros which implement the android-udev-rules from github use the adb_user property to indicate that the device is valid for fastboot. Make use of this property for labgrid which removes the need for more hardcoded USB IDs.
**Checklist**
Fixes #1086

resource/udev: allow fastboot with adb_user=yes

---

labgrid/driver/shelldriver.py

Our platform does not support RSA anymore.  
So we need to allow using ed25519 for the keyfile
**Checklist**

Use ed25519 for the SSH keyfile

---

doc/getting_started.rst

The remote infrastructure expects a working SSH setup at least between the machine running the client and the exporter. Add a note to the documentation in the getting started section.

getting_started: add SSH requirement note

---

CHANGES.rst
doc/configuration.rst
labgrid/driver/qemudriver.py

Adds support for configuring the driver to create a display device, which can either be no device, a software framebuffer, or a accelerated GPU (which requires host support)
**Checklist**

qemudriver: Add display support

---

labgrid/remote/client.py

`labgrid-client ssh`/`labgrid-client rsync` pass arguments to the ssh/rsync subprocesses. Add this info to the epilog displayed at the bottom of the help text.
**Checklist**
Fixes #1064

remote/client: note additional args passing for ssh/rsync in help text

---

doc/configuration.rst
labgrid/driver/ubootdriver.py
tests/test_ubootdriver.py

uboot doesn't have pre defined boot sources. The "boot" command takes no parameters.
Add self.boot_commands to hold different boot_command by name.
They can be used with LinuxBootProtocol boot(name)
**Checklist**

U-Boot boot commands Support

---

doc/configuration.rst
labgrid/driver/usbloader.py

The current implementation adds the cmd as last arg. There it is ignored by uuu
tool. It runs in the default mode with just an image.
For CPUs relying on a special build-in run scripts it must be added with
-b before the file argument.
Removed the broken cmd and add script as config option. This way 
currently working setups should work further.
```
uuu help text (libuuu_1.4.43)
uuu [-d -m -v -V] <bootloader|cmdlists|cmd>
uuu [-d -m -v] -b[run] <emmc|emmc_all|fat_write|nand|qspi|sd|sd_all|spl> arg...
spl	boot spl and uboot
arg0: _flash.bin
```
**Checklist**

labgrid/driver/usbloader: fix uuu command

---

doc/usage.rst

Document `labgrid-client allow`.
**Checklist**

usage: document labgrid-client allow

---

labgrid/util/helper.py
labgrid/util/ssh.py

Switches to using the processwrapper to run the rsync command in put_file. This logs the output to the Python logging instead of stdout, which means it can be better filtered as to where it goes. In particular, it prevents writing output to stdout (unless desired) when capsys is disabled.
**Checklist**

ssh: Use processwrapper for rsync

---

labgrid/driver/usbsdwiredriver.py

The labgrid-client tried to call the get method when using the sd-mux command with and sdwire device.  This should work since the labgrid-client sd-mux command has code to explictly support sdwire devices.
```
(labgrid-venv) Rocinante:labgrid-sandbox jpuderer$ labgrid-client -x ws://labgrid-devhost:20408/ws -c test.yaml sd-mux get 
Selected role main and place test from configuration file
File "/Users/jpuderer/labgrid/labgrid/remote/client.py", line 1787, in main
args.func(session)
File "/Users/jpuderer/labgrid/labgrid/remote/client.py", line 950, in sd_mux
print(drv.get_mode())
^^^^^^^^^^^^
AttributeError: 'USBSDWireDriver' object has no attribute 'get_mode'
```
**Checklist**

Add missing get method to sdwire driver

---

labgrid/target.py
man/labgrid-client.1
man/labgrid-client.rst
tests/test_target.py

If a resource named "default" is found and either none or too many resources passed the name check, return the resource named "default".
This is a slightly simpler approach than #1026 (the other part is covered by #1111) and #1098.
**Checklist**
Closes #1098
Closes #582

target: make get_resource() prioritize resources named "default" on ambiguous results

---

labgrid/driver/powerdriver.py
tests/test_powerdriver.py

Some PDUs URL include username/password and query attributes, and they need to be included in the proxied URL as well.
Include URL based username, password and query attributes on proxied URL (those used when `labgrid-exporter` is started with `-i` option, making all connections go via SHH tunnerl).

driver/powerdriver: Properly reconstruct proxied URL

---

labgrid/target.py
man/labgrid-client.1
man/labgrid-client.rst

The previous comment and check regarding the selection of the resource named "default" in `get_resource()` were phrased/constructed in a confusing way. Fix that.
Also rephrase the man page section about resources named "default".
**Checklist**
Fixes #1112

target/man: rephrase default resource selection

---

contrib/completion/labgrid-client.bash
labgrid/remote/client.py

There might be multiple instances of a resource type in a single place (either specified via resources with names in the configuration or via named matches: `labgrid-client add-named-match`).
This allows addressing them via `-n`/`--name`. If a configuration is given, the drivers specified there will be used if they have the same name as the resource. Otherwise new driver instances will be created.
These sub commands gained the new argument:
- `power`
- `dfu`
- `flashscript`
- `bootstrap`
- `sd-mux`
- `usb-mux`
- `forward`
- `tmc`
- `write-image`
**Checklist**
- [.] PR has been tested (tested power sub command only)
Closes #1026
Closes #1117
Fixes #1023
Fixes #364

remote/client: allow specifying resources by name for various sub commands

---

labgrid/driver/httpvideodriver.py
labgrid/remote/client.py
labgrid/remote/coordinator.py
labgrid/remote/exporter.py
labgrid/resource/ethernetport.py
labgrid/target.py
labgrid/util/agents/network_interface.py

Sending error messages to stderr instead of stdout allows easier output parsing, e.g. for `labgrid-client export`.
Most errors are already sent to stderr, but not everywhere. So direct the remaining errors (and tracebacks) to stderr.
**Checklist**

tree-wide: send error messages to stderr instead of stdout

---

doc/configuration.rst
labgrid/driver/sshdriver.py

Recent versions of OpenSSH allow using the SFTP protocol in favor of the deprecated SCP protocol, and from OpenSSH 9, SCP will use the SFTP protocol by default. Therefore, `put()` and `get()` can now be configured to use SFTP by setting `sftp` to true for `SSHDriver`.
Signed-off-by: Emil Kronborg Andersen <emil.kronborg@protonmail.com>
I tested the change locally using an image that only supports SFTP. Without this change, I am unable to transfer files using `put()` and `get()`. However, applying this change, the methods work as expect.
**Checklist**

drivers/sshdriver: add support for the SFTP protocol for file transfers

---

.github/workflows/reusable-unit-tests.yml

These coverage upload tools are not required any longer: coveralls is not used since 2018 [1], codecov is used via `codecov/codecov-action@v3` [2].
codecov deprecated its previous uploader [3] and removed it from PyPI [4]. This makes labgrid's CI tests fail [5].
So do not install codecov and coveralls any longer.
[1] https://coveralls.io/github/labgrid-project/labgrid
[2] https://github.com/codecov/codecov-action
[3] https://github.com/codecov/codecov-python
[4] https://pypi.org/project/codecov/
[5] https://github.com/labgrid-project/labgrid/actions/runs/4679950048
**Checklist**

github: reusable-unit-tests: do not install codecov/coveralls

---

contrib/completion/labgrid-client.bash
labgrid/remote/client.py
man/labgrid-client.1
man/labgrid-client.rst

This is the equivalent of the pytest plugin's `--lg-initial-state` option. It can be used to specify an initial state the device is known to be in. This is useful during development. The Strategy used must implement the `force()` method.
**Checklist**

Allow setting initial Strategy state in client

---

doc/configuration.rst
labgrid/driver/__init__.py
labgrid/driver/dediprogflashdriver.py
labgrid/resource/__init__.py
labgrid/resource/dediprogflasher.py
man/labgrid-device-config.5
man/labgrid-device-config.rst
tests/test_dediprogflasher.py

Akin to 'flashrom', the Dediprog resource expects 'dpcmd' to be available on the host. Currently, only parameter that can be set is VCC.
The main advantage to use it instead of `flashrom` is that it allows for using images smaller than the SPI memory, which is then automatically filled with `0xff`. For `flashrom`, one needs the image to have the right size - although one can avoid writing the whole of it by having a layout file - which adds to the inconvenience. Using `dpcmd` is more straightforward and faster.
Tested locally using an SF100.
**Checklist**

driver/resource: Support dediprog

---

labgrid/driver/httpvideodriver.py
labgrid/driver/usbaudiodriver.py
labgrid/remote/client.py

Correctly set the exitcode for these subcommands. For this we introduce an InteractiveCommandError, which only sets the exitcode to the one received from the program.
**Checklist**
Fixes #660
Supersedes #662

remote/client: return exit code for ssh/scp/rsync/telnet/video/audio/console

---

labgrid/driver/__init__.py

These drivers should be importable just like the others, so add them.

driver: add missing drivers to __init__.py

---

.github/workflows/push-pr-unit-tests.yml
.github/workflows/scheduled-unit-tests.yml
dockerfiles/Dockerfile
dockerfiles/staging/dut/Dockerfile
pyproject.toml

Python 3.7 will be [EOL on 2023-06-27](https://devguide.python.org/versions/).
This is a preparation for determining labgrid's version (#1125).
> Use of pkg_resources is deprecated in favor of [...] importlib.metadata [...]"
[Source](https://setuptools.pypa.io/en/latest/pkg_resources.html) - see also [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata).
There is also a [backport of this functionality](https://pypi.org/project/importlib-metadata/), but since the EOL date is not too far away, dropping support for Python 3.7 seems to be the easiest way.
Our docker images are still based on Debian buster, but that ships Python 3.7, so bump the base image version to the next stable release "bullseye" and drop building ser2net …

Drop support for Python 3.7, bump docker base image to bullseye

---

labgrid/util/marker.py

The marker can randomly contain some key words. As they show up in the serial logs they may trigger false positive hits while searching.
Remove the character R, I and D to avoid substrings like ERROR, FAIL, WARN, INFO or DEBUG

labgrid: util: marker: use safe marker

---

labgrid/driver/serialdriver.py
pyproject.toml

Switch over to our pyserial fork on pypi and disable the check in the serialdriver.
**Checklist**

Use pyserial fork from pypi

---

labgrid/remote/client.py

When using multiple `NetworkService` resources, `labgrid-client ssh` returns an error even if the binding is set in the environment file:
```
labgrid-client: error: multiple resources matching <class 'labgrid.resource.networkservice.NetworkService'> found in Target(name='essential', env=Environment(config_file='/tmp/boards.yaml'))
Found multiple resources but no name was given, available names:
ip-board
ip-extention
```
resources:
```
slot0:
ip-board:
cls: 'NetworkService'
address: '192.168.0.1'
ip-extention:
cls: 'NetworkService'
address: '192.168.0.11'
```
environment file:
```
drivers:
SSHDriver:
bindings:
networkservice: 'ip-board'
```
The propose change is to first try to get the SSHDriver and if that fails continue with what is currently done.
This makes it possible …

remote/client: ssh command: first look for SSHDriver

---

labgrid/driver/serialdriver.py
pyproject.toml

pyserial 3.2.1 was released more than six years ago, even Debian buster (currently oldstable) contains pyserial 3.4 [1]. It is very unlikely that this is still in use anywhere with a recent labgrid version, especially since we already dropped support for Python 3.7 [2].
This was the only user for the packaging dependency, so drop it.
[1] https://packages.debian.org/source/buster/pyserial
[2] https://github.com/labgrid-project/labgrid/pull/1129
**Checklist**

driver/serialdriver: drop handling of legacy pyserial 3.2.1

---

doc/RELEASE.rst
man/labgrid-client.1
man/labgrid-device-config.5
man/labgrid-exporter.1
pyproject.toml

With #1079, crossbar is no longer installed in the same virtualenv as labgrid and its dependencies. We can now loosen labgrid's dependencies.
Use the known-good previously pinned versions as minimum versions.
We cannot unpin crossbar's version because of continuing issues: [dependencies being incompatible with Python > 3.11](https://github.com/erikrose/parsimonious/issues/225), [PyPI packages depending on non-PyPI packages](https://github.com/crossbario/crossbar/issues/2069) etc.
Based on #1079.
**Checklist**
Closes #1153

Unpin labgrid's dependencies

---

.readthedocs.yaml

Currently, readthedocs uses Python 3.7.9 by default. labgrid dropped Python 3.7 support in #1129. Since this PR was merged, the readthedocs builds fail [1]. This is especially annoying since #1079 was merged afterwards, changing labgrid's setup and its documentation significantly, meaning latest master and the docs hosted on readthedocs differ in incompatible ways. labgrid users already stumbled upon this.
It is not really clear why this Python version is used, though: The docs don't specify a default for build.tools.python [2], the legacy option python.version [3] uses "3" as default, which seems to correlate with the value documented in [2] meaning "last stable CPython version". But 3.7.9 is not the "last stable CPython version".
To fix this, configure all required …

readthedocs: specify Python version and OS

---

doc/conf.py

jQuery is used to expand the menu in the mobile view and for the search functionality. With Sphinx 6.2.1, jQuery is not loaded. The sphinx-rtd-theme docs suggest adding `sphinx_rtd_theme` to `extensions` as a workaround [1]. Do that.
[1] https://sphinx-rtd-theme.readthedocs.io/en/stable/changelog.html#known-issues
**Checklist**

doc/conf: add sphinx_rtd_theme to extensions to fix jQuery loading

---

doc/configuration.rst
labgrid/driver/power/eaton.py
labgrid/driver/power/raritan.py
labgrid/util/snmp.py

Based on the Eaton PDU NetworkPowerDriver implementation, uses PySNMP.
This PR adds `raritan` as a possible PDU NetworkPowerPort model by adding an appropriate NetworkPowerDriver using SNMP via PySNMP.
The feature has been tested on our Raritan PDU. Changing the power state for an outlet via labgrid has worked properly with this change.
Documentation sources for Raritan PDU, i.a. its SNMP protocol OIDs:
* http://support.raritan.com/px3/version-3.0.3/user-guides/PX3-0B-v3.0-E.pdf 
* https://cdn1.raritan.com/download/pdu-g2/4.0.20/MIB_Usage_4.0.20_49038.pdf
* https://www.circitor.fr/Mibs/Html/P/PDU2-MIB.php#switchingOperation
**Checklist**

driver/power: add raritan pdu network power driver

---

.github/workflows/docker.yml

Extend the docker action with tag detection and pushing. This allows users to use the tagged labgrid versions instead of always using the latest version from docker.
**Checklist**

github/workflows/docker: push tags

---

contrib/systemd/labgrid-coordinator.service
contrib/systemd/labgrid-exporter.service

The labgrid exporter needs to talk to the coordinator (crossbar), so start after the network-online.target instead of after the network.target. Also add a weak requirement for that target to make sure it is actually started.
Adding `PYTHONUNBUFFERED=1` [1] to the environment forces the stdout and stderr streams to be unbuffered, so all logs end up in the journal instantly.
Try to read environment variables from `/etc/environment`. This is the place where `LG_CROSSBAR` should be defined. Don't fail if that file does not exist, though.
Soften the restart criteria by using `on-failure` instead of `on-abort`, which covers more failure scenarios, see [2]. The exporter exits with exit code 100 if it loses the connection to the coordinator. While this is already covered by …

contrib/systemd: improve exporter/coordinator services

---

debian/changelog

Updates the debian changelog. This should be done on each release, I've added this as a task to #1168.

debian/changelog: add latest releases

---

contrib/completion/labgrid-client.bash
labgrid/remote/client.py
labgrid/remote/exporter.py
labgrid/util/__init__.py
labgrid/util/version.py
man/labgrid-client.1
man/labgrid-client.rst

This PR allows user to check client version when issue happens, so we possible to know if the issue happens due to old install?
It looks something as next:
```
root@a598f07a4a9e:~# labgrid-client version
0.4.0
```

Add print version subcommand.

---

contrib/systemd/labgrid-exporter.service
doc/getting_started.rst

Some USB TTY use group dailout, while others use plugdev. Allow access to both.
**Checklist**

contrib/systemd/labgrid-exporter: add plugdev to SupplementaryGroups

---

labgrid/driver/sshdriver.py

Cleanup of the temporary directory should not occur until after SSH has
exited, as SSH will delete the control socket which can race with the
shutil.rmtree() and result in strange errors like:
tools/labgrid/venv/lib/python3.10/site-packages/labgrid/environment.py:65: in cleanup
self.targets[target].cleanup()
tools/labgrid/venv/lib/python3.10/site-packages/labgrid/target.py:555: in cleanup
self.deactivate_all_drivers()
tools/labgrid/venv/lib/python3.10/site-packages/labgrid/target.py:505: in deactivate_all_drivers
self.deactivate(drv)
tools/labgrid/venv/lib/python3.10/site-packages/labgrid/target.py:498: in deactivate
client.on_deactivate()
tools/labgrid/venv/lib/python3.10/site-packages/labgrid/driver/sshdriver.py:65: in on_deactivate
self._cleanup_own_master() …

sshdriver: Fix control socket cleanup race

---

labgrid/remote/client.py

`labgrid-client monitor` prints resources as `<exporter>/<group>/<name>`, while the resource match pattern has the format `<exporter>/<group>/<class>/<name>`. The `/<name>` is optional.
So in `labgrid-client monitor`, the class name is missing. This is confusing. Resource match patterns cannot be copy/pasted into `labgrid-client add-match` or `labgrid-client add-named-match`.
Fix that by printing the full resource identifier for the monitor subcommand.
I've checked all code locations in labgrid using resource identifiers, everything else uses the correct notation. This shouldn't break anything.
**Checklist**
Fixes #1177

remote/client: print full resource identifier on monitor

---

labgrid/driver/usbloader.py

The diagnostic output of these tools is often useful for development and debugging.

driver/usbloader: enable print_on_silent_log for subprocess calls

---

labgrid/util/atomic.py

If the temporary file cannot get created..
```
File "labgrid/util/atomic.py", line 6, in atomic_replace
with tempfile.NamedTemporaryFile(
File "/usr/lib/python3.9/tempfile.py", line 680, in NamedTemporaryFile
(fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
File "/usr/lib/python3.9/tempfile.py", line 390, in _mkstemp_inner
fd = _os.open(file, flags, 0o600)
OSError: [Errno 30] Read-only file system: 'tmpgvplm6ok'
```
..the variable `f` is not assigned..
```
During handling of the above exception, another exception occurred:
File "labgrid/remote/coordinator.py", line 292, in poll
await self._poll_step()
File "labgrid/remote/coordinator.py", line 258, in _poll_step
await self.save()
File …
```

util/atomic: fix UnboundLocalError in atomic_replace()

---

dockerfiles/README.rst
dockerfiles/build.sh

This allows for building docker images for different platforms such as linux/arm64 .
I am using this feature because in my case the labgrid coordinator will be executed on a Raspberry Pi 4 in a `docker compose` environment.
**Checklist**

dockerfiles: support for docker buildx

---

labgrid/config.py
labgrid/driver/dfudriver.py
labgrid/driver/fastbootdriver.py
labgrid/driver/lxausbmuxdriver.py
labgrid/driver/openocddriver.py
labgrid/driver/powerdriver.py
labgrid/driver/quartushpsdriver.py
labgrid/driver/usbloader.py
labgrid/driver/usbsdmuxdriver.py
labgrid/driver/usbsdwiredriver.py
tests/test_config.py

The tools in the tools key can either be a single string with the binary
name or a complete path to a binary. This works for every tool expect
for qemu since drivers can provide a fallback to the default tool.
However qemu currently requires the user to supply the full binary path,
which is unintuitive.
Instead return the originally requested tool-name instead if no
specialized path is found. And return the simple unexpanded path if a
local tool with the same name can't be found.
**Checklist**

 config: return passed in tool by default 

---

labgrid/remote/client.py
labgrid/resource/remote.py
tests/conftest.py
tests/test_crossbar.py

Allow using the same resource name across classes.
I tested it in my setup and created a test that fails without this fix.
**Checklist**
- No documentation on this fix
Fixes #1173

Unique resource name per resource class

---

labgrid/binding.py
labgrid/driver/common.py
labgrid/resource/common.py
labgrid/target.py
tests/test_target.py

Implement a new get_bound_resources() function which returns the underlying resources a driver is bound to. This can also be called on Resources, but they will just return themselves in a set.
Add a new keyword argument to get_driver/get_active_driver(), which allows the user to retrieve a driver using a specific resource it's bound to.
**Checklist**

drivers, resource: implement get_bound_resources()

---

labgrid/strategy/ubootstrategy.py

Update the uboot strategy to feature initial state, usable from pytest and labgrid-client.
Unnecessary actions to reach the requested state are not performed.
Tested with labgrid-client in my setup, transitioning:
- from off to uboot with initial state: off
- from uboot to shell with initial state: uboot
**Checklist**
Documentation already present
Manual tests in my setup
No man page impacted, this can serve as an example to implement a strategy with initial state support

ubootstrategy: add support for initial state

---

pyproject.toml

The original author of pysnmp passed away and the lextudio folks took over maintenance [1]. A request to take over the pysnmp PyPi project is pending [2]. Let's move the the maintained fork rather now than later.
While at it, drop the pysnmp-mibs dependency altogether, because this is no longer required for pysnmp>=4.3 [3].
[1] https://github.com/etingof/pysnmp/issues/429
[2] https://github.com/pypi/support/issues/2420
[3] https://github.com/lextudio/pysnmp-mibs/blob/master/README.md
**Checklist**

pyproject.toml: move pysnmp -> pysnmp-lextudio, drop unnecessary pysnmp-mibs

---

labgrid/resource/udev.py

When a udev event is retrieved from the UdevManager's queue, it is matched against each resource. If a match is found, the resource's device is updated (on "add"/"change"/"move" events) or removed (on "unbind"/"remove" events).
Normally the `avail` attribute is set afterwards, but not for the USBSDMuxDevice and USBSDWireDevice: those devices prevent their USBResource super class from setting the `avail` attribute. Instead, the devices are available depending on the availability of their disk and control paths. Then the device's `update()` method is called, which is a no-op for those devices.
On `poll()`, their disk and control paths is set to None if their device is None. Otherwise, these paths are set if the device is not already available.
In case of a USB reset (or fast …

udev/resource: fix mux device race condition leading to outdated control/disk paths

---

labgrid/pytestplugin/hooks.py
tests/test_fixtures.py

Adjust our pytestplugin to handle the case where the logging plugin is disabled.
**Checklist**
Fixes #1209

Fix handling disabled pytest logging plugin

---

labgrid/resource/udev.py

Add SEGGER J-Link debugger support the the USBDebugger resource. Have been tested on a distributed infrastructure by flashing a Nordic nRF52840 board with built in J-Link using the OpenOCDDriver.
**Checklist**

Add SEGGER J-Link vendor and model IDs to USBDebugger resource

---

labgrid/resource/remote.py
tests/test_crossbar.py

Exposes the place tags in the RemotePlace. This allows persistent data to be stored in the tags and retrieved by tests, for example unique MAC address that need to be programmed to a device after flashing
**Checklist**

remote: Expose tags in RemotePlace

---

labgrid/driver/qemudriver.py
tests/test_qemudriver.py

Starting with version 6.1.0, the QEMU command line argument to enable virtio with VirGL support was changed from "-vga virtio" to "-device virtio-vgal-gl". To correctly handle this, scrape the QEMU version number from the command output and use it to pass the correct arguments.
**Checklist**

qemudriver: Handle Virtio GL change in 6.1.0

---

doc/configuration.rst
labgrid/driver/powerdriver.py
labgrid/remote/client.py
labgrid/remote/exporter.py
labgrid/resource/__init__.py
labgrid/resource/ykushpowerport.py

Currently, ykush devices can only be controlled 'locally'. This PR adds support to control them on remote devices. It is based on the seemingly abandoned https://github.com/labgrid-project/labgrid/pull/953 - I basically updated it with the comments there plus a minor fix - first patch, that could go on a different PR if deemed best.
Note that I also removed the 'Export' class created because I'm still figuring out its need - and the commentary for it. If it's deemed necessary, I can bring it back.
**Checklist**

Support remote controlling Ykush devices

---

labgrid/util/managedfile.py

The managedfile class uses the 'stat' command locally, which has a different syntax on MacOS.  Everything otherwise seems to work quite well on MacOS.  Just added different arguments when using MacOS.
**Checklist**

Fix stat command for MacOS

---

man/labgrid-device-config.5
man/labgrid-device-config.rst

The YKUSHPowerDriver uses the ykushcmd binary since #1143.
**Checklist**

man/labgrid-device-config: add ykushcmd

---

labgrid/pytestplugin/fixtures.py
labgrid/pytestplugin/hooks.py

Since pytest 7.0 stash is suggested to be used for storing private information from a plugin.
https://docs.pytest.org/en/7.0.x/how-to/writing_hook_functions.html#storing-data-on-items-across-hook-functions
Tested by running tests using env fixture.
**Checklist**

pytest.stash instead of protected member

---

CHANGES.rst
labgrid/driver/bareboxdriver.py
tests/test_bareboxdriver.py

Log messages such as..
```
eth0: 1000Mbps full duplex link detected
```
..are logged asynchronously. This confuses the BareboxDriver.
To fix that, set the log level to "emerg" (0) right after a prompt is detected and recover the previous log level right before booting.
To make the tests run successfully, mock the _run() method before driver activation to act as if `echo $global.loglevel` was run.
**Checklist**

driver/bareboxdriver: silence barebox in _await_prompt() and unsilence on boot()

---

.github/workflows/scheduled-unit-tests.yml

The stable branch is typically close to the latest release (i.e. what the user will see on `pip install labgrid`). Testing this regularly allows us to notice issues early.

github/workflows: add scheduled test jobs for stable branch

---

labgrid/remote/coordinator.py

Fix the typo, so the actually used attribute is reset.
**Checklist**
Fixes 80067be

remote/coordinator: fix resetting places to an empty set

---

pyproject.toml

tox fails with because we require python >= 3.8 since commit: 6297725 ("drop support for Python 3.7")
**Checklist**

pyproject: remove Python 3.7 from tox envlist

---

pyproject.toml

With the release of Cython3 the build of PyYAML 5.4.1 is broken [1]. There seems to be no plan to fix 5.4.x branch [2]. Tox tests and a real world example runs fine with 6.0.1
[1] https://github.com/yaml/pyyaml/issues/724
[2] https://github.com/yaml/pyyaml/issues/728
master #1237
**Checklist**

pyproject: use PyYAML 6.0.1

---

CHANGES.rst
labgrid/driver/bareboxdriver.py

[1] introduced lowering barebox' log level to 0 (emerg) right after the barebox prompt has been detected and recovering the log level right before booting.
Tests may rely on log output, though. To enable capturing log messages a command may emit, set the log level to the initially remembered level before the command is executed and reset it to 0 (emerg) after the exit code was emitted.
barebox' poller should not run between the echos, so this should be safe. No asynchronous prints are expected to happen during this time.
[1] #1221, 6f7bf661 ("driver/bareboxdriver: silence barebox in _await_prompt() and unsilence on boot()")
**Checklist**

driver/bareboxdriver: run commands with saved log level

---

doc/configuration.rst
labgrid/driver/__init__.py
labgrid/driver/sigrokdriver.py

The ``SigrokDmmDriver`` wraps around a single channel DMM controlled by sigrok. It has been tested with Unit-T UT61C and UT61B devices but probably also works with other single chnnel DMMs.
This driver binds to a SigrokUsbDevice.
Make sure to select the correct driver for your DMM there.
Example usage:
```
resources:
- SigrokUSBDevice:
driver: uni-t-ut61c
match:
'ID_PATH': pci-0000:07:00.4-usb-0:2:1.0
drivers:
- SigrokUt61DmmDriver: {}
```
Args:
bindings (dict): driver to use with sigrok
I'm already using this driver to read values from two DMMs in parallel during hardware testing:
```
volt_dmm = target.get_driver("SigrokDmmDriver", name="volt_dmm")
curr_dmm = target.get_driver("SigrokDmmDriver", name="curr_dmm")
volt_dmm.start(5)
curr_dmm.start(5)
dmm_volt = …
```

driver/sigrok: Add sigrok driver for DMMs

---

doc/configuration.rst
labgrid/driver/__init__.py
labgrid/driver/httpdigitaloutput.py
labgrid/remote/client.py
labgrid/resource/__init__.py
labgrid/resource/httpdigitalout.py
tests/test_httpdigitalout.py

Add support and documentation for a generic digital output driver that works via HTTP.
The driver allows setting an URL to `PUT`/`POST`/`PATCH` a new output status to and an URL to `GET` the current status from.
The message body to send when asserting/deasserting the output can be specified independently.
The status returned by a `GET` request can either be matched exactly against the same body used to set the state or more fuzzily using regular expressions.
- What do _I_ use the feature for?
The [tacd](https://github.com/linux-automation/tacd) system management daemon on the [LXA TAC](https://www.linux-automation.com/de/products/lxa-tac.html) exposes digital outputs via a HTTP API.
The `HttpDigitalOutputDriver` enables controling these outputs.
- How does labgrid benefit …

httpdigitaloutput: support generic digital outputs via HTTP

---

labgrid/driver/shelldriver.py

Since `_check_prompt()` sets the correct `_status` attribute anyway when a login prompt is detected, this only is a problem for cases without login (either because no login is required or it happened before). `get_status()` returns 0 instead of 1 then until `run()` is executed the first time.
Fix this by setting the correct attribute.
**Checklist**
Fixes 822abb3

driver/shelldriver: fix status attribute setting

---

doc/configuration.rst

Fix NetworkFlashrom class name spelling and document SmallUBootDriver's `boot_secret_nolf` attribute.

doc/configuration: small fixes

---

labgrid/resource/udev.py

Similar to USBSerialPort's `port` attribute, USBNetworkInterface's `ifname` attribute is overwritten by udev. Add a warning to make that clear.

resource/udev: warn on initializing USBNetworkInterface with ifname

---

labgrid/resource/__init__.py

This allows users to import resources from `labgrid.resource` directly.

resource: import missing resources

---

CHANGES.rst
labgrid/util/managedfile.py
tests/test_flashscript.py

`ManagedFile` has an optimization to detect if the "local" file is available over NFS at the remote side. In that case, rsync is skipped and get_remote_path will just return the NFS path.
This is done by comparing stat(1) output of the absolute path on local and remote host. If the absolute paths contains symlinks, this comparison may not happen if the remote host doesn't contain the exact same symlinks. Let's avoid this issue by canonicalizing the path.
- what do you use the feature for?
My build directory is symlinked, so I am usually not passing the canonical path to `labgrid-client fastboot flash`
- how does labgrid benefit as a testing library from the feature?
It's faster to read piecewise from NFS than to rsync up-front.
- how did you verify the feature works?
labgrid-client …

util/managedfile: resolve symlinks before comparing NFS paths

---

dockerfiles/Dockerfile
dockerfiles/staging/dut/Dockerfile

Update the docker base image from Debian bullseye to bookworm.
**Checklist**
See also #1009.

dockerfiles: bump base image bullseye -> bookworm

---

dockerfiles/staging/dut/Dockerfile

The docker docs contain [1] these COPY forms:
```
COPY [--chown=<user>:<group>] [--chmod=<perms>] <src>... <dest>
COPY [--chown=<user>:<group>] [--chmod=<perms>] ["<src>",... "<dest>"]
```
Arguments within [ ] are optional. The square brackets are not meant to be part of the actual instruction.
The docker docs [1] mention that "[e]ach <src> may contain wildcards and matching will be done using Go’s filepath.Match rules". Go’s filepath.Match [2] interprets terms in square brackets as a character class. `[--chown=root:root]` must have been interpreted as a valid character class until recently. A couple of days ago, building the "dut" service started failing:
```
Building dut
#0 building with "default" instance using docker driver
#1 [internal] load build definition from …
```

dockerfiles/dut: fix --chown option

---

pyproject.toml

readthedocs installs Python package dependencies like this:
```bash
$ pip install --upgrade --no-cache-dir pip setuptools
$ pip install --upgrade --no-cache-dir pillow mock==1.0.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.9.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<2.3 jinja2<3.1.0
$ pip install --upgrade --upgrade-strategy only-if-needed --no-cache-dir .[doc]
```
Until recently `--upgrade-strategy` was specified as `eager`, but now `only-if-needed` [1]. This results in Sphinx 1.8.6 being used.
This becomes an issue since Sphinx is not required directly by labgrid, but via sphinx_rtd_theme which loosely requires `sphinx >=1.6,<8` [2]. This results in this readthedocs build error:
```python
Exception occurred:
File …
```

pyproject.toml: require Sphinx>=2.0.0 for doc feature

---

labgrid/remote/client.py

On delete, resource is an empty dictionary:
```
ERROR   labgrid.remote.: ClientSession.onUserError(): "While firing <bound method ClientSession.on_resource_changed of <labgrid.remote.client.ClientSession object at 0x7fcf1cbdff90>> subscribed under 8031289985454517."
File "/usr/ptx-venvs/labgrid/lib/python3.11/site-packages/txaio/aio.py", line 487, in done
res = f.result()
^^^^^^^^^^
File "/usr/ptx-venvs/labgrid/lib/python3.11/site-packages/labgrid/remote/client.py", line 126, in on_resource_changed
print(f"Resource {exporter}/{group_name}/{resource['cls']}/{resource_name} deleted")
~~~~~~~~^^^^^^^
KeyError: 'cls'
```
This can be reproduced easily by restarting an exporter while running `labgrid-client monitor`.
We could publish the class, …

remote/client: do not print deleted resource's class on monitor

---

labgrid/driver/shelldriver.py

xmodem was failing because it would consume the trailing newline character between the `echo` for the marker and the command output. Fix this by suppressing new line on the marker
**Checklist**

shelldriver: Fix xmodem

---

labgrid/driver/qemudriver.py

For debugging, it can be useful to start an interactive session for the
user to access the DUT console. This is possible with real targets
through labgrid-client -s STATE console, but no equivalent exists yet
for targets using QEMUDriver. Resolving that may be a bigger
undertaking, so for now, let's provide a class method
get_qemu_base_args, that returns the list of arguments sans QMP parts.
Users can then initialize labgrid as usual and call the function to
get the command line and start Qemu for interactive use without having
to duplicate the labgrid environment parsing as in [1].
[1]: https://github.com/barebox/barebox/blob/v2023.05.0/test/emulate.pl#L226
**- what do you use the feature for?** Start Qemu interactively with same environment yaml used for testing
**- how does labgrid …

qemudriver: export get_qemu_base_args method

---

labgrid/driver/sshdriver.py
tests/test_sshdriver.py

This commit adds a function that will forward a port on the local host to a unix socket on the target.
Adds a function to the ssh driver that allows a unix socket on the target device to be forwarded to a tcp port on the host. This will allow tests to be performed against a running program that has no exposed ports.
**Checklist**

sshdriver: Add Port Forwarding to Unix Sockets

---

labgrid/driver/sshdriver.py
labgrid/util/ssh.py
tests/test_sshdriver.py

Using Popen.wait() on a process that has output sent to a pipe can potentially deadlock if the process produces enough output to fill the pipe, since it will stall and never terminate waiting for the pipe to have more space.
Instead, use Popen.communicate() with the timeout parameter. This will consume all output until EOF (preventing the process from stalling due to a full pipe), and then check the return code. In the event of a timeout error, Popen.communicate() doesn't loose any data, so it's safe to call it again after the Popen.kill() in the exception handler.
This likely was done this way because the timeout parameter was new in Python 3.3, but this shouldn't be a concern anymore
**Checklist**

ssh: Prevent timeout from deadlock

---

examples/docker/conftest.py

__examples/docker__:  `pytest -s --lg-env env.yaml test_shell.py` will print next error:
```
______________________ ERROR at setup of test_shell ______________________
target = Target(name='main', env=Environment(config_file='env.yaml'))
@pytest.fixture(scope='session')
def command(target):
strategy = target.get_driver('DockerStrategy')
>       strategy.transition("shell")
conftest.py:6:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../labgrid/step.py:215: in wrapper
_result = func(*_args, **_kwargs)
../../labgrid/strategy/dockerstrategy.py:39: in transition
status = Status[status]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cls = <enum 'Status'>, name = 'shell'
def __getitem__(cls, name):
>       return cls._member_map_[name]
E …
```

docker: fix wrong state of example

---

pyproject.toml

labgrid's tests have never been linted, so there is no need to install pytest-pylint. Install pylint instead to allow linting of the labgrid module.
Require at least version 3.0.0 of pylint which will be required for Python 3.12 anyway [1].
This also allows us to work around https://github.com/carsongee/pytest-pylint/issues/180 which currently makes our CI tests fail.
[1] https://github.com/pylint-dev/pylint/releases/tag/v3.0.0
**Checklist**

pyproject.toml: depend on pylint rather than pytest-pylint

---

doc/configuration.rst
labgrid/driver/sshdriver.py

OpenSSH >= 9.0 defaults to the SFTP protocol. However, some older targets may only have scp installed. OpenSSH allows to explicitly select scp by providing the `-O` flag.
As already done for the transition of SFTP, add a dedicated SSHDriver attribute named `explicit_scp_mode` which defaults to `False`.
To not call the OpenSSH version check too often, move the call to a `@cached_property`.
**Checklist**
Fixes what was addressed in a [comment](https://github.com/labgrid-project/labgrid/pull/1003#pullrequestreview-1364832063) for #1003

sshdriver: support selecting scp mode explicitly

---

labgrid/resource/udev.py

Add additional SEGGER J-Link model ids to the USBDebugger resource. Have been tested on a distributed infrastructure by flashing a Nordic nRF5340 board with built in J-Link using the OpenOCDDriver.
**Checklist**

Add additional SEGGER J-Link model IDs to USBDebugger resource

---

labgrid/driver/sshdriver.py
tests/test_sshdriver.py

This reverts commit b8f059fb4277e3ca01684b7a71ac89974ff1cc36.
OpenSSH < 8.5 called with -f waits for the stderr pipe to be closed before forking. [1] fixes this behavior.
The labgrid commit to be reverted calls `communicate()`, relying on a timely fork. Affected OpenSSH versions now run into a TimeoutExpired exception on `communicate()` leading to an ExecutionError being raised in labgrid.
A `wait()` with timeout was used since the initial implementation [2]. We wanted to make sure that we don't depend on the state of the pipes, so use of wait() was intentional, as it directly covers the interesting cases:
- immediate abort (due to a config error or similar)
- normal startup (parent process exits after fork)
- hang (via `wait()` timeout)
Reverting the problematic commit …

Revert "sshdriver: Prevent timeout from deadlock"

---

dockerfiles/build.sh

The `has_podman` routine contains a small bug. The routine isn't used for now, but ensure it's working anyway.
Fixes: #1091

dockerfiles: fix has_podman routine

---

labgrid/remote/client.py

In certain situation, e.g. if the serial port vanishes (i.e. on-board FTDI chips), microcom returns with 1 and:
```
Got EOF from port
connection lost
```
The loop should still continue, so do not raise an exception in this case.
Fixes: cdebb1cc ("remote/client: return exit code for ssh/scp/rsync/telnet/video/audio/console")
**Checklist**
Fixes #1137

client: fix console --loop on microcom error

---

labgrid/target.py

Use short-hand class names and add driver causing `NoSupplierFoundErrors` in error messages.
**Checklist**

target: improve exceptions

---

labgrid/remote/exporter.py
man/labgrid-exporter.1
man/labgrid-exporter.rst

In distributed setups, the coordinator may point to places in different subnets. In order for clients to resolve resources behind the exporter, they need to know its FQDN instead of just the hostname.
Thus, set this to be the default when the exporter is invoked without the --hostname parameter.
**Checklist**

exporter: Use fqdn instead of hostname only

---

tests/test_sshdriver.py

Since d08a35c5, stdout of the ssh keepalive process is logged. The return value of the communicate method is used to achieve this. This leads to ValueErrors during testing:
```
File "/home/runner/work/labgrid/labgrid/labgrid/target.py", line 516, in _atexit_cleanup
self.cleanup()
File "/home/runner/work/labgrid/labgrid/labgrid/target.py", line 562, in cleanup
self.deactivate_all_drivers()
File "/home/runner/work/labgrid/labgrid/labgrid/target.py", line 512, in deactivate_all_drivers
self.deactivate(drv)
File "/home/runner/work/labgrid/labgrid/labgrid/target.py", line 505, in deactivate
client.on_deactivate()
File "/home/runner/work/labgrid/labgrid/labgrid/driver/sshdriver.py", line 65, in on_deactivate
self._stop_keepalive()
File …
```

tests: fix SSHDriver deactivation test

---

CHANGES.rst
doc/configuration.rst
labgrid/driver/qemudriver.py

Adds support to pass additional disk options to QEMU when creating the drive. This can be helpful for example to pass different "cache" options that may affect performance.
**Checklist**

qemudriver: Add support for additional disk options

---

.github/workflows/docker.yml
.github/workflows/reusable-unit-tests-docker.yml

Fixes warnings such as:
```
/home/runner/.local/lib/python3.10/site-packages/setuptools_scm/_integration/setuptools.py:30: RuntimeWarning: 
ERROR: setuptools==59.6.0 is used in combination with setuptools_scm>=8.x
Your build configuration is incomplete and previously worked by accident!
setuptools_scm requires setuptools>=61
Suggested workaround if applicable:
- migrating from the deprecated setup_requires mechanism to pep517/518
and using a pyproject.toml to declare build dependencies
which are reliably pre-installed before running the build tools
```
**Checklist**

github/workflows/docker: upgrade setuptools before installing setuptools_scm

---

.github/workflows/push-pr-unit-tests.yml
.github/workflows/scheduled-unit-tests.yml
tests/test_crossbar.py

crossbar is not compatible with Python 3.12, yet: [1] and [2] are not part of a release. A release will probably take some more time [3][4].
We shouldn't advertise Python 3.12 support until that happens. But we can make sure that everything else keeps working fine with Python 3.12 by marking the crossbar tests as XFAIL for 3.12 and running the test suite for 3.12.
[1] https://github.com/crossbario/crossbar/pull/2091
[2] https://github.com/crossbario/crossbar/pull/2093
[3] https://github.com/crossbario/crossbar/pull/2093#issuecomment-1853007773
[4] https://github.com/crossbario/crossbar/pull/2091#issuecomment-1850126501
See also #1260 keeping track of Python 3.12 compatibility.
**Checklist**

Test with Python 3.12, but don't advertise it, yet

---

labgrid/driver/qemudriver.py

The virt machine type is commonly used, when a hardware independent environment is required. Adding virt support to the disk image option, makes it easier to handle frequently changing disk images.

driver/qemudriver: add support for virt machine

---

labgrid/driver/bareboxdriver.py
labgrid/driver/common.py
labgrid/driver/dediprogflashdriver.py
labgrid/driver/dockerdriver.py
labgrid/driver/externalconsoledriver.py
labgrid/driver/fake.py
labgrid/driver/flashromdriver.py
labgrid/driver/flashscriptdriver.py
labgrid/driver/openocddriver.py
labgrid/driver/qemudriver.py
labgrid/driver/quartushpsdriver.py
labgrid/driver/serialdriver.py
labgrid/driver/shelldriver.py
labgrid/driver/sigrokdriver.py
labgrid/driver/sshdriver.py
labgrid/driver/ubootdriver.py
labgrid/driver/usbaudiodriver.py
labgrid/driver/usbstoragedriver.py
labgrid/driver/usbvideodriver.py
labgrid/driver/xenadriver.py
labgrid/resource/common.py
labgrid/resource/docker.py
labgrid/resource/ethernetport.py
labgrid/resource/lxaiobus.py
labgrid/resource/mqtt.py
labgrid/resource/remote.py
labgrid/resource/udev.py
labgrid/util/qmp.py

Each driver and resource sets up their own logger in a pretty similar way. So move this functionality to the base class and generate a sane logger name there.
**Checklist**

driver/resources: use consistent logger names

---

labgrid/driver/qemudriver.py

Fold the "q35", "virt" and "pc" machines into a single if clause. They all use the same definition anyway.
**Checklist**

driver: qemudriver: fold equivalent disk arguments

---

CHANGES.rst
doc/configuration.rst
labgrid/driver/shelldriver.py

Fixes #441
Make `password` an optional field, so when is not set, it defaults to `None`. If we then get a password prompt on login, we can still raise the Exception. Otherwise it is now possible to set the password to an empty string explicitly.
**Checklist**

shelldriver: allow login with empty password

---

doc/configuration.rst
labgrid/driver/power/eth008.py
tests/test_powerdriver.py

Adding a new power driver for robot electronics eth008 using HTTP-GET API.
Locally tested with labgrid-client power on/off/cycle.
**Checklist**

power: add eth008 power backend

---

doc/configuration.rst
labgrid/driver/sshdriver.py

This is another approche than #1291.
Here, username and password properties are added to `SSHDriver` and used instead of username and password coming from `NetworkService`.
This will answer my original issue:
> Depending on the software provisioned on a place, credentials may be different. It's my case where 3 different credentials are needed (user1/pass1 user2/pass2 user3/pass3) when soft1 or soft2 or soft3 is on the target.
`ShellDriver` and `SSHDriver` will both hold credentials in the environment configuration, where the user can adapt then to its use case.
**Checklist**
Closes #1291

driver/sshdriver: Add credential overriding NetworkService's

---

examples/sigrok/env.yaml
examples/sigrok/main.py

Add a simple sigrok example that captures on one channel on a fx2lafw device.
**Checklist**

examples: add sigrok example

---

labgrid/driver/modbusdriver.py
pyproject.toml

Small pr to fix an issue with handling error with modbus.
As per the documentation: https://pymodbustcp.readthedocs.io/en/latest/package/class_ModbusClient.html#pyModbusTCP.client.ModbusClient.last_error
`last_error` is a property, not a function

Fix modbus error parsing

---

CHANGES.rst
debian/changelog
debian/copyright
doc/conf.py
man/labgrid-device-config.5
man/labgrid-device-config.rst
man/labgrid-exporter.1
man/labgrid-exporter.rst
man/labgrid-pytest.7
man/labgrid-pytest.rst
man/labgrid-suggest.1
man/labgrid-suggest.rst

labgrid is under active development, so extend the copyright period to reflect that. Since we're using a calver version scheme, rename the next release to 24.0. While at it, also fix some underlines in CHANGES.rst.
**Checklist**

debian/doc/man: extend copyright period to 2024, rename next release 24.0

---

debian/labgrid.install
doc/configuration.rst
examples/network-test/env.yaml
examples/network-test/pkg-replay-record.py
helpers/labgrid-raw-interface
labgrid/driver/__init__.py
labgrid/driver/rawnetworkinterfacedriver.py

The RawNetworkInterfaceDriver allows "raw" control of a network interface (such as Ethernet or WiFi).
The newly added labgrid-raw-interface helper (``helpers/labgrid-raw-interface``) needs to be installed in the PATH and usable via sudo without password.
It supports:
- recording traffic
- replaying traffic
- basic statistic collection
**Checklist**

Add RawNetworkInterfaceDriver, labgrid-raw-interface helper and example

---

contrib/coordinator-statsd.py

Ensures that the statsd service closes sessions after querying the coordinator.
**Checklist**

contrib/coordinator-statsd: Close sessions

---

doc/configuration.rst

Adjust the section ```TFTPProviderDriver / HTTPProviderDriver``` in the _Configuration_ chapter to what is found in sections ```TFTPProvider / HTTPProvider``` & ```RemoteTFTPProvider / RemoteHTTPProvider``` and enumerate the ```HTTPProviderDriver``` in the code-block, too.

Small formal Documentation Update

---

CHANGES.rst

This is consistent with commit a3df4e6698880ab1f340 (2023-04-27, Rouven Czerwinski: "stepreporter: deprecate it").

CHANGES.rst: mention logging config for StepReporter

---

labgrid/remote/exporter.py

Following the addition of the fqdn option, the hostname is ignored. Hostname is set with gethostname() regardless of args.hostname value because the condition is incorrect.
Fix this and get the hostname option working again.
Fixes #1290

remote/exporter: hostname option is ignored

---

man/labgrid-client.1
man/labgrid-client.rst

In the labgrid-client doc page, where the power option is detailed:
'get' seems to serve the same purpose as 'status', which isn't a valid option, and 'cycle' is not shown in the doc despite being in the CLI help output. This is a quick fix to address that.
**Checklist**

labgrid-client.rst: replace 'status' with 'cycle'

---

contrib/sync-places.py

When settings tags from the command line, key, value pairs are always strings. Make sure this is the same when reading a YAML file. It can easily be done in the YAML file itself, but this makes the syntax a bit lighter.
**Checklist**
This was originally a part of #1303, but was split up now that that PR is editing another file.

contrib: sync-places: convert tags into strings

---

contrib/README.rst
contrib/labgrid-webapp
contrib/requirements-webapp.txt

Add a sub-command to sync-places to generate a graphviz graph of the resources and places in a given environment.
A visual representation can help make sense of a large amount of information quickly.
This tried to put all relevant information in one place without being overly complicated.
I also tired to use a color blind friendly palette, not sure how that turned out.. 
I'm very open to modifying this based on feedback and recommendations.
I also tried to put this into a separate tool using fastapi to have the graph rendered in a browser directly, but ran into trouble. If that approach is preferred I can also push that instead, and maybe with a bit of support we can get it to work consistently.
```console
$ ./labgrid/contrib/sync-places.py graph | dot -Tsvg -o labgrid-graph.svg
```
By …

contrib: add helper to graph current configuration

---

labgrid/driver/mqtt.py
labgrid/resource/mqtt.py
pyproject.toml

labgrid's "mqtt" and "dev" extras require `paho-mqtt>=1.5.1`. With [paho-mqtt 2.0.0](https://github.com/eclipse/paho.mqtt.python/releases/tag/v2.0.0) released on 2024-02-10, [breaking changes](https://github.com/eclipse/paho.mqtt.python/blob/master/docs/migrations.rst#change-between-version-1x-and-20) were introduced. This was first detected by the scheduled CI jobs via pylint:
```
************* Module labgrid.resource.mqtt
labgrid/resource/mqtt.py:20:17: E1120: No value for argument 'callback_api_version' in constructor call (no-value-for-parameter)
************* Module labgrid.driver.mqtt
labgrid/driver/mqtt.py:30:23: E1120: No value for argument 'callback_api_version' in constructor call (no-value-for-parameter)
```
When using 'labgrid-client pw get' with a …

driver/resource: mqtt: use callback API v2, bump paho-mqtt>=2.0.0

---

.github/workflows/build-and-release.yml
.github/workflows/reusable-unit-tests.yml

Fixes deprecation warnings such as:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
When bumping codecov/codecov-action v3 to v4, we run into https://github.com/codecov/codecov-action/issues/1274. The changes [needed for this change](https://about.codecov.io/blog/january-product-update-updating-the-codecov-ci-uploaders-to-the-codecov-cli/) are not clear, yet. Let's stick to the previous version for now.
**Checklist**

github/workflows: update GitHub actions to latest versions

---

pyproject.toml

The new major release 6.0 introduces breaking changes (functions are now async), limit the dependency until we fix this properly.
**Checklist**

pyproject.yaml: limit pysnmp to versions < 6

---

labgrid/driver/usbvideodriver.py

Decoding via VA-API fails for the C920 model and the playbin element on AMD graphic cards, playbin3 has no problems though - so lets switch to that.
Tested on Fedora 39 running GStreamer 1.22.9. 
Current Debian stable ships with [GStreamer 1.22.0](https://packages.debian.org/bookworm/libgstreamer1.0-0) which supports playbin3.
**Error log**
The error output with a failed VA-API pipeline:
<details>
<summary>labgrid-client video</summary>
```
> labgrid-client video
(gst-launch-1.0:17414): GStreamer-Base-CRITICAL **: 16:15:20.192: basetransform: second attempt to fixate caps returned invalid (NULL) caps on pad vaapipostproc0:sink
(gst-launch-1.0:17414): GStreamer-Base-CRITICAL **: 16:15:20.193: basetransform: second attempt to fixate caps returned invalid (NULL) caps on pad …
```

driver/usbvideodriver: use playbin3 element

---

doc/configuration.rst

Initially, all driver bindings were documented with their respective binding key. This wasn't documented consistently since then.
Especially when using multiple instances of a single driver class, the bindings are needed to specify on which resource or other driver a driver should bind on. Until now, most binding keys had to be looked up in the source code. So improve this situation by fixing and adding binding keys as well as also adding all Remote/Network resource variants a driver is able to bind to.
Also update protocol implementations and resource usage. While at it, document drivers not expecting arguments, drop driver usage from network resouces, fix header underlines and remove unnecessary new lines.
**Checklist**

doc/configuration: update/fix bindings, protocols and resource usage

---

doc/configuration.rst
labgrid/resource/udev.py

A USB serial device often provides multiple interfaces for the same
serial number. In these cases it is not possible to distinguish
the interfaces solely based on the serial number (ID_SERIAL_SHORT).
However, if additionally the interface number (ID_USB_INTERFACE_NUM)
is provided, it is possible to distinguish all interfaces without
the need of using the full device path (ID_PATH).
Example:
```
(...)
=== suggested matches ===
(...)
USBSerialPort:
match:
ID_SERIAL_SHORT: ABCDEF00001
ID_USB_INTERFACE_NUM: '00'
(...)
=== suggested matches ===
(...)
USBSerial Port
USBSerialPort:
match:
ID_SERIAL_SHORT: ABCDEF00001
ID_USB_INTERFACE_NUM: '01'
```
**Checklist**

resource: udev: also suggest ID_USB_INTERFACE_NUM for USBResource

---

doc/configuration.rst
labgrid/driver/pyvisadriver.py
labgrid/resource/pyvisa.py

Allow users to override PyVISA backed to use something like PyVISA-sim or another custom backend.
tested using PyVISA-sim with:
**lg-env.yaml**
```yaml
targets:                                                                        
main:                                                                         
resources:                                                                  
RemotePlace:                                                              
name: {{REMOTEPLACE}}                                                   
drivers:                                                                    
- cls: PyVISADriver                                                       
name: 'pyvisa-3333'                                                     
bindings: …
```

driver/pyvisadriver: add optional backend property

---

doc/configuration.rst
labgrid/remote/exporter.py
labgrid/resource/__init__.py
labgrid/resource/suggest.py
labgrid/resource/udev.py

This PR adds support for GPIOs for which the gpiochip is identified using udev.
This is useful when the probe order of the gpiochip is not predictable. 
In this case, this is case it is not possible to know the global gpio number required by SysfsGPIO resource.
With MatchedSysfsGPIO, the pin number is local to the gpiochip and gpiochip is identified with udev
**Checklist**

Resource: add udev based Sysfs GPIO support

---

labgrid/driver/sshdriver.py

map() returns an iterator, which only works once. Return and cache a tuple instead.
Fixes: 2c062e3ac6bb ("driver/sshdriver: store OpenSSH version in cached property")

driver/sshdriver: fix caching of _ssh_version

---

CHANGES.rst
contrib/completion/labgrid-client.bash
doc/configuration.rst
labgrid/driver/usbstoragedriver.py
labgrid/remote/client.py
labgrid/util/agents/udisks2.py
man/labgrid-client.1
man/labgrid-client.rst

Adds a `write-files` client command to copy files onto mass storage. This is useful for bootloader development for processors with bootroms that load code from file systems (e.g. EFI system partition, OMAP, AT91, Zynq, Raspberry ... etc.). The user interface tries to reproduce the semantics of the UNIX `cp` command as much as possible.
As of now, we can only copy individual files, but not recursively on directories; in the future we might want to extend the `ManagedFile` class to support this use case as well.
This is mostly based on @sephalon's #548, with some sprinkles of my #820, but with `udisksctl` instead of `pmount`.
**How to test**
```
labgrid-client write-files a b      # writes files a, b into /mnt/
labgrid-client write-files -t a b c # writes files b, c into …
```

remote/client: implement udisks2-using write-files command 

---

doc/overview.rst

Mention that SSH access to the exporter is required. Also document how the SSH jump host function can be used with plain SSH.
**Checklist**

doc/overview: mention SSH requirement

---

doc/configuration.rst

The exact class name must be used in the configuration snippet. Stick to that name also in the headline as well as in the text.
While at it, link MatchedSysfsGPIO and SysfsGPIO.
Fixes #1339

doc/configuration: fix spelling of MatchedSysfsGPIO class name

---

examples/network-test/pkg-replay-record.py

There is no need to put the frame as a single item into a list.
**Checklist**

examples/network-test: simplify ethernet frame generation

---

labgrid/driver/usbstoragedriver.py

Otherwise, udisks2 and gi are needed for all installations, even if write_files is never used.
Fixes: #1219

driver/usbstoragedriver: use udisk2 only when calling write_file

---

contrib/README.rst

Add a line indicating how to actually see the graph.
This is just a small documentation change to relieve my initial confusion.
Fixes #1355

contrib: Show how to get the graph

---

dockerfiles/Dockerfile
dockerfiles/staging/docker-compose.yml

Instead of relying on an external repository that basically does the same job, use a simple loop opening a socket via bash's pseudo-device files below `/dev/tcp` instead.                                        
**Checklist**

dockerfiles: replace wait-for-it dependency with simple bash loop

---

doc/development.rst

The 'make html' command fails with the [doc] build. Update the documentation to show how to resolve this.
Fixes #1352

doc: Install [dev] so that docs can be built

---

doc/configuration.rst

Besides the image name, the `UUUDriver` supports a `script` attribute. This is described in the Arguments: section, but not in the example, which uses the non-existent `cmd` attribute instead.
Fix that and while at it, correctly indicate that script is optional. Omitting it will just remove the `-b $script` from the `uuu` invocation.
Fixes #1090

doc/configuration: UUUDriver: align example with reality

---

man/labgrid-client.1
man/labgrid-client.rst

Fix/extend positional labgrid-client arguments in man page.
**Checklist**
Fixes: #483

man/labgrid-client: fix/extend positional arguments

---

labgrid/driver/shelldriver.py
tests/test_shelldriver.py

The `get_ip_addresses` may be called with a specific device and returns alls IP addresses on that interface. Due to a limitation in the regex, devices including either dashes or dots aren't detected.
On the OpenWrt distributions the default device is called `br-lan`, usually connecting ethernet ports and WiFi devices. Likewise dots are attached to the device name to specify VLANs.
This commit extends the regex to support both dashes and dots.
**Checklist**
- This is just an extension of the feature, should it still be documented?
- No changes
- No changes
- No changes

shelldriver: allow dashes and dots in device names

---

labgrid/remote/exporter.py

The following ser2net versions return nonzero even on a successful use of the -v flag to get the version:
v4.4.0
v4.5.0
v4.5.1
v4.6.0
v4.6.1
This was fixed in v4.6.2, which was only recently released. Modify _start() so that it uses subprocess.run() to capture stdout and the returncode, then check against the version and effectively ignore the return value if there's a match. If the ser2net version is one of the unaffected ones (e.g. v4.6.2) and still returns nonzero, then raise an ExporterError.
Tested locally by installing in a venv and running the exporter.
Fixes #1383

exporter: check ser2net version in exporter

---

labgrid/resource/udev.py

Add the USB IDs for an FT232HL chip in the Digilent JTAG-SMT2 surface-mount programming module used as a JTAG programmer on FPGA boards.

resource: udev: new USB ID for USBDebugger

---

labgrid/driver/mqtt.py
labgrid/remote/client.py
labgrid/util/agents/network_interface.py
labgrid/util/yaml.py

Right now the CI fails and that makes me and my PRs unhappy.
**Checklist**
Fixes #1406

treewide: fixes to make pylint happier

---

doc/configuration.rst
labgrid/driver/power/ubus.py
tests/test_powerdriver.py

Using PoE switches as power supply is convenient since a switch is needed in many cases anyway and with the right adapter most embedded devices can be powered.
OpenWrt offers `ubus` as micro bus system to control the system, including PoE ports on switches.
This commit adds a driver to handle PoE switches running OpenWrt.
**Checklist**
> Same as for all other NetworkPowerPorts
> no changes

power: add ubus NetworkPowerPort

---

labgrid/util/managedfile.py

If the host systems run Busybox, long options may be disabled. Switch to the short options but comment them for readability.
Remove the pylint comment as a bonus since the line is no longer to long!
**Checklist**

util: use short `ln` options for Busybox compat

---

.gitignore
labgrid/__init__.py
labgrid/util/version.py
pyproject.toml

This avoids the overhead of using `importlib.metadata` to search for the version.

use setuptools_scm to generate a version file

---

labgrid/remote/exporter.py

Fix the ser2net version check and support ser2net >=4.6.0.
**Checklist**
Fixes #1416

Exporter: always use tcp for ser2net

---

CHANGES.rst

Update the changelog for 24.0.

CHANGES: update changelog for 24.0 release

---

CHANGES.rst
doc/getting_started.rst
labgrid/remote/client.py

microcom is generally not available on rpm based distributions[1], making it hard to setup labgrid client on them.
[1] https://repology.org/project/microcom/versions
**Checklist**
Tested the telnet code path in a fedora container.

remote/client: fallback to telnet when microcom is not available

---

labgrid/driver/consoleexpectmixin.py

This code adds a simple return value to the settle() call which is useful in scenarios where a command or key sequence needs to be sent to quiet large amounts of console spam (for example linux kernel dmesg). In such cases this action may have to be retried multiple times and it's good to get an indication from settle() whether the console has really settled or a timeout has been reached.
This code is currently used in our deployment, before the change settle() does not have a return value at all therefore this change should not introduce regressions. The testsuite has been run with the change applied without any tests failing.
No changes to the documentation have been performed as the API of ConsoleExpectMixin is not documented there in detail.
**Checklist**

console: Make settle() indicate success/failure

---

labgrid/driver/sigrokdriver.py

This fixes some things in the sigrok driver implementation:
- explicitly set time field in csv conversion,
apparently some versions of sigrok-cli on some distros (for example Ubuntu 22.04) default to false,
resulting in invalid parsing
- analyze method checks/uses wrong (local) file path when the resource is remote
- capture file is transferred to wrong path when specified filename is not absolute and using a remote sigrok resource.
- avoid deadlock when sigrok-cli process failed
- unsuccessful sigrok-cli termination when using sigrok driver remotely
**Checklist**

driver/sigrok: various fixes

---

labgrid/driver/usbstoragedriver.py
labgrid/util/agents/udisks2.py

When switching an SDWire to 'host' mode, it may take time for the partition to appear.
During that time the device (e.g. '/dev/sdo1') may not exist, so trying to cat e.g. '/sys/call/block/sdo1' fails. Handle this by returning a zero size in that case, as is done when the returned size is empty.
Even when the block device is present, udisks2 may take a short time to make the device available. Handle this by retrying a few times, until things settle.
Add the call to _wait_for_medium() in write_files() while we are here, to match what is done in write_image(). Also fix the parameter type for write_files() and mention the exception it may raise.
This change has been manually tested since there are no tests available for the code being modified.
**Checklist**
(I cannot find any tests for …

udisks2: Be more tolerant of device-startup time

---

doc/development.rst

Document how await_resources inside a strategy can be used to wait for the availability of a resource.
**Checklist**

doc/development: document await_resources

---

labgrid/driver/serialdigitaloutput.py

If self.signal is "dtr", a ValueError is raised.  That happens because the if/else logic is wrong for that case. Fix that.
**Checklist**
Fixes #577

driver/serialdigitaloutput: fix get() for DTR signal

---

labgrid/util/ssh.py

SSHConnection does not open a new connection if an existing connection is open. It reuses the connection and starts a keepalive command (cat).
On `disconnect()`, the keepalive command is only stopped for newly initiated connections, not for existing ones. Fix that.
**Checklist**

util/ssh: stop keepalive in disconnect() when existing connection is used

---

labgrid/driver/power/raritan.py

No need to ensure a maximum number - new models can have more outlets. Just used one today that had index 24.
**Checklist**

driver/power: Remove check for maximum number of outlets for raritan

---

labgrid/driver/externalconsoledriver.py

The ExternalConsoleDriver works on top of a command executed on the local computer. Until now the system default of `io.DEFAULT_BUFFER_SIZE` (typically 8192 bytes) was used for bufsize. This does not work well for this use case, we want unbuffered reads and writes. So set the bufsize to 0, see https://docs.python.org/3/library/subprocess.html#popen-constructor .
**Checklist**

driver/externalconsoledriver: use bufsize=0 for opening external process

---

doc/configuration.rst
labgrid/driver/power/tinycontrol.py

This PR adds a power control backend for the IP Power Socket 6G10A manufactured by tinycontrol.eu. It is integrated in the current network power control framework with the `tinycontrol` model name.
No tests have been provided as it's not clear to me how this can be tested without real HW.
This code is being currently used in our deployment, running the labgrid test suite with this change does not result in any failed tests.
**Checklist**

labgrid/driver/power: Backend for tinycontrol.eu IP Power Socket 6G10A v2

---

.github/workflows/docker.yml
dockerfiles/README.rst
dockerfiles/build.sh
dockerfiles/staging/docker-compose.yml

Address #917 by adding support for building and publishing arm64 Docker images on CI.
The most direct way to do this seems to be docker buildx, using Github actions provider by Docker, but buildx isn't able to push multi-platform images to a local image store so some supporting changes are required to build.sh:
1. Allow additional arguments to be passed
2.  Use the same image names as on Docker Hub
Note that 1. changes usage for build.sh when building for a specific platform. This is addressed in README.md and hopefully addresses more use-cases, but not sure about Labgrid policy about breaking changes?
Building non-x86 platforms with Github Actions uses emulation, so enable layer caching and tweak the Dockerfile to make better use of caches.
There is an additional patch to enable image …

Publish arm64 Docker images

---

labgrid/driver/power/tinycontrol.py

Fixes the import order in the new tinycontrol power backend found by pylint:
```
labgrid/driver/power/tinycontrol.py:13:0: C0411: standard import "urllib.parse.urljoin" should be placed before third party import "requests" (wrong-import-order)
labgrid/driver/power/tinycontrol.py:14:0: C0411: standard import "xml.etree.ElementTree" should be placed before third party import "requests" (wrong-import-order)
```
**Checklist**
Fixes #1405

driver/power/tinycontrol: fix import order

---

examples/deditec-relais8/deditec.py
examples/deditec-relais8/deditec_remote.py
examples/library/test.py
examples/networkmanager/nm.py
examples/qemu-networking/qemunetworkstrategy.py
examples/sigrok/main.py
examples/strategy/bareboxrebootstrategy.py
examples/strategy/quartusstrategy.py
examples/strategy/test_barebox_strategy.py
examples/sysfsgpio/sysfsgpio.py
examples/sysfsgpio/sysfsgpio_remote.py
examples/usbpower/examplestrategy.py
examples/usbpower/test_example.py

The examples are one of the starting points new users might look into. Don't use deprecated classes there and clean up.
**Checklist**

examples: fixes, cleanup, use StepLogger instead of StepReporter

---

doc/usage.rst

Explain that neither  `--lg-colored-steps` nor `LG_COLOR_SCHEME` have an effect anymore.

doc/usage: adjust docs for legacy --lg-colored-steps, LG_COLOR_SCHEME

---

labgrid/autoinstall/main.py

StepReporter is deprecated, use StepLogger instead. While at it, make use of labgrid's basicConfig(). It provides a very similar format string, so drop all redundant arguments.
**Checklist**

autoinstall/main: use labgrid's StepLogger/basicConfig

---

labgrid/util/yaml.py

When adding drivers/resources to an environment config or resources to an exporter config, users can stumble upon redundant keys. The resulting errors are not obvious, the last key simply overrides any previous entries with the same key.
In order to make these config errors more obvious, emit a warning when duplicate keys are detected in mappings.
**Checklist**

util/yaml: warn on duplicate keys in mappings

---

.github/workflows/docker.yml
.github/workflows/reusable-unit-tests-docker.yml
dockerfiles/README.rst
dockerfiles/staging/docker-compose.yml

Docker compose v1 has been deprecated since July 2023 [1]. Now the GitHub actions Ubuntu runner images removed it, too [2]. So move to v2.
labgrid is obviously not affected by any changes between v1 and v2 other than the compose call `docker-compose` -> `docker compose`.
While at it, drop the obsolete version element [3] from the docker compose config.
[1] https://docs.docker.com/compose/migrate/
[2] https://github.com/actions/runner-images/issues/9692
[3] https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element-optional
**Checklist**

docker: move to Docker compose v2

---

.github/workflows/reusable-unit-tests.yml

ncurses-term and the TERM setting were added for the ColoredStepReporter functionality. This has been removed with the StepLogger introduction. So drop both.
**Checklist**

workflows/reusable-unit-tests: do not install ncurses-term, drop TERM setting

---

labgrid/remote/client.py

Since #427 the PLACE environment variable is deprecated in favor of LG_PLACE. So suggest LG_PLACE rather than PLACE.
**Checklist**

remote/client: suggest non-deprecated env var LG_PLACE instead of PLACE

---

doc/configuration.rst
labgrid/resource/udev.py
labgrid/util/agents/usb_hid_relay.py

This USB relay uses a different protocol than the dcttech one, so implement the new protocol and detect which one to use based on the vendor ID.

add support for the LCTech LCUS USB

---

.github/workflows/scheduled-unit-tests.yml

Adding the stable branches here is problematic: GitHub uses the workflow definitions from the default branch (master). The workflow might not match the stable branch. So drop it here.
As a replacement, the current stable branch is tested on a labgrid fork that has the stable branch set as its default branch, so the workflow is maintained in the same branch as the code.

github/workflows/scheduled-unit-tests: drop scheduled docker tests on stable-23.0

---

labgrid/driver/shelldriver.py
tests/test_shelldriver.py

This PR fixes the regex that matches the default interface device name. This bug was discovered when working with OpenWrt in the context of labgrid.
**Checklist**

fix: match interface regex in ShellDriver

---

labgrid/remote/coordinator.py

The code which is creating Reservation objects in the coordinator contains what looks to be a typo. This typo creates a bug where reservations that match more than one tag are not correctly handled.
The places needed to reproduce this problem can be created in the following way:
```
labgrid-client -p place1 create
labgrid-client -p place1 set-tags env=prod
labgrid-client -p place1 set-tags board_model=foo
labgrid-client -p place2 create
labgrid-client -p place2 set-tags env=ci
labgrid-client -p place2 set-tags board_model=foo
```
Before fix:
```
$ labgrid-client reserve --wait env=ci board_model=foo
Reservation '45JJKBHK1X':
owner: localhost/m.grela
token: 45JJKBHK1X
state: allocated
filters:
main: board_model=foo
allocations:
main: place1
created: 2024-09-03 …
```

remote/coordinator: Fix typo to allow for reservations matching multiple tags

---

.github/workflows/reusable-unit-tests.yml
pyproject.toml

The `labgrid.remote` module was formatted with ruff in #1426. The gRPC changes are formatted correctly. Add ruff to the "dev" extra. Then enforce formatting on the module, but exclude generated code.
We can enforce formatting of more modules over time.
**Checklist**

github: enforce ruff format on labgrid.remote

---

labgrid/driver/usbvideodriver.py

The playbin3 uses a urisourcebin to open and read the uri. The urisourcebin detects the fd as a stream uri and internally crates a multiqueue with a default buffer duration of 5 s and a high watermark of 0.60 to buffer the stream. This adds 3 s latency to the video stream.
If the source signals that is it a live source, the urisourcebin would avoid buffering of the stream. Unfortunately, the fdsrc doesn't signal that the data is live, and doesn't have a property to change this.
Use buffer-duration to set the size of the queue for buffering to 0 to avoid this additional latency.
The queue could be completely removed by setting "buffering" in the flags property of playbin3 to 0, which would be equal to the behavior of a live source, but the changed flags are more difficult to understand …

driver/usbvideodriver: reduce latency of GStreamer pipeline

---

labgrid/resource/udev.py

Update list of USBDebugger to match stlink v2 and more stlink v3
Tested with `labgrid-suggest`, which properly reports stlink v2 and v3 with the added model id. Also tested with OpenOCDDriver to load fw on an stm32 mcu (see https://github.com/labgrid-project/labgrid/discussions/1517 for original discussion)
**Checklist**

udev: Adds model id for stlink-v2 and v3

---

pyproject.toml

pysnmp depends on pyasn1. `pyasn1.compat.octets` was removed in pyasn1 0.6.1 [1] leading to ModuleNotFoundErrors in labgrid's "eaton" and "poe_mib" power backends:
```
_______________ TestNetworkPowerDriver.test_import_backend_eaton _______________
self = <test_powerdriver.TestNetworkPowerDriver object at 0x7f84794bfdd0>
def test_import_backend_eaton(self):
pytest.importorskip("pysnmp")
>       import labgrid.driver.power.eaton
tests/test_powerdriver.py:295:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
labgrid/driver/power/eaton.py:2: in <module>
from ...util.snmp import SimpleSNMP
labgrid/util/snmp.py:1: in <module>
from pysnmp import hlapi
/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/pysnmp/hlapi/__init__.py:7: in …
```

pyproject.toml: limit pysnmp's pyasn1 dependency to <0.6.0

---

.github/workflows/push-pr-unit-tests.yml
.github/workflows/reusable-unit-tests.yml
.github/workflows/scheduled-unit-tests.yml
CHANGES.rst
pyproject.toml

Python 3.8 received its [final security release on 2024-09-06 (3.8.20) and is now EOL](https://peps.python.org/pep-0569/). Since #1519 makes our Python 3.8 CI job fail, let's remove support now.

Drop Support for Python 3.8

---

labgrid/remote/exporter.py
labgrid/resource/udev.py

pylint's 'no-self-use' check was moved to an optional extension, see [1].
[1] https://pylint.readthedocs.io/en/latest/whatsnew/2/2.14/summary.html#removed-checkers.
**Checklist**
Note: This is also part of (otherwise unrelated) #1497. Since that PR is still in discussion, let's merge this first as a first step towards happy CI.

treewide: drop pylint disable=no-self-use comments

---

.github/workflows/docker.yml
.github/workflows/reusable-unit-tests-docker.yml
.github/workflows/reusable-unit-tests.yml

Installing setuptools_scm via pip system-wide is deprecated. With ubuntu 24.04 this becomes an error. labgrid does not rely on a special version of setuptools_scm anyway, so simply install the corresponding Ubuntu package.
Bump the Ubuntu runner images to 24.04. Pinning the runner images to a release prevents unexpected breakages
when a new LTS is released. We follow the releases, so let's keep this a manual step.
**Checklist**

github: bump ubuntu runner images to 24.04

---

.github/workflows/reusable-unit-tests.yml

GitHub emits warnings like:
> The following actions use a deprecated Node.js version and will be forced to run on node20: codecov/codecov-action@v3. For more info:
> https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
The codecov upload hasn't worked reliably in a while. This should fix it.

update codecov/codecov-action v3 -> v4

---

labgrid/util/agents/usb_hid_relay.py

Since c9fc5bfdb9da, it was no longer possible to use the same USB relay device from multiple labgrid processes, as the USB device was kept open and claimed.
To fix this, we use a context manager which first claims the USB interface (with retry while busy) and releases it after the transaction.
With this fix, multiple processes can toggle outputs in a busy loop without causing 'USBError(16, 'Resource busy')' failures.
Fixes: c9fc5bfdb9da ("labgrid/util/agents/usb_hid_relay: keep the USB device open")

util/agents/usb_hid_relay: fix concurrent access

---

helpers/labgrid-raw-interface
labgrid/driver/rawnetworkinterfacedriver.py

Adds support for live streaming packets from a RawNetworkInterfaceDriver. This can be useful for writing tests that parse packets in real time looking for a specific pattern, for example:
```python
import dpkt
drv = target.get_driver("RawNetworkInterfaceDriver")
with drv.record("-", timeout=60) as p:
pcap = dpkt.pcap.Reader(p.stdout)
for timestamp, buf in pcap:
eth = dpkt.ethernet.Ethernet(buf)
if _some_criteria_:
break
else:
assert False, "Packet not found!"
```
**Checklist**

Rawnetworkinterface stream

---

.github/workflows/push-pr-unit-tests.yml
.github/workflows/reusable-unit-tests.yml
.github/workflows/scheduled-unit-tests.yml

This fixes the workflows to pass the codecov token to the upload action, so that uploads are no longer blocked by limits.

fix codecov upload

---

pyproject.toml

Instead of repeating the dependencies in the "deb" and "dev" extras, switch to recursively referencing the relevant extras.
This has worked in pip for a while.
**Checklist**

pyproject.toml: use recursive dependencies

---

.github/workflows/push-pr-unit-tests.yml
.github/workflows/reusable-unit-tests.yml
.github/workflows/scheduled-unit-tests.yml
doc/conf.py
pyproject.toml

Add tests for Python 3.13 ([expected on 2024-10-07](https://peps.python.org/pep-0719/#schedule)) and advertise support.
Note that the siglent power backend is incompatible with Python 3.13, see #1509. I think this shouldn't stop us from testing/advertising support, right?
**Checklist**

Test/Advertise Python 3.13 Support

---

.github/workflows/reusable-unit-tests.yml

This allows codecov to show the coverage sepeately for each tested python version.

github/workflows: set the python version as a codecov flag

---

pyproject.toml

Ideally we add files once we ran `ruff format` initially. We've missed that in #1320 and #1534, so do it now.

ruff: enforce on more files

---

helpers/labgrid-raw-interface
labgrid/driver/rawnetworkinterfacedriver.py

Add methods to the RawNetworkInterfaceDriver to set interfaces up and down, as well as getting and waiting for the interface state. Also add basic/EEE/pause interface configuration and query support.
This allows the driver to take more control over the interface, preconfiguration is not needed anymore. Tests that expect the exporter interface to be down (such as ethernet selftests, cable tests) are now possible.
Note that the RawNetworkInterfaceDriver now brings the bound interface up on activate and down on deactivate.
Also note that ethtool gained the required `--json` support for the default sub command and for `--show-eee` only in v6.10.
**Checklist**

driver/rawnetworkinterfacedriver: add interface up/down/(basic, EEE, pause) configuration

---

doc/configuration.rst

I wasn't able to reach the Wiki in the last few days, I guess since the Tizen project is stopped, they stopped serving the wiki?
Let's use links from archive.org instead.
```sh
cd doc/
python3 -m venv venv
source venv/bin/activate
python3 -m pip install sphinx sphinx_rtd_theme setuptools
make html
python3 -m http.server -d .build/html
```
**Checklist**

doc/configuration: fix dead wiki.tizen.org links by using archive.org's

---

labgrid/driver/usbvideodriver.py

This is pretty similar to the existing JPEG cameras and supports manual focus control.
Also do some minor clean-ups while we are here.

USBVideoDriver: add support LogiLink UA0379

---

labgrid/remote/coordinator.py

Replace runnning with running.

remote/coordinator: fix typo

---

labgrid/remote/coordinator.py

This helps with debugging, as tasks don't use the default names of "Task-<ID>".

remote/coordinator: add names for asyncio tasks

---

doc/configuration.rst
labgrid/remote/exporter.py
labgrid/resource/udev.py

This resource is a bit unusual, as there is no corresponding driver, as it is only useful to monitor whether the expected USB hubs are detected by an exporter.
In larger labs, there are often USB hubs that are considered part of the infrastructure. When these fail (either temporarily or permanently), the connected devices aren't detected any more. For users of individual places, this leads to unavailable resources without a clear cause.
By configuring USBHub resources for the infrastructure hubs in the exporters, we can start monitoring hub availability centrally via the coordinator.

add USBHub resource and export

---

doc/configuration.rst
labgrid/driver/sigrokdriver.py
labgrid/remote/exporter.py
labgrid/resource/sigrok.py
labgrid/resource/udev.py

Add channel group parameter to sigrok devices
Trying to interface Labgrid with a power supply using `sigrok`, I need to specify the channel group to be used (in my case: `-g 1`).
**Checklist**

driver/sigrokdriver: add channel group parameter

---

labgrid/resource/docker.py

There is race condition between container start and ssh-server service ready in container, which may possible make `nw_service` not available.
Make `nw_service` for docker not static allows `target` to wait for the available of `nw_service`, rather than raise an exception.
Run the command `pytest -s --lg-env env.yaml test_shell.py`, there is a low probability next:
```
test_shell.py E
======================================== ERRORS =========================================
_____________________________ ERROR at setup of test_shell ______________________________
target = Target(name='main', env=Environment(config_file='env.yaml'))
@pytest.fixture(scope="session")
def command(target):
strategy = target.get_driver("DockerStrategy")
strategy.transition("accessible")
> …
```

docker: fix nw_service not available error

---

doc/configuration.rst
labgrid/driver/dockerdriver.py
tests/test_docker.py

Prioritize existing local docker image, before pulling from a registry.
Try to run a local docker image from the uri given. If the imaging is not found locally, docker will try to pull it from a registry. This will allow you to create and build an image locally, without having to push it to a registry first.
**Checklist**

add option to use local docker image

---

CHANGES.rst
doc/configuration.rst
labgrid/driver/qemudriver.py

- what do you use the feature for?
The barebox test suite uses Labgrid in CI for QEMU and these are some quality of life improvements around `QEMUDriver` `extra_args`:
- Allow `extra_args` to be empty
- Show QEMU stderr for malformed `extra_args`
- Allow `extra_args` to list display devices and have them shown if requested
- how did you verify the feature works?
Manually by editing the YAML and running Labgrid with QEMUDriver:
- by removing `extra_args`
- adding an unknown option in `extra_args` 
- adding `-device ramfb` in `extra_args` and setting `display` to `qemu-default`
**Checklist**
- [x ] PR has been tested

Qemu enhancements for extra_args

---

labgrid/remote/exporter.py

This change is caused by updating ruff 0.8.6 -> 0.9.0. The changelog reads:
> Ruff now formats your code according to the 2025 style guide. As a result, your code might now get formatted differently. See the formatter section for a detailed list of changes.
From: https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md
Fixes the scheduled CI errors: https://github.com/labgrid-project/labgrid/actions/runs/12705943303/job/35417915127
**Checklist**

remote/exporter: apply ruff format fixes for 2025 style guide

---

.readthedocs.yaml

Not specifying a configuration is now deprecated and results in permanent errors soon [1].
Temporary build errors were already observed, see the deprecation timeline in: https://app.readthedocs.org/projects/labgrid/builds/
While at it, bump RTD's Ubuntu/Python versions.
[1] https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
**Checklist**

readthedocs: set explicit sphinx configuration and bump Ubuntu/Python

---

labgrid/remote/exporter.py
tests/conftest.py

We receive the coordinator version in the hello message from the coordinator on the exporter side. Correctly print out that we connected to a coordinator with the sent back version instead of confusingly printing that this is the exporter version.

remote/exporter: fix info message for version

---

labgrid/remote/coordinator.py
labgrid/remote/exporter.py
pyproject.toml

To allow debugging in production, we need a way to introspect objects in the coordinator and exporter without stopping the process. This is possible with pystuck.
We add it as a dev dependency only, as it's only needed in special circumstances and can be installed manually in that case. It is only enabled when the `--pystuck` option is passed on startup.

remote: add support for pystuck

---

labgrid/remote/coordinator.py
labgrid/remote/exporter.py

These check for some corner cases that we've seen in your lab and handle them better.

improve gRPC robustness

---

labgrid/remote/coordinator.py

With many places and resources, saving them can take seconds and block the main loop.
Avoid that by moving that off to an executor thread.
Also split the background tasks so they don't block each other needlessly.

improve handing of background tasks in the coordinator

---

labgrid/remote/exporter.py

Instead of providing incomplete resources on startup since the resource information has not been polled yet, poll the resource once while adding it.

remote/exporter: poll resource on add

---

CHANGES.rst
debian/changelog
debian/copyright
doc/conf.py
man/labgrid-client.1
man/labgrid-client.rst
man/labgrid-coordinator.1
man/labgrid-coordinator.rst
man/labgrid-device-config.5
man/labgrid-device-config.rst
man/labgrid-exporter.1
man/labgrid-exporter.rst
man/labgrid-pytest.7
man/labgrid-pytest.rst
man/labgrid-suggest.1
man/labgrid-suggest.rst

labgrid is under active development, so extend the copyright period to reflect that. Since we're using a calver version scheme, rename the next release to 25.0. While at it, drop outdated dates from the man pages.
**Checklist**

Extend copyright period to 2025

---

labgrid/remote/client.py
tests/test_client.py

This pull request is fixing the tag validation bug - for example:
labgrid-client -p my_place create
labgrid-client -p my_place set-tags my_tag=15
labgrid-client reserve my_tag=15 #error
this error happens when the value starts with a number.
**Checklist**
Fixes #1570

remote: tag value validation in labgrid-client

---

labgrid/remote/coordinator.py

Labgrid currently uses bidirectional streams between coordinator and
client/exporter. For the client side this is a good fit, since the
client sends requests and the coordinator can answer directly. However
for the exporter we have a case where nested calls were used in the old
crossbar infrastructure, namely when re-acquiring a resource after the
exporter was offline but the place was kept acquired. We call these
orphaned resources. They replace the real resource on the coordinator
side until the resource can be reacquired on the respective exporter
after it has restarted.
With crossbar, when seeing the resource update, the coordinator could
directly call the exporter to acquire the resource for the specific
place. This was possible since crossbar did the RPC route handling and
arbitrary …

refactor handling of orphaned resources in the coordinator

---

labgrid/driver/networkinterfacedriver.py

This makes it more clear what state the NetworkInterfaceDriver is waiting for.
**Checklist**

driver/networkinterfacedriver: add wait_state()'s expected argument to step

---

dockerfiles/build.sh

`docker <subcommand> --help` cannot be used to detect whether a sub command is available because it exits with 0 no matter if the sub command exists or not.
Use `docker buildx version` as a test for buildx support instead.
**Checklist**
Fixes: #1585

dockerfiles/build.sh: fix buildx detection

---

labgrid/resource/remote.py

Add the missing sigrok channel_group parameter to the Network variants of the sigrok resources.
**Checklist**
Fixes: #1536

labgrid/resource/remote: add missing sigrok channel_group parameter

---

labgrid/driver/sshdriver.py
man/labgrid-device-config.5
man/labgrid-device-config.rst
tests/test_sshdriver.py

`SSHDriver` now supports the `tools` key in the config to customize the path to `ssh`, `scp`, `sshfs` and `rsync`. It falls back to loading them from the `PATH`, so there's no change in behaviour if the tools aren't specified.
This is useful when running Labgrid on hosts which don't have these tools installed. It also allows running Labgrid workflows hermetically.
**Testing**
Manual tests have been done, using `SSHDriver` to transfer files and execute commands. 
**Checklist**
Fixes #1553

driver/sshdriver: read from tools

---

labgrid/remote/client.py

This is a workround for the gRPC issue https://github.com/grpc/grpc/issues/38679.
On Python 3.12, an empty exception message is printed from gRPC during shutdown, although nothing seems to go wrong. As this is confusing for users, suppress the message by closing stderr. When in debug mode, we keep it open.

remote/client: suppress gRPC error message on shutdown

---

doc/configuration.rst
doc/getting_started.rst
doc/usage.rst
man/labgrid-device-config.5
man/labgrid-device-config.rst

rfc952 specifies:
A "name" (Net, Host, Gateway, or Domain name) is a text string up
to 24 characters drawn from the alphabet (A-Z), digits (0-9), minus
sign (-), and period (.).  Note that periods are only allowed when
they serve to delimit components of "domain style names".
v2: added the updated man pages

doc v2: hostname can have a '-' character

---

labgrid/remote/client.py

Adds support for the power protocol for DigitalOutputPowerDriver (SysfsGPIO) to labgrid-client
**Checklist**

client: add power control to the client via the DigitalOutputPowerDriver

---

contrib/systemd/labgrid-exporter.service

The exporter sets `reexec=True` for known errors only. If other errors occur (e.g. network issues), the exporter exits with 0.
So set `Restart=always` to make sure even these exit conditions lead to a restarted exporter. Drop the now redundant `RestartForceExitStatus`. Add `StartLimitIntervalSec=0` to make it restart indefinitely.
**Checklist**

contrib/systemd/labgrid-exporter: make service restart always and indefinitely

---

doc/configuration.rst
doc/getting_started.rst

Hi,
I just started learning how labgrid works and had some question marks during the process of getting to know labgrid.
While learning, I tried to take some time to add some additional input to the getting_started, which I think would have helped me to understand labgrid faster. I hope that this will help other users in the future.
To make the review process easy, I tried to make small commits out of the changes and explain why the addition makes sense in my eyes in the commit messages.
Cheers,
lemoer

doc: extend getting_started

---

contrib/systemd/labgrid-exporter.service

`StartLimitIntervalSec` belongs in the "Unit" section, not in the "Service" section.
**Checklist**
Fixes: #1616

contrib/systemd/labgrid-exporter: move StartLimitIntervalSec from Service to Unit section

---

labgrid/remote/config.py

ResourceConfig passes a template loader with the directory name of the resource (exporter) config to `jinja2.Environment()`. Instead of using the Environment's loader to load the actual config, the config file is opened and read from manually and its content is then passed to `jinja2.Environment.from_string()`.
Change that by using the designated `jinja2.Environment.get_template()` method to load the config.
**Checklist**

remote/config: simplify ResourceConfig template loading

---

labgrid/driver/power/tplink.py
pyproject.toml

Increase the minimum python-kasa version to 0.7.0. This allows us to use a newly introduced and not deprecated replacement for the kasa.SmartStrip class.
Since python-kasa 0.7.0, the SmartStrip class [is deprecated](https://python-kasa.readthedocs.io/en/stable/smartstrip.html).
The docs state:
"If you want to continue to use the old API for older devices, you can use the classes in the iot module to avoid deprecation warnings."
https://python-kasa.readthedocs.io/en/stable/deprecated.html#deprecated-api-reference
Do that.
**Checklist**

driver/power/tplink: use IotStrip instead of deprecated SmartStrip

---

doc/configuration.rst

Since barebox v2025.03.0 CTRL-d is the recommended way to interrupt barebox autoboot for testing [1].
[1] https://git.pengutronix.de/cgit/barebox/commit/?id=ae482477b60e1e308327658a899358746ff2f5b
/cc @a3f

doc/configuration: recommend CTRL-d as BareboxDriver interrupt

---

labgrid/util/agents/network_interface.py

`nm.get_device_by_iface()` returns `None` if there is no device for an interface. This can happen if NetworkManager is not running, it it's in an undefined state or if it does not manage the interface at all.
Instead of trying to call methods on the returned None type, let's bail out early with a proper exception.
**Checklist**

util/agents/network_interface: bail out if NM did not find an interface

---

.git_archival.txt
.gitattributes

Currently, it's not possible to `pip install` the `labgrid` package by using the GitHub archive URL. However, `setuptools_scm` [supports](https://setuptools-scm.readthedocs.io/en/latest/usage/#git-archives) this with a few files added to the repo.
**Testing**
This fails:
```
pip install https://github.com/labgrid-project/labgrid/zipball/master
```
This succeeds:
```
pip install https://github.com/arm-software/labgrid/zipball/pip-install-from-archive
```
**Checklist**

setuptools_scm: support reading version from archive

---

labgrid/target.py

No need to wait for resources that aren't used when activating a specific resource.
This reduces invocation times of various operations significantly (at least in our case):
- `labgrid-client power get`
3.2 -> 1.2 s
- `labrid-client io get ign`
2.7 -> 1.1 s
- `labgrid-client ssh true`
4.2 -> 3.1 s
Waiting needlessly when interacting with a target can be frustrating, so after some good old `print()` debugging, it turned out to be the polling of resources that took up (at least some of) the time.
**Checklist**

target: poll needed resources only when activating

---

labgrid/driver/fastbootdriver.py

"fastboot erase" erases a flash partition, so add a corresponding method for it.
**Checklist**

driver/fastbootdriver: add erase method

---

labgrid/remote/client.py

Promote the environment variables `LG_ENV`, `LG_PLACE` and `LG_STATE` in the corresponding argument's help texts.
**Checklist**

remote/client: add environment variables to help texts

---

labgrid/resource/udev.py

Add additional SEGGER J-Link model id to the USBDebugger resource. Have been tested on a distributed infrastructure by flashing a Nordic nRF5340 board with built in J-Link using the OpenOCDDriver.
**Checklist**

Add additional SEGGER J-Link model ID to USBDebugger resource

---

labgrid/target.py

This reverts commit d81eb868c445943f332764b428e8111344db47ba.
The change could cause inconsistent driver states (e.g. drivers active
for resources that have become unavailable), as not all resources are
processed by update_resources. See the original PR
https://github.com/labgrid-project/labgrid/pull/1638 for more details.

fix inconsistent driver states by reverting #1638

---

labgrid/pytestplugin/hooks.py

According to [1] add_color_level() is a method of ColoredLevelFormatter
only. The exception AttributeError is raised for other formatters.
[1] https://github.com/pytest-dev/pytest/blob/main/src/_pytest/logging.py#L104
**Checklist**

Use add_color_level() conditionally

---

labgrid/driver/sshdriver.py

Without this change an Exception during `_start_own_master_once()` could get lost if the timeout happens at the wrong point in time.
With this change we re-raise the last exception that happened during `_start_own_master_once()`.
**Checklist**

SSHDriver: Fix Timeout handling on start_own_master()

---

man/labgrid-client.1
man/labgrid-client.rst

Change the formatting of argument placeholders for the `labgrid-client` docs so it's clearer for people looking through the documentation. This includes indentation with extra whitespace in man/labgrid-client.rst so that descriptions are lined up in an editor, although this part isn't reflected on the generated docs page.
I've attached some before and after screenshots to compare how the docs look.
Before:
After:

man/labgrid-client: improve readability

---

doc/configuration.rst
labgrid/driver/power/shelly_gen2.py
pyproject.toml

The API changed and no longer excepts POST for the legacy API. This commit adds support for the "new" RPC API.
Ref: https://shelly-api-docs.shelly.cloud/gen2/General/RPCProtocol
Tested with a Shelly Plug S MTR Gen3
**Checklist**
- Added in docstring
- Tested with real hardware

NetworkPowerPort: add support for Shelly Gen2+

---

doc/configuration.rst

Fix links and sort power backends in the documentation

doc/configuration: fix ubus/sysfs links, sort power backends

---

doc/conf.py

As can be found here [1], pkg_resources is deprecated and is removed by default from python 3.12 according to [2]. The used alternative importlib.metadata is available from python 3.8 on according to [3].
[1] https://setuptools.pypa.io/en/latest/pkg_resources.html
[2] https://docs.python.org/3/whatsnew/3.12.html
[3] https://docs.python.org/3.12/library/importlib.metadata.html

doc: use importlib.metadata in favor of pkg_resources in conf.py

---

labgrid/util/agentwrapper.py
man/labgrid-client.1
man/labgrid-client.rst

Allows client to specify where on the exporter .labgrid_agent_{agent_hash}.py should be copied to. Default is the user homedir.
**Checklist**

agentwrapper: Allow specifying agent prefix

---

doc/configuration.rst
labgrid/driver/modbusdriver.py
labgrid/remote/client.py
labgrid/resource/__init__.py
labgrid/resource/modbus.py

Waveshare only implement the ability to query the status of all relays (https://www.waveshare.com/wiki/Modbus_RTU_Relay#Read_States_of_Relays) not just one, so a modification to the existing drivers is required.
**Checklist**

Add support for Waveshare Modbus Relays

---

doc/configuration.rst
doc/getting_started.rst
doc/usage.rst
man/labgrid-device-config.5
man/labgrid-device-config.rst

Added the full "Power Distribution Unit" next to the first time the abbreviation 'PDU' comes in the configuration documentation.

doc: PDU, hostname regex improvements

---

labgrid/util/managedfile.py
tests/test_util.py

Replace the unnecessary usage of the sshmanager within `ManagedFile` for the local case with pure python functionality.
**Checklist**

Managedfile: replace ssh usage for localhost

---

doc/Makefile
doc/configuration.rst

While trying to make TFTPProviderDriver work with tftpd-hpa on Debian Bookworm, I hit various different issues and ultimately couldn't really make things work properly. The closest I got was by removing --secure from the server's option but I would then need U-Boot to provide the full path to the files and not relative to the TFTP server's root directory, which makes things not go nicely in general and especially not with labgrid (it uses external property as prefix for the path, and not internal).
I installed atftpd instead and things worked out nicely out-of-the-box on Debian Bookworm, so let's mention that in the docs along with the requirements for the labgrid setup to work with the TFTPProvider.
A small unrelated commit crept in to make building the docs faster  by …

doc/configuration: add more info on TFTP server requirements

---

labgrid/resource/udev.py

The list was stolen from U-Boot[1] and RK3576's was given to me by Rockchip's maintainer Heiko Stübner as I don't own an RK3576 board.
[1] https://github.com/u-boot/u-boot/blob/v2025.07/drivers/usb/gadget/Kconfig#L73-L88
**Checklist**
With PX30 and RK3399

RKUSBLoader: add all known USB Product ID

---

CHANGES.rst
doc/usage.rst
labgrid/pytestplugin/fixtures.py
labgrid/pytestplugin/hooks.py
tests/test_fixtures.py

The option is deprecated since labgrid v0.1.0 (released in 2017). It's time to remove it.

pytestplugin: remove deprecated --env-config option

---

labgrid/util/agents/sysfsgpio.py

If the executor doesn't have the proper permissions to control the GPIO or export it, a Permission Denied will be raised. However, __del__ is called regardless and gpio_sysfs_value_fd attribute isn't present if the __init__ doesn't finish.
Thus, Python prints the following:
"""
Exception ignored in: <function GpioDigitalOutput.__del__ at 0x7f5b017f80e0>
File "<loaded sysfsgpio>", line 44, in __del__
AttributeError: 'GpioDigitalOutput' object has no attribute 'gpio_sysfs_value_fd'
""" before the raised Exception, possibly misleading the user on their debugging quest.
Therefore, let's make sure the attribute exists before anything can throw an Exception in __init__.
os.close() can only be called on a valid file descriptor, which None isn't, …

agents/sysfsgpio: fix misleading Python error when permission denied

---

doc/configuration.rst
labgrid/driver/__init__.py

Document missing WaveshareModbusTCPCoil `coil_count` argument, add generic driver import.
Fixes #1575 (/cc @ep1cman)

WaveShare Modbus Fixes

---

doc/development.rst
doc/usage.rst
examples/qemu-networking/qemunetworkstrategy.py
examples/strategy/bareboxrebootstrategy.py
examples/strategy/quartusstrategy.py
examples/usbpower/examplestrategy.py
labgrid/pytestplugin/__init__.py
labgrid/pytestplugin/hooks.py
labgrid/strategy/__init__.py
labgrid/strategy/bareboxstrategy.py
labgrid/strategy/common.py
labgrid/strategy/dockerstrategy.py
labgrid/strategy/shellstrategy.py
labgrid/strategy/ubootstrategy.py
tests/test_docker.py

Introduce a decorator for the Strategy's `transition()` and `force()` methods. It stores the original exception in the Strategy's new `broken` attribute and raises a `StrategyError` from it. All subsequent calls to the decorated method will lead to the original exception.
Now that a Strategy can be marked broken easily, check for that in labgrid's pytest plugin before executing a test and its fixtures. If a broken Strategy is found in one of the targets, skip the test. It's not worth continuing with it. It only leads to cascading and confusing errors.
Having a strategy prepared with the new decorator, a strategy exception now leads to either a test error (when triggered in a fixture) or a test fail (when triggered in the test itself). All subsequent tests requesting the …

Introduce Broken Strategy State, Prevent Further Use and Skip Subsequent Tests

---

doc/configuration.rst
labgrid/driver/usbloader.py

Some devices do not allow USB Serial Download read commands, which will result in a failure, when trying to verify the correctness of the image. Make the verify step optional but on by default.
**Checklist**
Test has been done by creating a minimal place and setting verify to True, False and leaving it empty.
```
targets:
main:
resources:
- RemotePlace:
name: "myboard"
drivers:
- IMXUSBDriver:
verify: False
```

IMXUSBDriver: conditionally check image

---

doc/configuration.rst

This adds documentation to clarify the fact that udev rules are treated as strings and must match the case that udev is expecting.
**Checklist**
Fixes #1733

doc: clarify udev string matching rules

---

labgrid/driver/shelldriver.py

cp -a implicitly preserves symlinks during copying. If the authorized_keys file is a symlink, the /tmp/labgrid-ssh/authorized_keys will still point to the read-only target of the symlink and adding the key will fail.
Add -L to cp to dereference the symlinks.

driver/shelldriver: dereference symlinks when copying .ssh

---

labgrid/driver/fastbootdriver.py

processwrapper.check_output returns a byte-like object, which is not compatible with split() with an str. Decode the output to a str to fix this.
This fixes direct calls of the getvar function from a test suite. Calling `fastboot getvar` from the command line doesn't use the filtering mechanism and is successful without this fix.
The alternatives would have been to change the callers of _filter_fastboot_output to convert the byte-like object to a string, or to change '\n' to a byte-like object. The latter would also need a change of the startswith call.

driver/fastbootdriver: decode output to str before split
