labgrid/remote/client.py
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>
=> remote/client: with 'places' also print aliases and comment

README.rst
This adds actual content to the readme file.
=> readme: update sections

labgrid/config.py
I stumpled upon this while trying to understand how the configurations work, add docstrings for this module.
Signed-off-by: Rouven Czerwinski  <r.czerwinski@pengutronix.de>
=> config: add docstrings

doc/conf.py, doc/index.rst, setup.py
Make onewire support optional and run apidoc via sphinx.
=> build module documentation

doc/getting_started.rst
=> doc/getting_started: finish distributed tutorial

doc/index.rst
=> doc: fix components configuration rename in index

.travis.yml
=> travis: do a git diff before failure for build log

doc/configuration.rst, doc/design_decisions.rst, doc/development.rst, doc/getting_started.rst, doc/index.rst, doc/overview.rst, doc/usage.rst
Signed-off-by: Jochen Frieling <j.frieling@pengutronix.de>
=> doc: fix typos

doc/configuration.rst
=> doc/configuration: add OneWirePIODriver

labgrid/driver/shelldriver.py
When invoking a longer running command, e.g. a tar extract, the default
timeout of 30 seconds is not sufficient.
=> shelldriver: allow to specify timeout value for run() and run_check()

tests/conftest.py, tests/test_onewire.py, tests/test_serialdriver.py, tests/test_sshdriver.py
=> tests: add tests for the onewire components

doc/development.rst, doc/usage.rst
Adds three new documentation sections.
=> Writing a strategy, hawkbit and usb stick emulation

doc/usage.rst
Signed-off-by: Jochen Frieling <j.frieling@pengutronix.de>
=> doc/usage: fix typos

dev-requirements.txt, labgrid/remote/client.py, labgrid/util/__init__.py, labgrid/util/dict.py, man/labgrid-client.1, man/labgrid-client.rst, setup.py
This shows resource or places changes as they happen, which is useful
during development or debugging.
=> remote/client: add monitor mode

doc/configuration.rst, labgrid/strategy/__init__.py, labgrid/strategy/shellstrategy.py
This is for systems which boot Linux automatically.
=> strategy: add ShellStrategy

labgrid/config.py
=> config: fix missing logging import

doc/configuration.rst, doc/development.rst, labgrid/config.py, labgrid/driver/__init__.py, labgrid/driver/qemudriver.py, labgrid/util/qmp.py, tests/test_qemudriver.py
=> Qemudriver

doc/configuration.rst, labgrid/config.py, labgrid/driver/qemudriver.py
Also fix a problem with kernel arguments and improve the config exception messages.
=> add support for disk images to the QEMUDriver

dev-requirements.txt
=> setup, requirements: add missing xmodem dependency

labgrid/driver/bareboxdriver.py, labgrid/driver/ubootdriver.py, labgrid/protocol/linuxbootprotocol.py
These commits implement reset functionality for bootloader drivers.
=> bootloader reset

labgrid/config.py, labgrid/environment.py, man/labgrid-client.1, man/labgrid-client.rst, man/labgrid-device-config.1, man/labgrid-device-config.rst, tests/test_environment.py
=> Add imports key for remote client

labgrid/config.py, labgrid/pytestplugin/fixtures.py
In pytest plugins are marked available as long as they are registered,
registration however does not indicate usage. Check if junit xml output is
enabled and only than report additional attributes.
=> fixtures: check if getattr returns the _xml attribute

labgrid/driver/power/netio_kshell.py, tests/test_powerdriver.py
added model to interface with all netio_4x-models over telnet(kshell)
Signed-off-by: Johannes Nau <johannes.nau@jumo.net>
=> add NetworkPowerDriver-model "netio_kshell"

doc/configuration.rst, labgrid/driver/shelldriver.py
=> driver/shelldriver: add login timeout option

doc/development.rst
=> doc: update Ideas to reflect already implemented features

doc/configuration.rst, labgrid/driver/serialdriver.py, labgrid/resource/serialport.py, tests/conftest.py, tests/test_serialdriver.py
Signed-off-by: Johannes Nau <johannes.nau@jumo.net>
=> add support for remote serial ports over raw-tcp.

README.rst, doc/configuration.rst, doc/getting_started.rst, doc/usage.rst
These patches provide multiple enhancements for the documentation.
Those are mostly about the "getting started" part and help users on a Debian current distributions to copy-and-paste their way through this section.
=> Documentation Updates

doc/configuration.rst, labgrid/driver/ubootdriver.py
Signed-off-by: Rouven Czerwinski <rouven@czerwinskis.de>
=> ubootdriver: make password prompt configurable

labgrid/remote/client.py
=> remote/client: support named digital IOs

doc/development.rst, labgrid/target.py, tests/test_target.py
=> target: support optional bindings

doc/configuration.rst, labgrid/consoleloggingreporter.py, labgrid/driver/consoleexpectmixin.py, labgrid/pytestplugin/fixtures.py, labgrid/pytestplugin/reporter.py, labgrid/step.py, labgrid/stepreporter.py, setup.py, tests/conftest.py, tests/test_reporter.py, tests/test_step.py
This PR adds file logging output for console events.
=> Add logging output support for console events

dev-requirements.txt, doc/configuration.rst, labgrid/driver/__init__.py, labgrid/driver/modbusdriver.py, labgrid/resource/__init__.py, labgrid/resource/modbus.py, setup.py
=> add ModbusCoilDriver and corresponding resource

doc/configuration.rst, labgrid/driver/modbusdriver.py, labgrid/driver/onewiredriver.py, labgrid/resource/modbus.py, labgrid/resource/onewireport.py
=> driver&resource: add support for inverted PIOs

labgrid/driver/shelldriver.py
Previously we did a bind mount on just the authorized key file, this breaks if
we have a read only file system. Create a directory in /tmp and bind mount the
whole ~/.ssh directory instead.
Fixes #93
=> Mount .ssh directory instead of authorized_keys file

doc/getting_started.rst
=> doc/getting_started: describe how to use ID_PATH via udev

CHANGES.rst, examples/barebox/conftest.py, examples/barebox/test_bootchooser.py, examples/barebox/test_watchdog.py, examples/infoprotocol/conftest.py, examples/infoprotocol/env.yaml, examples/library/test.py, examples/remote/test_barebox.py, examples/shell/conftest.py, examples/strategy/local.yaml, examples/strategy/test_barebox_strategy.py, examples/strategy/test_uboot_strategy.py, examples/usb/test_usb_mxs.py, examples/usb/test_usb_storage.py, examples/usbstick/conftest.py, examples/usbstick/test_stick.py, labgrid/target.py, tests/test_target.py
Add syntactic sugar to target functions and add protocols to __getitem__
=> Driver, Resource and protocol retrieval by string

README.rst
=> README.rst: minor typo

doc/configuration.rst, labgrid/driver/__init__.py, labgrid/driver/sigrokdriver.py, labgrid/remote/exporter.py, labgrid/resource/remote.py, labgrid/resource/sigrok.py, labgrid/resource/udev.py, tests/conftest.py, tests/test_sigrok.py
=> sigrok support

README.rst
=> README: add link to IRC and Matrix channel

labgrid/resource/remote.py, tests/conftest.py, tests/test_crossbar.py
Fix a regression introduced in the pyup update.
=> Fix Remoteplace regression

doc/getting_started.rst
=> doc/getting_started: add newline to fix code-block parsing

doc/configuration.rst, labgrid/driver/ubootdriver.py
=> ubootdriver: make bootstring configurable and update docstring

labgrid/protocol/__init__.py, tests/test_fixtures.py, tests/test_powerdriver.py, tests/test_protocol.py, tests/test_util.py
Various small new tests to increase coverage
=> Increase coverage

examples/strategy/bareboxrebootstrategy.py
This strategy can serve as an example for how to write your own strategies.
=> add an example strategy to get into barebox via reboot

examples/hawkbit/test_hawkbit.py, labgrid/external/hawkbit.py
This series extends the external/hawkbit code to be able to perform automated deployments and simple rollouts.
=> Fix and extend hawkbit control code

labgrid/remote/client.py
Signed-off-by: Enrico Joerns <ejo@pengutronix.de>
=> remote/client: add 'sd-mux' paramter to switch USB-SD-Mux remotely

doc/conf.py, doc/configuration.rst, doc/usage.rst, man/labgrid-device-config.1, man/labgrid-device-config.rst
Add documentation for the bindings key in the environment configuration files. I also added a missing resource to configuration.
=> Document how to use multiple drivers with names in the yaml configuration files.

doc/configuration.rst, labgrid/driver/usbtmc/keysight_dsox2000.py, labgrid/driver/usbtmcdriver.py, labgrid/driver/usbvideodriver.py, labgrid/remote/client.py, labgrid/remote/common.py, labgrid/remote/coordinator.py, labgrid/remote/exporter.py, labgrid/resource/remote.py, labgrid/resource/udev.py, labgrid/util/agent.py, labgrid/util/agentwrapper.py, setup.py, tests/test_agent.py, tests/test_usbtmc.py, tests/test_usbvideo.py
Only the "Logitech HD Pro Webcam C920" and "Keysight DSO-X 2014A" are supported for now.
=> Add support for USB webcams and oscilloscopes

doc/development.rst
=> doc/development: update ideas section with new features

labgrid/target.py
`get_active_driver` is just a special case of `get_driver`, refactor the code to
reflect that by adding an active keyword parameter. Also assert if activate and
active are both set.
This also fixes a bug where `get_active_driver` did not respect driver
priorities.
=> Fix Priorities for get_active_driver

labgrid/remote/client.py
Change is analogous to the io subcommand.
=> client: add named access to consoles

labgrid/driver/openocddriver.py
This makes the openocd driver more flexible to use.
=> driver/openocddriver: multiple improvements

doc/development.rst
=> doc/development: explain default paths in graph strategy

labgrid/driver/serialdriver.py, labgrid/pytestplugin/fixtures.py, labgrid/resource/remote.py, labgrid/strategy/graphstrategy.py
Miscellaneous changes to improve overall usability:
- do not run tests if init failed
- raise additional error on failed serial open
- show steps in GraphStrategy
- use check_output instead of check_call for more informative exceptions and debug log command as well as output
=> Improve usability

labgrid/resource/udev.py
Previously the USBSDMuxDevice set up its on polling solution to find the disk
and control path. Update them after the udev device is added or removed instead
of polling constantly.
=> resource/udev: use update function for USBSDMuxDevice

doc/usage.rst, labgrid/config.py, labgrid/environment.py, labgrid/pytestplugin/__init__.py, labgrid/pytestplugin/fixtures.py, labgrid/pytestplugin/hooks.py, labgrid/pytestplugin/reporter.py
=> Feature Flags

labgrid/driver/usbtmc/tektronix_tds2000.py, labgrid/driver/usbtmcdriver.py, labgrid/remote/client.py
This was tested on a TDS2014B.
=> driver/usbtmc: add basic support for Tektronix TDS2000

.travis.yml, CHANGES.rst, doc/development.rst, doc/getting_started.rst, labgrid/driver/fastbootdriver.py, labgrid/driver/networkusbstoragedriver.py, labgrid/driver/openocddriver.py, labgrid/driver/quartushpsdriver.py, labgrid/driver/serialdriver.py, labgrid/driver/usbloader.py, labgrid/pytestplugin/fixtures.py, labgrid/remote/client.py, labgrid/remote/exporter.py, labgrid/util/__init__.py, labgrid/util/helper.py, labgrid/util/managedfile.py, labgrid/util/proxy.py, labgrid/util/ssh.py, man/labgrid-exporter.1, man/labgrid-exporter.rst, tests/conftest.py, tests/test_util.py
This PR introduces:
- sshmanager to manage ssh connections to exporters and use only one socket connection
- ManagedFile to support upload of image files to exporters
- A proxy infrastructure to use port forwarding for serial connections
Check List:
=> SSH Tunneling and ManagedFile

doc/development.rst
Typo and link fixes for doc/development.rst.
Corrects typos which introduce wrong rendering and corrects a link placement which was broken in the sshmanager doc commit.
Tested by looking at the rendered github output.
=> Fix typos in doc/development and correct link

labgrid/driver/fastbootdriver.py, labgrid/driver/networkusbstoragedriver.py, labgrid/driver/openocddriver.py, labgrid/driver/power/gude8316.py, labgrid/driver/quartushpsdriver.py, labgrid/driver/serialdriver.py, labgrid/driver/sshdriver.py, labgrid/driver/ubootdriver.py, labgrid/driver/usbloader.py, labgrid/pytestplugin/reporter.py, labgrid/remote/client.py, labgrid/remote/exporter.py, labgrid/util/helper.py, labgrid/util/managedfile.py, labgrid/util/proxy.py, labgrid/util/ssh.py
Most of these popped up during `tox -e lint`.
=> Miscellaneous fixes: styling, unused imports, overridden builtins, ..

labgrid/driver/openocddriver.py, labgrid/driver/quartushpsdriver.py
#308 introduced ManagedFile. Fix this in quartushpsdriver and extend the ManagedFile usage in quartushpsdriver.
=> ManagedFile: fix quartushpsdriver, make configs in openocddriver managed

man/labgrid-device-config.1, man/labgrid-device-config.rst
=> man/labgrid-device-config: document python module import

labgrid/remote/client.py, labgrid/target.py
=> Miscellaneous fixes: error message for coordinator connection failure, fix get_resources() docstring

.travis.yml, labgrid/util/ssh.py, tests/test_util.py
This fixes some edge-cases in the SSHConnection implementation:
- handing of existing SSH masters
- host key checking
- testing in travis and locally
- premature master timeout (when unused for a some minutes)
- unclear log messages
=> fix managed SSH connections

doc/development.rst, doc/usage.rst
Fixes (among other things) #365.
=> doc: fixes and improvements

tests/test_fixtures.py
This should catch problems like the one fixed in #377.
**Checklist**
=> tests: check that the pytest plugin loads correctly and --help still works

doc/configuration.rst, labgrid/driver/networkusbstoragedriver.py
Implement image loading support from the environment configuration file for the NetworkUSBStorageDriver.
=> driver/networkusbstoragedriver: support images configuration

labgrid/util/agent.py, labgrid/util/agents/dummy.py, labgrid/util/agentwrapper.py, tests/test_agent.py
This change allows splitting of agent functionality into modules loaded on demand.
**Checklist**
=> loadable modules for the agent

doc/configuration.rst, labgrid/driver/shelldriver.py
Two small editorial changes and then one new section:
- getting started: move udev section into exporter section
- configuration: explain options, images, tools, and example keys
- getting started: give a short introduction into the library
=> Documentation improvements

labgrid/driver/modbusdriver.py
With this an ExecutionError is raised if the read/write coil operations
fail.
**Checklist**
=> driver: modbusdriver: add error handling

labgrid/resource/udev.py
The backlog collects udev events and works on them in batches with a
maximum of 10 events at once.
This prevents stalls of the heartbeat since the exporter can spend a
long time processing all udev events if many devices are disconnected or
connected at once.
**Checklist**
Fixes #361
=> resource/udev: add backlog for udev

doc/development.rst
Signed-off-by: Florian Scherf <f.scherf@pengutronix.de>
=> docs: improve GraphStrategy docs

.travis.yml, dev-requirements.txt, doc-requirements.txt, graph-requirements.txt, modbus-requirements.txt, requirements.txt, snmp-requirements.txt, xena-requirements.txt
This is part of an incremental update of our dependencies to newer versions.
=> update dependency versions

dev-requirements.txt, doc-requirements.txt, doc/conf.py, graph-requirements.txt, requirements.txt, snmp-requirements.txt, xena-requirements.txt
This updates several dependencies to the current versions.
**Checklist**
=> update various dependencies

CHANGES.rst, doc/configuration.rst, labgrid/driver/__init__.py, labgrid/driver/flashromdriver.py, labgrid/resource/__init__.py, labgrid/resource/flashrom.py, tests/test_flashrom.py
Signed-off-by: Kasper Revsbech <krev@triax.com>
=> flashrom: Add support for flashing ROM's by the flashrom utility

tests/test_flags.py
Add tests for the flags introduced previously.
=> tests: add test for flags

labgrid/pytestplugin/reporter.py, labgrid/step.py, tests/test_step.py, tests/test_stepreporter.py
It's useful for debugging to show some more information from the StepReporter, so collect and show duration and exception information.
**Checklist**
=> steps: add exception and duration information

doc/overview.rst
Document the proxy settings.
**Checklist**
=> doc/overview: document proxy settings

labgrid/remote/coordinator.py, labgrid/util/__init__.py, labgrid/util/atomic.py, tests/test_crossbar.py
These are some easy fixes I found while implementing resource acquire/release support.
**Checklist**
=> Minor coordinator fixes and cleanups

doc/development.rst
Target Feature Flags and SSH Tunneling have been implemented.
**Checklist**
=> doc/development: remove implemented ideas

doc/RELEASE.rst, doc/conf.py
Release documentation I wrote quite some time ago but never send to the project. Lets discuss whether this is correct.
=> doc: add RELEASE.rst file for maintainers

labgrid/remote/client.py
Simplify the autobahn WAMP session setup and fix running a strategy from labgrid-client.
Fixes #472
=> Fix client strategy

debian/copyright
This adds a debian/copyright file in the expected format.
**Checklist**
=> Add Debian copyright file

examples/strategy/bareboxrebootstrategy.py, examples/strategy/quartusstrategy.py, examples/usbpower/examplestrategy.py, labgrid/remote/common.py, labgrid/step.py, tests/test_target.py
This PR fixes two minor issues with the attr.s cmp deprecation and the formatting of duration values from Steps.
**Checklist**
=> minor fixes

labgrid/util/helper.py
This fixes two small problems in the processhelper.
**Checklist**
=> minor processhelper fixes

labgrid/driver/qemudriver.py, labgrid/resource/udev.py
Some minor fixes collected while developing match suggestion support.
**Checklist**
=> Minor fixes to qemudriver and udev resources

labgrid/driver/usbvideodriver.py
Newer Logitech C920 versions seem to have a different USB VID. They also
seem to support the newer UVC1.5 standard, which is not implemented by
Linux, therefore the h264 output is unfortunately not supported.
This PR adds a separate pipeline for these devices which use the MJPG
output and VA-API to convert to a h264 stream.
=> usbvideodriver: add support for newer C920 Webcams

labgrid/target.py
Instead of polling the managers for the resources, poll the resources
directly. This brings the usage more in line with how these resources
are polled in the exporter, allowing the usage of the USBSDMuxDevice in
local configurations again.
**Checklist**
=> target: poll resources directly

labgrid/target.py, tests/test_target.py
This helps discovering errors in complex yaml configs.
**Checklist**
=> target: make sure drivers consume all given bindings

dev-requirements.txt, graph-requirements.txt, requirements.txt, snmp-requirements.txt, xena-requirements.txt
The new pytest version has some useful features, so update our pins.
**Checklist**
=> update pytest and some minor dependencies

labgrid/driver/sshdriver.py
Add a keepalive function to the SSHDriver, similar to the utils ssh
implementation.
**Checklist**
=> driver/sshdriver: add keepalive

doc/configuration.rst, doc/getting_started.rst, doc/overview.rst, man/labgrid-exporter.1, man/labgrid-exporter.rst
This came up in #582 and @Bastian-Krause was equally clueless as myself.
=> improve labgrid-exporter configuration docs

labgrid/driver/sshdriver.py
Closes https://github.com/labgrid-project/labgrid/issues/597
Running the example from the issue:
```
from labgrid import Target
from labgrid.resource import NetworkService
from labgrid.driver import SSHDriver
lg_target = Target("Device")
lg_network_service = NetworkService(lg_target,
name='network_service',
address='192.168.3.15',
username='root')
lg_ssh_driver = SSHDriver(lg_target, name=None)
try:
lg_target.activate(lg_ssh_driver)
except Exception as e:
print(e.msg)
print(e.stdout)
print(e.stderr)
```
```
$ python labgrid_issue.py 
Failed to connect to 192.168.3.15 with ['ssh', '-f', '-o', 'LogLevel=ERROR', '-o', 'PasswordAuthentication=no', '-x', '-o', 'ConnectTimeout=30', '-o', 'ControlPersist=300', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', …
```
=> sshdriver: Add stdout and stderr to the subprocess exception

labgrid/driver/power/sentry.py, tests/test_powerdriver.py
=> driver/power: add support for Sentry PDU

labgrid/driver/usbstoragedriver.py, labgrid/util/managedfile.py, labgrid/util/ssh.py
This improves/fix some some minor issue discovered in the USBStorageDriver and the related file handling code.
**Checklist**
=> minor storage driver improvements

doc/development.rst
=> doc: development: start hints for writing and debugging tests

dev-requirements.txt, labgrid/pytestplugin/fixtures.py, requirements.txt, setup.py
Pytest 6 was released recently with a lot of improvements and bug fixes.
Use the latest pytest version and the latest pytest plugin versions which
might have changes to be compatible with the 6.x versions.
**Checklist**
=> Update pytest and pytest-* to current versions

labgrid/driver/usbstoragedriver.py
Add log entires just before actual writing is executed. This is useful
when checking logs to figure out what exaclty got written.
Signed-off-by: Stefan Agner <stefan@agner.ch>
**Checklist**
=> driver/usbstoragedriver: log what actually gets written

labgrid/util/helper.py
Executing a very shored lived process (e.g. a cat of a /sys file) using
check_output sometimes does not return the output the process returned.
Debugging into it showed that the process indeed returned the expected
value, but the PTY file descriptor also returned a EIO error:
read(17, "131072\r\n", 4096)            = 8
read(17, 0x55bd3aff9750, 4096)          = -1 EIO (Input/output error)
The PTY file descriptor is passed to os.fdopen() which returns a
io.BufferedReader instance. It turns out that io.BufferedReader is not
suitable to handle PTY file descriptors. It handles the EIO error as an
actual error and swallows the previously read bytes. The Python Issue
5380 has more details: https://bugs.python.org/issue5380.
Use low-level I/O operation so we can properly handle -EIO. …
=> util/helper: use low level read for PTY

doc/usage.rst, labgrid/driver/sshdriver.py, labgrid/target.py
- Remove support for user control master connections
- Document the `cleanup` function for targets in the library case
- Minor adjustments to `argument` printing
**Checklist**
=> SSHDriver cleanup

doc/configuration.rst, labgrid/driver/smallubootdriver.py
=> smallubootdriver fixes

.github/workflows/unit-tests.yml, doc/getting_started.rst
The new pip resolver correctly resolves that crossbar requires autobahn with compression. Document it and add it to the workflow.
With this the CI builds again: https://github.com/Emantor/labgrid/actions/runs/395994168
**Checklist**
=> Add libsnappy dev and document requirement for crossbar

labgrid/util/ssh.py, tests/test_util.py
Newer SSH versions have a more specific error message for the
control-master check, add it to the output check.
**Checklist**
=> util/ssh: add more specific SSH error message

labgrid/strategy/graphstrategy.py
High-level documentation is already available in doc/development.rst. Having doc strings on the errors and public methods still makes sense, since strategies that want to use these features must inherit from the GraphStrategy and must know how the public methods are intended to work.
**Checklist**
=> graphstrategy: document errors and public methods

doc/configuration.rst, labgrid/driver/serialdriver.py
Adds a timeout parameter to the Serial Driver
**Checklist**
=> Serial timeout

CHANGES.rst
Update CHANGES.rst for release v0.3.0
**Checklist**
=> CHANGES: update for release v0.3.0

doc/getting_started.rst
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>
This patch fixes a few small inconsistencies in the getting started documentation. It provides a working example of remote access to serial console.
=> doc: fix small inconsistency in the getting started

labgrid/target.py, tests/test_target.py
The duplicate binding mechanism forbid the duplicate binding of the same
supplier:
```
class DriverWithMultiA(Driver):
bindings = {
"res1": ResourceA,
"res2": ResourceA,
}
```
Is not allowed since the same resource is bound twice. We do howver have
Driver implementing two protocols, like the QEMUDriver:
```
class QEMUDriver(ConsoleExpectMixin, Driver, PowerProtocol, ConsoleProtocol):
```
Here we do want to allow the binding of the QEMUDriver under differing
Names, namely binding it as a PowerProtocol and ConsoleProtocol.
Rework the code to keep a set of (requirement, supplier) to check
against and prevent binding against the same class with a duplicate
binding error, however allow it if the supplier was found under a
different requirement.
Signed-off-by: Rouven Czerwinski …
=> target: duplicate bindings under differing names

labgrid/driver/sshdriver.py
Implement retry loop around start of ssh controlmaster connection,
avoiding "connection refused" errors caused by targets starting sshd after network interface is brought up.
Fixes #641
=> driver/sshdriver: add retry for fast failures

.github/workflows/unit-tests.yml, man/labgrid-client.1
Make sure that the man pages are reliably rebuild with rst2man.
**Checklist**
=> fix man page CI check

labgrid/strategy/ubootstrategy.py
Activate the console early so catch fast booting devices, as was done with barebox
**Checklist**
=> Uboot early console

dockerfiles/staging/docker-compose.yml
=> docker: docker-compose remove ports in dut configuration

crossbar-requirements.txt, requirements.txt
This should fix the CI failures due to incompatibilities with twisted.
**Checklist**
=> Bump crossbar & autobahn

doc/configuration.rst, labgrid/driver/__init__.py, labgrid/driver/flashscriptdriver.py, labgrid/remote/client.py, labgrid/remote/exporter.py, labgrid/resource/remote.py, labgrid/resource/udev.py, tests/test_flashscript.py
Some SoC vendors have complex and SoC specific protocols and programs
that are required to flash software on their devices. Instead of trying
to implement drivers for all of these one-off implementations, implement
the surgical chain-saw approach and add support for sending a "flashing
script" to be run on the exporter which will flash the device.
A typical use case might be creating a self extracting flashing script
with e.g. makeself that contains the image files and all flashing
utilities.
**Checklist**
=> Add Flash Scripting Driver

doc/configuration.rst, labgrid/driver/qemudriver.py
Minor improvements to the Qemu Driver
**Checklist**
=> Qemu improvements

labgrid/resource/ethernetport.py
Instantiating an exception, but not raising it, has no effect.
**Checklist**
Fixes #83
=> resource: ethernetport: raise exceptions rather than only instantiating them

labgrid/driver/quartushpsdriver.py
PR #736's ccc17c86 ("driver: quartushpsdriver: retry jtagconfig until intact JTAG chain found") implemented retrying on a specific error message.
Every once in a while other errors occur. Since `jtagconfig` is part of the proprietary Quartus programmer suite, there is no reasonable way to tell intact JTAG chains apart from error messages other than trying to parse the JTAG ID.
An intact chain looks like this:
4BA00477   SOCVHPS
..whereas errors look like that:
Unable to lock chain - Chain in use - check  on 127.0.0.1
..or:
Unable to read device chain - JTAG chain broken`
So try to find the JTAG ID of the first chain and make sure its a valid hexadecimal number. If that fails, log the message as a warning and try again for a limited time. We do not longer rely on a specific …
=> driver: quartushpsdriver: try reading JTAG ID from chain to identify errors

CHANGES.rst, dockerfiles/base/Dockerfile, dockerfiles/client/Dockerfile, dockerfiles/staging/docker-compose.yml, labgrid/resource/ethernetport.py, labgrid/resource/serialport.py, requirements.txt
Cherry picks and updates for changes for release 0.3.3.
**Checklist**
=> Stable 0.3.3

labgrid/driver/flashscriptdriver.py, labgrid/driver/mqtt.py, labgrid/driver/power/gude8031.py, labgrid/driver/provider.py, labgrid/driver/sshdriver.py, labgrid/driver/usbstoragedriver.py, labgrid/remote/client.py, labgrid/remote/config.py, labgrid/resource/provider.py, labgrid/strategy/shellstrategy.py, labgrid/target.py
Trivial fixes for
- unused imports
- import order
- lazy formatting in logging methods
- unnecessary semicolons
- trailing newlines
**Checklist**
=> Linting fixes

labgrid/resource/suggest.py
Easy usb path retrieval for the HIDRelay.
**Checklist**
=> resource/suggest: add HIDRelay

contrib/sync-places.py
Adds a script that can be used to configure the places a given
coordinator exports via a YAML file. This allows maintenance of cluster
place configuration using automated tools, such as Ansible
**Checklist**
=> contrib: Add script to synchronize places

labgrid/driver/modbusdriver.py
We got a report of a user trying to access a modbus device with the
following error:
```
File "/opt/venvs/labgrid/lib/python3.9/site-packages/labgrid/remote/client.py", line 1638, in main
args.func(session)
File "/opt/venvs/labgrid/lib/python3.9/site-packages/labgrid/remote/client.py", line 814, in digital_io
drv.set(False)
File "/opt/venvs/labgrid/lib/python3.9/site-packages/labgrid/binding.py", line 100, in wrapper
return func(self, *_args, **_kwargs)
File "/opt/venvs/labgrid/lib/python3.9/site-packages/labgrid/driver/modbusdriver.py", line 36, in set
raise ExecutionError('Could not write coil (code={})'.format(error_code))
labgrid.driver.exception.ExecutionError: Could not write coil (code=7)
```
The error code is 7, indicating that an exception …
=> modbusdriver: retrieve exception information

labgrid/driver/shelldriver.py
Based on labgridhelper.linux's `get_interface_ip()` function, introduce methods to retrieve the default route's interface device name as well as IP interfaces.
A `ShellDriver` bound on top of a `SerialDriver` is now able to retrieve the target's IP during runtime. That's useful for targets without a fixed IP. This could allow set up of automated SSH access in a future PR.
**Checklist**
=> driver: shelldriver: add get_default_interface_device_name()/get_ip_interfaces()

doc/configuration.rst, labgrid/driver/httpvideodriver.py, labgrid/driver/usbvideodriver.py, labgrid/protocol/__init__.py, labgrid/protocol/videoprotocol.py, labgrid/remote/client.py, labgrid/remote/exporter.py, labgrid/resource/__init__.py, labgrid/resource/httpvideostream.py, tests/test_httpvideo.py
Adds support for streaming video from IP video sources such as an HDMI
to IP capture device or an IP camera.
**Checklist**
=> Add IP Video support

labgrid/driver/ubootdriver.py
Converts the u-boot driver to use a loop to try an login to the console,
just like the shelldriver does. This ensures that the driver waits for
the console prompt after interrupting and before attempting to enter a
command. Otherwise, if u-boot is not waiting at the prompt it may
occasionally miss the input, causing the test to fail.
**Checklist**
=> ubootdriver: Use a loop to access the u-boot console

labgrid/driver/usbvideodriver.py, labgrid/remote/client.py
This device only support JPEG.
**Checklist**
=> driver/usbvideodriver: add basic MacroSilicon USB Video support

labgrid/remote/client.py
Adds a command line argument to log the output of the console to a file
**Checklist**
=> client: Add logfile for console

doc/getting_started.rst, doc/usage.rst
Minor documentation improvements.
=> doc: simplify getting_started/usage, make installation steps more consistent

labgrid/binding.py, labgrid/driver/filedigitaloutput.py, labgrid/environment.py, labgrid/remote/exporter.py, labgrid/resource/common.py, labgrid/util/ssh.py, mypy.ini
This PR begins to add some mypy annotations to reduce the number of reported issues.
To actually use mypy, we'll probably need to write a plugin to let it understand the bindings mechanism.
=> initial mypy annotations

labgrid/util/proxy.py
Add a ProxyError and check that we have a valid host and port. If we
don't raise a ProxyError with a proper explanation.
**Checklist**
=> proxy: add ProxyError, check host and port

CHANGES.rst
=> CHANGES: update for release v0.4.0

.github/workflows/unit-tests.yml, CHANGES.rst, setup.py
=> Post Release Updates

CHANGES.rst, labgrid/remote/exporter.py, labgrid/util/agents/sysfsgpio.py
Export the sysfs gpios during place acquire/release.
**Checklist**
Fixes https://github.com/labgrid-project/labgrid/issues/856
=> Export sysfs gpios during acquire

README.rst
The README is often the first thing people look at, so it should reflect the state of the projekt accurately. So try to describe the set of labgrid's features on high level.
=> README: update currently supported features

labgrid/driver/httpvideodriver.py, labgrid/driver/shelldriver.py, labgrid/remote/client.py
- drop unused imports
- fix import order
**Checklist**
=> Import fixes

debian/control, doc/index.rst, dockerfiles/README.rst
Small collection of typo fixes in docs.
=> Minor Documentation Typo Fixes

man/labgrid-client.1, man/labgrid-client.rst
Simple fix for the formatting of device-client man page & webpage documentation.
=> docs: Fix formatting of device-client man page

labgrid/remote/client.py
This makes it easier to coordinate with affected users before
reconfiguring an exporter.
Fixes: #782
**Checklist**
=> remote/client: optionally show used exporters with 'who'

labgrid/driver/shelldriver.py
Moves up the call to silence the kernel to the console expect loop. This
ensures that the kernel has been silenced before the prompt is checked,
as dmesg output can interrupt it and cause failures.
**Checklist**
=> shelldriver: Silence kernel earlier

labgrid/driver/openocddriver.py, labgrid/resource/udev.py
Add support for the ST-Link-V3 USB VID/PID and fix an issue caused by a feature check.
=> OpenOCD fix and device support

doc/configuration.rst, tests/conftest.py
Small collection of improvements to stay compatible with recent versions of autobahn/docker dependencies.
Note: preliminary work for relaxed dependencies in pyproject.toml
**Checklist**
=> tests: make tests compatible with recent versions of autobahn/docker

.github/workflows/unit-tests.yml, doc/Makefile, doc/conf.py, setup.cfg
Collection of fixes and improvements regarding doc/man generation.
Note: preliminary work for switch to pyproject.toml.
**Checklist**
=> doc/man: fixes and improvements for recent sphinx doc/man generation

labgrid/driver/power/netio_kshell.py
telnetlib is deprecated since Python 3.11 [1] and will be removed in Python 3.13 [2]. Use pexpect.spawn() with telnet instead. This requires matching more explicit strings and matches here and there.
While at it, send line separators as expected by NetIO devices [3].
Note: I have no NetIO devices available, so I tested the functions with increased timeout against a listening netcat pasting the expected answers [3] manually.
[1] https://docs.python.org/3/library/telnetlib.html
[2] https://peps.python.org/pep-0594/#deprecated-modules
[3] https://www.netio-products.com/files/NETIO-M2M-API-Protocol-Telnet.pdf
**Checklist**
=> driver/power/netio_kshell: pexpect.spawn() telnet rather than deprecated telnetlib

labgrid/driver/__init__.py, labgrid/remote/client.py
Various simplifications and cleanups to make the client code smaller.
No change in client behavior intended.
**Checklist**
=> Client Simplifications And Cleanups

.github/pull_request_template.md
Just a quick fix for a typo I noticed while creating the previous PR
=> github/pull_request_template: Fix a typo

contrib/coordinator-statsd.py
Based on feedback from our statsd team after trying out the reporting, it has been re-worked with several major improvements
1) Sets are now replaced with gauges. While sets are really cool from a
reporting perspective, they are difficult to deal with.
Specifically, it's very hard to report and graph "0" with a set
since that's just the absence of any set items, which could also be
"no data". Instead, use gauges and persistently record which metrics
were reported so that they can be reported as 0 next collection
iteration
2) Add tags to the place reporting, so it can more easily be correlated
to the reservation reporting. It's fairly trivial to sum these out
if desired.
3) Improve failure correction. If either the connection to the statsd
server or labgrid coordinator …
=> contrib: coordinator-statsd: Usability improvements

debian/changelog, debian/labgrid.manpages
- add man pages to debian packaging
- add 0.3.0 and 0.4.0 to changelog
=> debian: add manpages, update changelog

doc/getting_started.rst
I hope I have this understanding right
Signed-off-by: Simon Glass <sjg@chromium.org>
**Checklist**
=> Fix minor typo

doc/overview.rst
Signed-off-by: Simon Glass <sjg@chromium.org>
**Checklist**
=> Fix a typo

labgrid/driver/powerdriver.py
This should help a bit with the startup time.
**Checklist**
=> driver/powerdriver: import urllib only when needed

examples/deditec-relais8/deditec.py, examples/deditec-relais8/deditec_remote.py, examples/library/test.py, examples/networkmanager/nm.py, examples/sysfsgpio/sysfsgpio.py, examples/sysfsgpio/sysfsgpio_remote.py, labgrid/autoinstall/main.py, labgrid/remote/client.py, labgrid/stepreporter.py, pyproject.toml
This contains some of the changes from the logging rework (#1106), which can be done early to make the rest easier to review.
=> preparation for logging rework

labgrid/remote/client.py
Add the ability for labgrid-client to use the crossbar URL coming from the configuration file.
The crossbar URL come from (first wins):
- -x/--crossbar parameter
- crossbar_url in configuration file
- LG_CROSSBAR environment variable
- default: "ws://127.0.0.1:20408/ws"
**Checklist**
- The documentation is already there (man/labgrid-device-config.rst)
- Only manual test, with a configuration file having the crossbar_url option.
=> remote/client: use crossbar_url from configuration file

CHANGES.rst, README.rst
Changelog update to prepare for the release.
=> CHANGES: update CHANGES.rst for 23.0

tests/test_modbusrtudriver.py, tests/test_powerdriver.py
Fixes for tests found while updating the NixOS package.
**Checklist**
=> Various Test Fixes

.github/workflows/build-and-release.yml
We don't need to be limited to source distribution, also build and release a wheel package.
**Checklist**
=> github/build-and-release: also build wheel

CHANGES.rst
Import them from the stable branch.
**Checklist**
=> CHANGES: add bug fixes from 23.0.1

README.rst, doc/getting_started.rst
The main point of this PR is to document pip installation of labgrid via PyPi. While at it, add minor improvements for README and docs.
=> README and documentation improvements

.github/workflows/reusable-unit-tests.yml, README.rst
Fix RST parser warnings [1] and introduce a check to prevent this in the future.
[1] https://github.com/labgrid-project/labgrid/actions/runs/4859541942/jobs/8662458044
**Checklist**
Fixes #1160
=> README: fix RST syntax and introduce check

pyproject.toml
Add classifiers for audience, development status, OS and license.
=> pyproject: add more classifiers

contrib/coordinator-statsd.py
txaio was not configured to use asyncio which resulted in some failures when attempting to communicate with the coordinator.
**Checklist**
=> contrib: coordinator-statsd: Configure txaio

labgrid/resource/udev.py
This PR adds STLink V2 vendor and model to the USBDebugger resource. The code has been tested on a distributed labgrid testing system.
**Checklist**
=> Add vendor and model id of STLink V2 to USBDebugger resource

doc/configuration.rst
* doc/configuration: drop "optional" from driver arguments with default value
* doc/configuration: add empty lines around each list level
**Checklist**
Fixes #1092
=> doc/configuration: syntax fixes

.github/workflows/build-and-release.yml, .github/workflows/docker.yml, .github/workflows/reusable-unit-tests-docker.yml, .github/workflows/reusable-unit-tests.yml
Bump all actions to the latest versions available.
**Checklist**
=> github: workflows: update GitHub actions to latest versions

tests/test_target.py
This came up in an IRC discussion where the reporter said that this
raised some issues for him. The core library already supports this, add
a test to ensure the support stays.
**Checklist**
=> tests: test different resources having a default

labgrid/driver/sshdriver.py
While it is not normally expected for the keepalive process to produce any output, it can be helpful for debugging purposes to log any output it may have produced. As such, try harder to get output when terminating the process, and also report any output after it exits
**Checklist**
=> sshdriver: Log keepalive output

labgrid/driver/sigrokdriver.py
Minor improvements discovered in #1141 that don't fit in another PR.
**Checklist**
=> Minor Sigrok Improvements

labgrid/remote/client.py, labgrid/remote/common.py, labgrid/remote/config.py, labgrid/remote/coordinator.py, labgrid/remote/exporter.py, pyproject.toml
This should make it easier to review the gRPC migration.
=> configure ruff format and run it on all remote modules

doc/configuration.rst, doc/development.rst, labgrid/logging.py
Fix class name in StepLogger warning and document StepLogger.
**Checklist**
Fixes #1155
=> StepLogger documentation and warning fix

CHANGES.rst
Final updates for 24.0 release.
=> CHANGES: more updates for 24.0 release

README.rst
Add links to the youtube tutorial series and getting started section of the documentation on readthedocs.
=> README: add getting started section

doc/conf.py, man/Makefile, man/labgrid-client.1, man/labgrid-coordinator.1, man/labgrid-device-config.5, man/labgrid-exporter.1, man/labgrid-pytest.7, man/labgrid-suggest.1
Add support for sphinx_rtd_theme 3.0.0.
**Checklist**
=> doc: add support for sphinx_rtd_theme 3.0.0

CHANGES.rst
Hi,
I was asked by @jluebbe to proofread the 25.0 changelog / release notes.
I did not find any real issues with it. My only suggestion is to display a more prominent warning about 25.0 being incompatible with any other version, when it comes to network communication.
=> Proofread Changelog for 25.0

labgrid/driver/shelldriver.py
Because of limits to the number of characters allowed on the command line, break up the writing public ssh keys into 100 character chunks.
Fixes #1627
=> ShellDriver: put_key_file: write keys in chunks of 100 chars

doc/usage.rst
=> doc/usage: Trivial grammar fix

doc/configuration.rst
Describe missing network resources and make documentation of existing network resources more consistent.
=> doc: describe all network resources

doc/overview.rst
Replace old "router" terminology with "Coordinator".  This seems to have been missed by e0167aeebc8119a01673a5276ecfdaa402af9f3f.
=> doc: fix use of old and confusing router terminology
